### ISSUE TITLE
Support for ES 2.3.1

### ISSUE THREAD

**Issue by nakjunizm** [sscarduzio/elasticsearch-readonlyrest-plugin#103]
I was wondering if I can use your plug-in for ES 2.3.1 version.
In my system I have ES 2.3.1 cluster but my boss does not want to upgrade to 2.3.5.

So I tried to unzip elasticsearch-readonlyrest-v1.9.5_es-v2.3.5.zip and modify plugin-descriptor.properties and zip again.
It works fine on 2.3.1 but I am not sure I should do it in this way.
All I need is host based ACL.

**Comment by sscarduzio** [comment]
Hey @nakjunizm I just released a unit and integration tested build for you. 
You can follow this: https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin#1-install-the-plugin

The available ES version builds of the latest plugin code are listed here:
https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/tags

**Comment by nakjunizm** [comment]
Thanks for your quick response
