### ISSUE TITLE
Forbidden problems with the last version 2.4.0

### ISSUE THREAD

**Issue by dfaropennetwork** [sscarduzio/elasticsearch-readonlyrest-plugin#104]
Hi scarduzio,

I've problems with the last plugin version 3.4.0

Now on my infraestructure we have the elasticsearch 3.4.9 version and logstash 3.4.0 version.

Elasticsearch log:

[2016-10-03 21:31:48,464][INFO ][plugin.readonlyrest.acl  ] no block has matched, forbidding by default: { action: indices:data/write/bulk, OA:10.100.0.4, indices:[filebeat-2016.10.03 %{[@metadata][beat]}-2016.10.03], M:POST, P:/_bulk, C:<not available>, Headers:[]}
[2016-10-03 21:31:50,495][INFO ][plugin.readonlyrest.acl  ] no block has matched, forbidding by default: { action: indices:data/write/bulk, OA:10.100.0.4, indices:[filebeat-2016.10.03 %{[@metadata][beat]}-2016.10.03], M:POST, P:/_bulk, C:<not available>, Headers:[]}
[2016-10-03 21:31:52,528][INFO ][plugin.readonlyrest.acl  ] no block has matched, forbidding by default: { action: indices:data/write/bulk, OA:10.100.0.4, indices:[filebeat-2016.10.03 %{[@metadata][beat]}-2016.10.03], M:POST, P:/_bulk, C:<not available>, Headers:[]}
[2016-10-03 21:31:54,600][INFO ][plugin.readonlyrest.acl  ] no block has matched, forbidding by default: { action: indices:data/write/bulk, OA:10.100.0.4, indices:[filebeat-2016.10.03 %{[@metadata][beat]}-2016.10.03], M:POST, P:/_bulk, C:<not available>, Headers:[]}

logstash log:

stash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/pipeline.rb:232:in `worker_loop'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/pipeline.rb:201:in `start_workers'"], :level=>:error}
{:timestamp=>"2016-10-03T21:30:29.447000+0000", :message=>"[401] Forbidden by ReadonlyREST ES plugin", :class=>"Elasticsearch::Transport::Transport::Errors::Unauthorized", :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.1.0/lib/elasticsearch/transport/transport/base.rb:201:in `__raise_transport_error'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.1.0/lib/elasticsearch/transport/transport/base.rb:312:in `perform_request'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.1.0/lib/elasticsearch/transport/transport/http/manticore.rb:67:in `perform_request'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.1.0/lib/elasticsearch/transport/client.rb:128:in `perform_request'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-api-1.1.0/lib/elasticsearch/api/actions/bulk.rb:93:in `bulk'", 

With the 2.3.0 version the same configuration working correctly (logstash user and password, elasticsearch reaadonly plugin configuration etc...)

 readonlyrest:
    enable: true
    response_if_req_forbidden: Forbidden by ReadonlyREST ES plugin
    access_control_rules:

    - name: "Logstash can write and create its own indices"
      auth_key: logstash:lalalala
      type: allow
      actions: ["indices:data/read/*","indices:data/write/*","indices:admin/template/*","indices:admin/create","indices:data/write/bulk"]
      indices: [ "logstash-*", "filebeat-*", "packetbeat-*", "topbeat-*", "<no-index>" ,".marvel*"]

and logstash configuration:
~$ cat /etc/logstash/conf.d/beats-output.conf 
output {
  elasticsearch {
  #elasticsearch_java {
  hosts => ["localhost:9200"]
  #network_host => ["localhost:9200"]
  #sniffing => true
  #manage_template => false
  index => "%{[@metadata][beat]}-%{+YYYY.MM.dd}"
  document_type => "%{[@metadata][type]}"
  user     => "logstash"
  password => "lalalala"
  }
}

**Comment by sscarduzio** [comment]
Hey @dfaropennetwork there must be a mistake, because we don't have a 3.4.x version of Elasticsearch or readonlyrest plugin. 

- What's the plugin version (includes ES version, e.g. `v1.10.0_es-v2.4.0`)
- please show the ES configuration (including the plugin configuration section)
- what is your use case? What do you want to achieve?

**Comment by dfaropennetwork** [comment]
I want to restrict the index modifications for some users, but i was working your plugin perfectly on the previous version.

Sorry i was a mistake i wanted to say a elasticsearch 2.4.0 version and logstash version 2.4.0

i sahred with you my elasticsearch configuration 

[](http://pastebin.com/REqwzWHP)

**Comment by sscarduzio** [comment]
sorry it took time to get back to you, but the pastebin is not working anymore, is this issue still valid or you figured out something?
