### ISSUE TITLE
network.host configuration and read only rest enabled break restarting of elasticsearch

### ISSUE THREAD

**Issue by evolutivo** [sscarduzio/elasticsearch-readonlyrest-plugin#112]
Hi, 
if I set the network.host to the public ip of the server in the configuration file and enable the read only rest plugin too , elasticsearch fails starting from ./bin/elasticsearch or from service.

I have an elasticsearch 2.4.1 version , Ubuntu 14.04 server. Testet it with java 1.7 and 1.8

Am I doing something wrong ?

**Comment by sscarduzio** [comment]
Interesting. Do you have any stack trace?

**Comment by evolutivo** [comment]
I found out it's not only the network.host but every line I remove the comment from, e.g
cluster.name: elasticsearch
When every line of the config file is commented,everything is fine and elasticsearch starts correctly enabling the plugin. 
When I remove the comment and start elasticsearch with ./bin/elasticsearch I get this error:

Exception in thread "main" SettingsException[Failed to load settings from [elasticsearch.yml]]; nested: ElasticsearchParseException[malformed, expected end of settings but encountered additional content starting at line number: [95], column number: [1]]; nested: MarkedYAMLException[expected '<document start>', but found BlockMappingStart
 in 'reader', line 95, column 1:
    readonlyrest:
    ^

 at [Source: # ======================== Elasticsearch Configuration =========================




Then it shows almost all the config file and at the end:

 line: 95, column: 1]]; nested: ParserException[expected '<document start>', but found BlockMappingStart
 in 'reader', line 95, column 1:
    readonlyrest:
    ^
];
Likely root cause: expected '<document start>', but found BlockMappingStart
 in 'reader', line 95, column 1:
    readonlyrest:
    ^



It doesn't happen when I remove comments from lines but I don't have the lines of read only rest in the config file

**Comment by sscarduzio** [comment]
Yep it’s an indentation problem, super annoying I know! I found online YML formatters quite helpful.

**Comment by evolutivo** [comment]
Yes it was indeed an indentation problem. Didn't know this could happen. Thank you!
