### ISSUE TITLE
Setting localhost full access gives full access to Kibana with no login

### ISSUE THREAD

**Issue by teebu** [sscarduzio/elasticsearch-readonlyrest-plugin#113]
Can you confirm this. When I have this, anyone loading Kibana (not locally) doesn't ask for login and has full access to Sense as well.

```
    - name: Accept all requests from localhost
      type: allow
      hosts: [localhost, 127.0.0.1]
```

**Comment by sscarduzio** [comment]
If you only have that block, you should get "forbidden by default". Unless you're using a local proxy to accept those external connections (have a look at logs to what's the origin host the plugin is detecting )

**Comment by sscarduzio** [comment]
Btw in the proxy case you can use he "x forwarded for" header to detect hosts (there's a plugin rule for that)

**Comment by sscarduzio** [comment]
Also, where is your kibana daemon running?

**Comment by teebu** [comment]
same machine

**Comment by ld57** [comment]
Hi, 
my 50cts,

on my side kibana also works on same node, and I confirm the behavior.

in fact, on my side, since I use stunnel, I always come from 127.0.0.1  - it means this rule give access to all my stuff - will check the x-forwarding for that

But, if all rule blocks have a auth_key(_sha1) defined, then everystuff|body will need credential.

**Comment by sscarduzio** [comment]
I had to spin a linode server to see what was going on here. 

### What happens
Normally, Kibana proxies the `/elasticsearch/*` requests towards ES  and forwards the Authorization headers.
ReadonlyREST seeing the proxied requests coming from 127.0.0.1, always accepts the requests and never sends out a 401.
A browser needs a 401 for showing the username/password prompt.
Kibana is completely open with no login.

### Solution
Kibana should always be configured *with its own login* as explained in the README.md. Do not use any other white listing rule for Kibana.

**Comment by sscarduzio** [comment]
I'd say this was basically a configuration issue/pitfall.
