### ISSUE TITLE
readonly plugin blocking curtor (cant delete the indexes)

### ISSUE THREAD

**Issue by pramod08** [sscarduzio/elasticsearch-readonlyrest-plugin#118]
Hello

Am using curator for deleting indices in elasticseach ..
plugins installed
1.readonlyrest-plugin
2.head
3.Installed curator using pipe

elasticsearch version = 2.4

when i run manually the curator (3.5.1 )
curator delete indices --older-than 1 --time-unit days --timestring %Y.%m.%d

it will block by the readonly-plugin
The bellow Error as i run above command by manually
curator delete indices --time-unit days --timestring %Y.%m.%d
2016-10-24 17:51:44,977 INFO Job starting: delete indices
2016-10-24 17:51:44,988 ERROR Failed to get indices.
2016-10-24 17:51:44,988 ERROR No indices found in Elasticsearch
ERROR. No indices found in Elasticsearch.
  #791

**Comment by sscarduzio** [comment]
Well, unfortunately I have zero context to help you. All depends on how you configured readonly rest. Plus it's not clear what is your use case and the desired behaviour.
