### ISSUE TITLE
Initialization should fail if unknown rule is detected (prevents dangerous typos)

### ISSUE THREAD

**Issue by ld57** [sscarduzio/elasticsearch-readonlyrest-plugin#123]
Hi sscarduzio,

I just tested the 1.12 release on es 2.4.1 and, by doing a mistake, I found something which, imo should not happen : 

here a simple rule block, correctly indented, between several other rules block : 
```
   - name: ELKG admin Fred
      auth_key_sha1: 178636ad804e597e14aac3c6f610af8c1bcf7661989e17c4a6950044f61ab1bc
      type: allow
      actions: ["cluster:*", "indices:*", "org.xbib.elasticsearch.knapsack.*"]
```
This rule block works fine, users are prompted for basic auth, for this or others rules restricting access, everything is running as intended.

now, I did a mispell for `auth_key_sha2`  (as noticed, would not work, no sha2 supported)
it gives to me this rule block as

```
   - name: ELKG admin Fred
      auth_key_sha2: 178636ad804e597e14aac3c6f610af8c1bcf7661989e17c4a6950044f61ab1bc
      type: allow
      actions: ["cluster:*", "indices:*", "org.xbib.elasticsearch.knapsack.*"]
```

well, this "mispell" is not notified as "misconfiguration" in any logs (but not the purpose of this post here), but the unexpected behavior is that the auth parameter is ignored, and then the rule applies to all users.
In the described rule above, it gave full access to everybody (users or anonymous), without prompting for credentials.

In next release, would it be possible to reject or ignore completely a rule block if inside a parameter is mispelled ?

Regards,

Ld

**Comment by sscarduzio** [comment]
Good one, the plugin should fail when there's extraneous configuration
