### ISSUE TITLE
defining all access as auth_key_sha1 produces unexpected behavior regarding basic credential request from browser

### ISSUE THREAD

**Issue by ld57** [sscarduzio/elasticsearch-readonlyrest-plugin#124]
Hi again,

Still on ES 2.4.1 and ROR 1.12 .  (browser ie 11 and firefox 49.0.2)
It has been reproduced on my prod and test environnment.

In fact I enjoyed to convert all credentials in elasticsearch.yml to auth_key_sha1 .
No problem until I tried to access some plugin by http://localhost:9200/_plugin/xxxx ( like kopf, bigdesk, etc). and also when I tried to run kibana : 

if all authentication have been configured as auth_key_sha1 , then you won't be prompted anymore in your browser to reach data . in fact, you will never be able to access to your data, since you never get prompted.
Regarding application (kibana, beats, logstash etc), it still works fine.

In my opinion it does not need a fix, since a simple workaround in rules configuration is possible : 
I just created a rule block with just auth_key configuration : this permits to prompt for credential in browser : 

```
    - name: Dummy (to permit request for basic authentication popup)
      auth_key: dummy:dummy
      type: forbid

```

If you agree it is an expected behavior and would not require a fix, then let me know and I will add this to Wiki 

regards,

Ld

**Comment by nitram4** [comment]
I have mentioned it in issue #115 as very similiar issue"

Testing this release but, having issues when combining with auth_key_sha1 nad Group function. Only working when not using any limitations.

This is not working, not accepting password

```
    - name: User
      type: allow
      indices: ["<no-index>", ".kibana*", "logstash-*", logstash-app-*, .marvel-es-1-*,  "default", ".marvel*"]
      kibana_access: ro+
      auth_key: xxxx:xxxx
```

but it works with this :

```
    - name: Admin
      type: allow
      kibana_access: rw
      auth_key: XXX:XXXX
```
and this works also with auth_key_sha1.

**Comment by ld57** [comment]
Hi,

as promised , here a sample of my rules blocks (these rules works fine on my side - Since it is a test server I volontary let some auth_key normal, and some in sha1 - also I use some different kind of rules)

` readonlyrest:
    enable: true
    response_if_req_forbidden: Forbidden by ReadonlyREST ES plugin
    access_control_rules:

    - name: "Logstash can write and create its own indices"
      auth_key: logstash:logstash
      type: allow
      actions: ["indices:data/read/*","indices:data/write/*","indices:admin/template/*","indices:admin/create"]
      indices: ["logstash-*", "<no-index>", "log*"]
      
    - name: "metricbeat can write and create its own indices"
      auth_key: metricbeat_test:metricbeat_test
      type: allow
      actions: ["indices:data/read/*","indices:data/write/*","indices:admin/template/*","indices:admin/create"]
      indices: ["metricbeat-*", "<no-index>", "log_metricbeat*"]


    - name: ELKG admin Fred
      auth_key: admtest:admtest
      type: allow
      actions: ["cluster:*", "indices:*", "org.xbib.elasticsearch.knapsack.*"]

      
    - name: Kibana Server (we trust this server side component, full access granted via HTTP authentication)
      auth_key: kibana_test:kibana_test
      type: allow
      hosts: [127.0.0.1]

    - name: Developer (prevent api access)
      auth_key_sha1: 465462126162ddeefeeb6916ae0a09
      type: forbid
      uri_re: (_node|_cluster|_cat|_task|_plugin)
      
    - name: Developer (reads only defined indices, can view dashboard but can not create new charts/dashboards)
      auth_key_sha1: 465462126162ddeefeeb6916ae0a09
      type: allow
      kibana_access: ro
      indices: ["<no-index>", ".kibana*", "log_sec*"]`

will test group today, but pretty sure it works fine.
