### ISSUE TITLE
X-Api-Key and indices with *

### ISSUE THREAD

**Issue by psaiz** [sscarduzio/elasticsearch-readonlyrest-plugin#128]
Hi, 

Thanks for this plugin. It is very useful, and I'm using it for setting up a read only kibana.

I wanted to extend the usage a bit more, and do some index level security, and i'm running into two different issues. Let me know if you prefer two independent tickets. 

1. I don't seem to manage to pass the X-Api-Key.  If I do something like:

```
 curl -H  'X-Api-Key: 1234567890'   -X PUT <host>:9200/psaiz/balbal/1 -d '{"hello":"world"}'
```
I see this on the logfile (note the empty headers)
```
[DEBUG][plugin.readonlyrest.acl.blocks.rules.impl] KIBANA ACCESS DENIED { action: indices:data/write/index, OA:host, indices:[psaiz], M:PUT, P:/psaiz/balbal/1, C:{"hello":"world"}, Headers:[]}
```
 I've seen that the 'X-Forwarded-For' does work, so at the moment I'm using that one instead of X-Api-Key

2. If I put on the configuration a rule like:
```
  - name: "Test user"
    hosts: [6.6.6.6]
    accept_x-forwarded-for_header: true
    type: allow
    indices:
      - psaiz*
```
I'm  surprised that I can put to any index that contains 'psaiz', (even if it does not start with it!). Is that intended?

```
 curl -H 'X-Forwarded-For: 6.6.6.6'  -X PUT <host>:9200/psaiz/balbal/1 -d '{"hello":"world"}';

{"_index":"psaiz","_type":"balbal","_id":"1","_version":12,"_shards":{"total":3,"successful":3,"failed":0},"created":false}


 curl -H 'X-Forwarded-For: 6.6.6.6'  -X PUT <host>/another_p_saiz/balbal/1 -d '{"hello":"world"}';

Sorry, your request is forbidden.

 curl -H 'X-Forwarded-For: 6.6.6.6'  -X PUT <host>/another_psaiz/balbal/1 -d '{"hello":"world"}'

{"_index":"another_psaiz","_type":"balbal","_id":"1","_version":6,"_shards":{"total":3,"successful":3,"failed":0},"created":false}
```

Thanks again, 
pablo

**Comment by sscarduzio** [comment]
Thank you @psaiz for reporting this, sorry for the delay. Will issue new builds soon.

**Comment by psaiz** [comment]
Hi, 
Thanks for the fix. That will take care of the pattern matching. For the other question, concerning the 'X-Api-Key', am I doing something wrong? Should I open a different ticket?

Cheers, 
pablo

**Comment by sscarduzio** [comment]
X-Api-Key works for me, is this still an issue?
