### ISSUE TITLE
can increase the control rules to support the third party interface

### ISSUE THREAD

**Issue by zhengqisong** [sscarduzio/elasticsearch-readonlyrest-plugin#131]
control rules read from other system， for example：

- name: "api can write and create its own indices"
  type: allow
  api_url: http://10.0.2.80:9200/readonlyrest/acl/authlist
  cache_time: 2

**Comment by sscarduzio** [comment]
Hi @zhengqisong, not sure I understand: what would the response to - I assume  GET - `http://10.0.2.80:9200/readonlyrest/acl/authlist` look like?

_S

**Comment by zhengqisong** [comment]
add ApiUrlRule class  and change Block class

ApiUrlRule  code:

package org.elasticsearch.plugin.readonlyrest.acl.blocks.rules.impl;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import java.util.regex.PatternSyntaxException;

import org.apache.logging.log4j.Logger;
import org.elasticsearch.common.logging.ESLogger;
import org.elasticsearch.common.logging.ESLoggerFactory;
import org.elasticsearch.common.logging.Loggers;
import org.elasticsearch.common.settings.Settings;
import org.elasticsearch.plugin.readonlyrest.ConfigurationHelper;
import org.elasticsearch.plugin.readonlyrest.ReadonlyRestAction_bak;
import org.elasticsearch.plugin.readonlyrest.acl.RequestContext;
import org.elasticsearch.plugin.readonlyrest.acl.RuleConfigurationError;
import org.elasticsearch.plugin.readonlyrest.acl.blocks.Block;
import org.elasticsearch.plugin.readonlyrest.acl.blocks.BlockExitResult;
import org.elasticsearch.plugin.readonlyrest.acl.blocks.rules.Rule;
import org.elasticsearch.plugin.readonlyrest.acl.blocks.rules.RuleExitResult;
import org.elasticsearch.plugin.readonlyrest.acl.blocks.rules.RuleNotConfiguredException;
import org.elasticsearch.plugin.readonlyrest.util.HttpRequest;

public class ApiUrlRule extends Rule {
	private final static Logger logger = ESLoggerFactory.getLogger(ApiUrlRule.class);
	  
	private final static String RULES_PREFIX = "access_control_rules";
	private final static String USER_PREFIX = "users";
	
	String apiUrl = null;
	Map<String, String[]> apiRule = new HashMap<String,String[]>();
	int catchTime = 2;
	public ApiUrlRule(Settings s) throws RuleNotConfiguredException {
	    super(s);
	    String tmp = s.get(KEY);
	    catchTime = s.getAsInt("cache_time", 2);
	    if (!ConfigurationHelper.isNullOrEmpty(tmp)) {
	      try {
	    	  apiUrl = tmp;
	      }
	      catch (PatternSyntaxException e) {
	        throw new RuleConfigurationError("invalid 'api_url' paramters", e);
	      }
	    }
	    else {
	      throw new RuleNotConfiguredException();
	    }
	}

	protected Settings getBlockSettings(String apiUrl, String authHeader){
		String ruleStr = null;
		try{
			String[] ruleArray = apiRule.get(authHeader);
			Date dt = new Date();
			
			if(ruleArray != null && Long.toString(dt.getTime()).compareTo(ruleArray[1]) < 0){
				ruleStr = ruleArray[2];
			}
			if(ruleStr == null) {
				try {
					Iterator<String> iterator = apiRule.keySet().iterator();
					if(iterator.hasNext()){
						String key = iterator.next();
						String[] tmp_ruleArray = apiRule.get(key);
						if(tmp_ruleArray != null && dt.getTime() > Long.parseLong(tmp_ruleArray[1]) + (catchTime+1) * 60){
							apiRule.remove(key);
						}
					}
					Map<String,String> headerMap = new HashMap<String,String>();
					headerMap.put("Authorization", authHeader);
					ruleStr = HttpRequest.sendPost(apiUrl, null, headerMap);
					
					if(ruleStr==null || ruleStr.equals("")){
						throw new Exception();
					}
					Calendar nowTime = Calendar.getInstance();
					nowTime.add(Calendar.SECOND, catchTime);					
					String[] tmp = {authHeader, Long.toString(nowTime.getTime().getTime()), ruleStr};
					apiRule.put(authHeader, tmp);
				} catch(Exception ex){
					if(ruleArray != null){
						ruleStr = ruleArray[2];
					}
				}
			}
			Settings g = Settings.builder().loadFromSource(ruleStr).build();
			
			return g;
		}catch(Exception ex){
			logger.info("get rule error from "+apiUrl);
			return null;
		}
	}
	
	@Override
	public RuleExitResult match(RequestContext rc) {
		// TODO Auto-generated method stub
		//String authHeader = AuthKeyRule.extractAuthFromHeader(rc.getRequest().header("Authorization"));
		String authHeader = rc.getRequest().header("Authorization");
		if(authHeader==null || authHeader.equals("")){
			logger.info("no authHeader ");
			return NO_MATCH;
		}
		
		try{
			Settings g = getBlockSettings(apiUrl, authHeader);
			Map<String, Settings> s = g.getGroups(RULES_PREFIX);
			Map<String, Settings> users = g.getGroups(USER_PREFIX);
			for (String k : s.keySet()) {
				Block block = new Block(s.get(k), new ArrayList<>(users.values()), logger);
				BlockExitResult result = block.check(rc);
			    if (result.isMatch()) {
			       logger.debug("Block " + block.getName() + " has matched: " + result);
			       return MATCH;
			    }
			}
		}catch(Exception ex){
		}
		return NO_MATCH;
	}

}

package org.elasticsearch.plugin.readonlyrest.acl.blocks;

import com.google.common.collect.Sets;
import org.elasticsearch.common.logging.ESLogger;
import org.elasticsearch.common.settings.Settings;
import org.elasticsearch.plugin.readonlyrest.acl.RequestContext;
import org.elasticsearch.plugin.readonlyrest.acl.RuleConfigurationError;
import org.elasticsearch.plugin.readonlyrest.acl.blocks.rules.Rule;
import org.elasticsearch.plugin.readonlyrest.acl.blocks.rules.RuleExitResult;
import org.elasticsearch.plugin.readonlyrest.acl.blocks.rules.RuleNotConfiguredException;
import org.elasticsearch.plugin.readonlyrest.acl.blocks.rules.impl.*;

import java.util.List;
import java.util.Set;

import static org.elasticsearch.plugin.readonlyrest.ConfigurationHelper.*;

Block  code:

/**
 * Created by sscarduzio on 13/02/2016.
 */
public class Block {
  private ESLogger logger;

  private final String name;
  private final Policy policy;
  private boolean authHeaderAccepted = false;
  private Set<Rule> conditionsToCheck = Sets.newHashSet();

  public Block(Settings s, List<Settings> userList, ESLogger logger) {
    this.name = s.get("name");
    String sPolicy = s.get("type");
    this.logger = logger;
    if (sPolicy == null) {
      throw new RuleConfigurationError("The field \"type\" is mandatory and should be either of " + Block.Policy.valuesString() + ". If this field is correct, check the YAML indentation is correct.", null);
    }


    policy = Block.Policy.valueOf(sPolicy.toUpperCase());

    // Won't add the condition if its configuration is not found
    try {
      conditionsToCheck.add(new HostsRule(s));
    } catch (RuleNotConfiguredException e) {
    }
    try {
      conditionsToCheck.add(new ApiKeysRule(s));
    } catch (RuleNotConfiguredException e) {
    }
    try {
      conditionsToCheck.add(new AuthKeyRule(s));
      authHeaderAccepted = true;
    } catch (RuleNotConfiguredException e) {
    }
    try {
      conditionsToCheck.add(new UriReRule(s));
    } catch (RuleNotConfiguredException e) {
    }
    try {
      conditionsToCheck.add(new MaxBodyLengthRule(s));
    } catch (RuleNotConfiguredException e) {
    }
    try {
      conditionsToCheck.add(new MethodsRule(s));
    } catch (RuleNotConfiguredException e) {
    }
    try {
      conditionsToCheck.add(new KibanaAccessRule(s));
    } catch (RuleNotConfiguredException e) {
    }
    try {
      conditionsToCheck.add(new IndicesRule(s));
    } catch (RuleNotConfiguredException e) {
    }
    try {
      conditionsToCheck.add(new ActionsRule(s));
    } catch (RuleNotConfiguredException e) {
    }
    try {
      conditionsToCheck.add(new AuthKeySha1Rule(s));
      authHeaderAccepted = true;
    } catch (RuleNotConfiguredException e) {
    }
    try {
      conditionsToCheck.add(new GroupsRule(s, userList));
    } catch (RuleNotConfiguredException e) {
    }
  }

  public String getName() {
    return name;
  }

  public Policy getPolicy() {
    return policy;
  }

  public boolean isAuthHeaderAccepted() {
    return authHeaderAccepted;
  }

  public enum Policy {
    ALLOW, FORBID;

    public static String valuesString() {
      StringBuilder sb = new StringBuilder();
      for (Policy v : values()) {
        sb.append(v.toString()).append(",");
      }
      sb.deleteCharAt(sb.length() - 1);
      return sb.toString();
    }
  }

  /**
   * Check all the conditions of this rule and return a rule exit result
   *
   */

  public BlockExitResult check(RequestContext rc) {
    boolean match = true;
    for (Rule condition : conditionsToCheck) {
      // Exit at the first rule that matches the request
      RuleExitResult condExitResult = condition.match(rc);
      // a block matches if ALL rules match
      match &= condExitResult.isMatch();
    }
    if (match) {
      logger.debug(ANSI_CYAN + "matched " + this + ANSI_RESET);
      return new BlockExitResult(this, true);
    }
    logger.debug(ANSI_YELLOW + "[" + name + "] the request matches no rules in this block: " + rc + ANSI_RESET);

    return BlockExitResult.NO_MATCH;
  }

  @Override
  public String toString() {
    return "readonlyrest Rules Block :: { name: '" + name + "', policy: " + policy + "}";
  }
}
