### ISSUE TITLE
Build for ES 2.2.0

### ISSUE THREAD

**Issue by ammkha** [sscarduzio/elasticsearch-readonlyrest-plugin#132]
Is there a build for ES 2.2.0?

**Comment by sscarduzio** [comment]
https://readonlyrest.com/#download

**Comment by ammkha** [comment]
Thanks @sscarduzio 
I am getting the 'error sending email' (server error) on downloading it.

**Comment by sscarduzio** [comment]
Tell me what's your email using the chat tool in the website, so I can try to debug the website.

**Comment by sscarduzio** [comment]
so turns out Amazon SES went in sandbox mode.. Requested support. In the meanwhile I added more error messages to tell people to ask for builds in the chat box

**Comment by sscarduzio** [comment]
There was a problem with SES, now the website works again!

**Comment by ammkha** [comment]
Great, Thanks again! 👍
