### ISSUE TITLE
why GPLv3 license ?

### ISSUE THREAD

**Issue by theetete** [sscarduzio/elasticsearch-readonlyrest-plugin#134]
Hi,
can you expose the motivation behind recent changes of license from MIT to GPLv3?

**Comment by sscarduzio** [comment]
Hello @theetete, excellent question!

Here is a summary of the effect that the license change from MIT to GPLv3 has for the users:

### What does NOT change
* You can still deploy the plugin commercially, no question asked (the same way you deploy a linux server!).
* If you deployed and sold a modified version of the plugin when it was MIT licensed, you don't need to open source your changes.
* The GPLv3 license will still allow anybody to sell derived work (i.e. a forked version) for money, provided that the source is made available under the GPLv3 or compatible license.

### What does change
* The GPLv3 license will prevent forking and selling any derived work as closed source.
* If you customise the code of the plugin, it's illegal to sell it as closed source. You will need to release the changes under a GPL compatible license, or (preferrably) contribute them back to the main project as pull requests.

Lastly - although at the moment I cannot see why/how this may ever be needed - the owner of the copyright on the software (me) still has the right to ad-hoc re-license the software to selected individuals/companies once an agreement is reached.
