### ISSUE TITLE
update pre package to ES 5.1.1

### ISSUE THREAD

**Issue by danielmotaleite** [sscarduzio/elasticsearch-readonlyrest-plugin#135]
I was about to try the new PRE version compatible with 5.x, but your package is for 5.0.1 and ES is now at 5.1.1 (no 5.1.0 was released), so can you please update it

Thanks

**Comment by sscarduzio** [comment]
Check the website http://readonlyrest.com

**Comment by danielmotaleite** [comment]
Already installed it and it is working fine, Thanks!
