### ISSUE TITLE
Can't install on ES 5.0.2

### ISSUE THREAD

**Issue by enp** [sscarduzio/elasticsearch-readonlyrest-plugin#136]
Hi,

Can't install downloaded plugin on ES 5.0.2:

> [elastic@elastic elasticsearch]$ bin/elasticsearch-plugin install ~/readonlyrest-v1.13.0-pre1_es5.0.1.zip 
> A tool for managing installed elasticsearch plugins
> 
> Commands
> --------
> list - Lists installed elasticsearch plugins
> install - Install a plugin
> remove - Removes a plugin from elasticsearch
> 
> Non-option arguments:
> command              
> 
> Option         Description        
> ------         -----------        
> -h, --help     show help          
> -s, --silent   show minimal output
> -v, --verbose  show verbose output
> ERROR: Unknown plugin /home/elastic/readonlyrest-v1.13.0-pre1_es5.0.1.zip

**Comment by enp** [comment]
Sorry, forgot about 'file:' before plugin file name, so will be better to fix email

**Comment by sscarduzio** [comment]
Thanks fixed the email 👍
