### ISSUE TITLE
ES/Kibana 5.1.1 support is broken

### ISSUE THREAD

**Issue by enp** [sscarduzio/elasticsearch-readonlyrest-plugin#137]
Hi,

I can't work with ES/Kibana 5.1.1. My ES config looks like:

> readonlyrest:
>     enable: true
>     response_if_req_forbidden: Access is forbidden
> 
>     access_control_rules:
> 
>     # We trust this server side component, full access granted via HTTP authentication
>     - name: "::KIBANA-SRV::"
>       auth_key: kibana:kibana
>       type: allow

Kibana config looks like:

> server.port: 5602
> server.host: "0.0.0.0"
> 
> elasticsearch.username: "kibana"
> elasticsearch.password: "kibana"

On running Kibana I see:

> 
> [elastic@elastic kibana]$ bin/kibana
>   log   [11:34:24.190] [info][status][plugin:kibana@5.1.1] Status changed from uninitialized to green - Ready
>   log   [11:34:24.271] [info][status][plugin:elasticsearch@5.1.1] Status changed from uninitialized to yellow - Waiting for Elasticsearch
>   log   [11:34:24.308] [info][status][plugin:console@5.1.1] Status changed from uninitialized to green - Ready
>   log   [11:34:24.553] [info][status][plugin:timelion@5.1.1] Status changed from uninitialized to green - Ready
>   log   [11:34:24.558] [info][listening] Server running at http://0.0.0.0:5602
>   log   [11:34:24.560] [info][status][ui settings] Status changed from uninitialized to yellow - Elasticsearch plugin is yellow
>   log   [11:34:24.563] [info][status][plugin:elasticsearch@5.1.1] Status changed from yellow to green - Kibana index ready
>   log   [11:34:24.563] [info][status][ui settings] Status changed from yellow to green - Ready
>  error  [11:34:33.263]  Error: Authentication Exception
>     at respond (/opt/kibana-5.1.1-linux-x86_64/node_modules/elasticsearch/src/lib/transport.js:289:15)
>     at checkRespForFailure (/opt/kibana-5.1.1-linux-x86_64/node_modules/elasticsearch/src/lib/transport.js:248:7)
>     at HttpConnector.<anonymous> (/opt/kibana-5.1.1-linux-x86_64/node_modules/elasticsearch/src/lib/connectors/http.js:164:7)
>     at IncomingMessage.wrapper (/opt/kibana-5.1.1-linux-x86_64/node_modules/elasticsearch/node_modules/lodash/lodash.js:4994:19)
>     at emitNone (events.js:91:20)
>     at IncomingMessage.emit (events.js:185:7)
>     at endReadableNT (_stream_readable.js:974:12)
>     at _combinedTickCallback (internal/process/next_tick.js:74:11)
>     at process._tickDomainCallback (internal/process/next_tick.js:122:9)
>

and error in browser:

> {"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"}

**Comment by sscarduzio** [comment]
I noticed this too, basically the traffic pattern between Kibana 5 and ES is substantially different than it used to be in Kibana 4 and ES. This means I have to re-do the work of traffic snooping I had to do with Kibana 4 and allowing one by one the operations Kibana 5 needs to function.

WIP for now, it will be in the official release of 1.13.0

**Comment by extremoburo** [comment]
I'm having the same issue with Kibana 5.1.1 / ES 5.1.1 , and Kibana 4 doesn't like ES 5.x.x so this fix is quite necessary. thanks Simone.

**Comment by luiscarvalho** [comment]
Hi, 
I'm facing the same issue, there is some good news?

Thanks.

**Comment by hawthornpie** [comment]
I am also meetting the same problem.  Do you have ETA? 
Thanks a lot!

**Comment by sscarduzio** [comment]
I already fixed this on my side, but I'm waiting for kibana 5.1.2 to be released with some bug fixes necessary for this feature to work again as expected.

So in a way I'm blocked from releasing a kibana-enabled readonlyrest for 5.x until they resolve on their side.

Some progress is being made and I'm collaborating with them because I can test really quickly.

Ref. https://github.com/elastic/kibana/issues/9583

**Comment by hawthornpie** [comment]
Awesome! It is really a good news!!!
Happy New Year in advance!

**Comment by sreejithps303** [comment]
Hi ,

Is there any expected release date for kibana 5.1.2?

**Comment by sscarduzio** [comment]
I got this working with the newly released 1.13.0 for ES 5.1.1 and the snapshot version of Kibana:

https://github.com/elastic/kibana/tree/5.1#snapshot-builds

**Comment by sreejithps303** [comment]
I have tried with the Snap shot version of kibana . It is working. But authentication is asking two times in kibana . Did you face this issue?

**Comment by danielmotaleite** [comment]
ES and kibana  5.1.2 have been released by the way

**Comment by sscarduzio** [comment]
There's a build of ReadonlyREST for 5.1.2 available at https://readonlyrest.com.
