### ISSUE TITLE
Windows 8/10 error while installation

### ISSUE THREAD

**Issue by akhodachenko** [sscarduzio/elasticsearch-readonlyrest-plugin#14]
ElasticSearch v2.0.0

plugin.bat install file:D:/elasticsearch-readonlyrest-v1.4_es-v2.0.0.zip
-> Installing from file:D:/elasticsearch-readonlyrest-v1.4_es-v2.0.0.zip...
Trying file:D:/elasticsearch-readonlyrest-v1.4_es-v2.0.0.zip ...
Downloading .DONE
Verifying file:D:/elasticsearch-readonlyrest-v1.4_es-v2.0.0.zip checksums if available ...
NOTE: Unable to verify checksum for downloaded plugin (unable to find .sha1 or .md5 file to verify)
ERROR: Could not find plugin descriptor 'plugin-descriptor.properties' in plugin zip

**Comment by sscarduzio** [comment]
Will test this today. Thanks for reporting.

**Comment by sscarduzio** [comment]
I fixed a bug in the build system, tested in docker and it works. 
Try now to re-download the 2.0 compatible zip file, I updated it.

**Comment by akhodachenko** [comment]
It works now, thanks!
Also do you know, will the current readonlyrest-v1.4 sources work with ElasticSearch 2.1.0?

**Comment by sscarduzio** [comment]
Just released the 2.1.0 compatible build :)
