### ISSUE TITLE
Is it possible to apply rule based on url??

### ISSUE THREAD

**Issue by gitime** [sscarduzio/elasticsearch-readonlyrest-plugin#140]
Hi,

I would like to know if it is possible to restrict / grant access to urls like,
```
user 1:
  - can access http://192.168.0.1:5601/app/kibana#/*
  - can access http://192.168.0.1:5601/app/monitoring#/*
  - can access http://192.168.0.1:5601/app/timelion#*
user 2:
  - can access http://192.168.0.1:5601/app/kibana#/*
  - cannot access http://192.168.0.1:5601/app/monitoring#/*
```

Is something like this possible? Else, it would be great if you can provide such a feature.

**Comment by sscarduzio** [comment]
Hey @gitime! 
This would be a nice feature for a Kibana plugin, it's impossible to achieve this for an Elasticsearch plugin.
I've been thinking about making a companion Kibana plugin for readonlyrest, will keep this in mind.
