### ISSUE TITLE
Is there a way to configure session timeout?

### ISSUE THREAD

**Issue by hawthornpie** [sscarduzio/elasticsearch-readonlyrest-plugin#142]
After an account loging successfully, the session is alive permantly. I am not sure whether is OK to configure session timeout. After a configurable period if the logged in account doesn't do anything, it needs to login again. And you can leave current implementation ( never timeout) as default configuration.

Thanks.

**Comment by sscarduzio** [comment]
This is not the first time this is being requested.

It's kinda of a challenge to implement this with HTTP basic auth, but in theory it's possible using a cookie.

I'll give this a try :)

![challenge accepted](http://vignette2.wikia.nocookie.net/animaljam/images/d/d2/Challenge-accepted.png/revision/latest?cb=20140928111255)

**Comment by hawthornpie** [comment]
Got it. Thanks for your replay. 
\(^o^)/~

**Comment by sscarduzio** [comment]
Challenge blocked... https://github.com/elastic/elasticsearch/issues/22367
