### ISSUE TITLE
separation between branch for es 2.x and 5.x

### ISSUE THREAD

**Issue by ld57** [sscarduzio/elasticsearch-readonlyrest-plugin#143]
Hi Simone, 
first, happy new year !

I have in mind that latest fixes you applied to release later than 1.12.1 are all made in your master branch.
the issue is that you also modified files to adapt for es 5.x in master.

I am not familiar with git, but my concerns are how it will allow to build for both version ? ( es 2.4.x and 5.x )
If for example I would like just to add the #128 fix to the current 1.12.1 ( to make a 1.12.11 for example), how must I do ?

Ld

**Comment by ld57** [comment]
well, that I did for now, I downloaded the 1.12.2 for es 2.4.3 , and just  modded descriptor properties files (twice) to adapt, since I own a es 2.4.1

**Comment by sscarduzio** [comment]
I'm working for automating the release process so as I tag a release in the 5.x or 2.x branches it uploads directly to S3 and shows in the website download tool without manual upload/update.

Hopefully this will allow me to release more often, for more versions and with less confusion.

**Comment by ld57** [comment]
okay sounds good !
