### ISSUE TITLE
Builds for 2.4.4

### ISSUE THREAD

**Issue by reftel** [sscarduzio/elasticsearch-readonlyrest-plugin#155]
Hi! ES 2.4.4 is out. Could you please make a build for it?

**Comment by sscarduzio** [comment]
Hi @reftel well spotted! A build is on the way 👍

**Comment by sscarduzio** [comment]
Aaand it's there https://readonlyrest.com

**Comment by reftel** [comment]
Thanks!

**Comment by Ajayn84** [comment]
Hi, I dont see the build available for ES 2.4.4.
Could you please make it available
