### ISSUE TITLE
Know Your Community survey

### ISSUE THREAD

**Issue by sscarduzio** [sscarduzio/elasticsearch-readonlyrest-plugin#158]
[![Know Your Community survey](http://i.imgur.com/qlCilS5.png)](https://sscarduzio.typeform.com/to/ltHL59)

### Hi everyone,

I value a lot your opinion on the present and future of ReadonlyREST: please tell me how you are using the plugin and what you would like to see next by answering these[ few questions](https://sscarduzio.typeform.com/to/ltHL59).

I'm using a GH issue just because I can directly notify some of the most active folks around here like:  @ld57 @Kuckkuck @theundefined @gulycka @danielmotaleite @gitime @nmaisonneuve @shambar

I'll later throw the invitation in the newsletter for the broader public.

**Comment by sscarduzio** [comment]
Hey guys, I followed up on this and opened a forum

http://forum.readonlyrest.com

In this space, we can:
* Login with Github
* Propose and vote [new features](http://forum.readonlyrest.com/c/features)
* Leave [feedback](http://forum.readonlyrest.com/c/feedback) on what could this software do better, or if the user experience  could be simpler
* Discuss [general topics](http://forum.readonlyrest.com/c/uncategorized)

**Comment by ld57** [comment]
Okay good idea  👍
