### ISSUE TITLE
https://readonlyrest.com - Offline ?

### ISSUE THREAD

**Issue by rhysxevans** [sscarduzio/elasticsearch-readonlyrest-plugin#159]
Hi

I am trying to get the latest version (I'm assuming the file name is elasticsearch-readonlyrest-plugin-v1.13.1_es2.4.4.zip) however the readonlyrest.com page is offline. It returns an internal server error.

I usually install via a command along the lines of

"/usr/share/elasticsearch/bin/plugin install https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/blob/master/download/elasticsearch-readonlyrest-plugin-v1.13.1_es2.4.4.zip?raw=true"

Any idea where I can get the file from in the interim?

Thanks

**Comment by sscarduzio** [comment]
Hello @rhysxevans, the service is back. Thanks for reporting.
Github releases is not anymore the preferred way to release builds. If you need to host the binary somewhere for automation, you can upload it somewhere (i.e. Github, S3).

**Comment by rhysxevans** [comment]
Perfect thanks.
