### ISSUE TITLE
Installing

### ISSUE THREAD

**Issue by dco5** [sscarduzio/elasticsearch-readonlyrest-plugin#16]
I have not been able to install the plugin following the pre built zip instructions. I am getting unknown command url. I tried using
  sudo bin/plugin install file:///tmp/elasticsearch-readonlyrest-plugin434172537190131624.zip

but I get:
 -> Installing from file:/tmp/elasticsearch-readonlyrest-plugin434172537190131624.zip...
Trying file:/tmp/elasticsearch-readonlyrest-plugin434172537190131624.zip ...
Downloading ...DONE
Verifying file:/tmp/elasticsearch-readonlyrest-plugin434172537190131624.zip checksums if available ...
NOTE: Unable to verify checksum for downloaded plugin (unable to find .sha1 or .md5 file to verify)
ERROR: Could not find plugin descriptor 'plugin-descriptor.properties' in plugin zip

**Comment by sscarduzio** [comment]
Where did you get that binary named like that? In what version of ES are you trying to install the plugin?

**Comment by dco5** [comment]
I have elastic 2.1.1

**Comment by sscarduzio** [comment]
try with this:
https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/raw/master/download/elasticsearch-readonlyrest-v1.5_es-v2.1.1.zip

**Comment by dco5** [comment]
I tried doing this
sudo bin/plugin install https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/raw/master/download/elasticsearch-readonlyrest-v1.5_es-v2.1.1.zip

and was able to install it! Thanks for your help!

**Comment by sscarduzio** [comment]
Amazing, I didn't even know you can directly put the URL as an argument of the plugin install command!
Glad to help :) !

**Comment by dco5** [comment]
You can even do this:
sudo bin/plugin install sscarduzio/elasticsearch-readonlyrest-plugin

and it will download it from github, but you have to have it in archive/master.zip
