### ISSUE TITLE
Logstash failing on HEAD

### ISSUE THREAD

**Issue by dwjvaughan** [sscarduzio/elasticsearch-readonlyrest-plugin#162]
Apologies if I'm missing something obvious here, but logstash seems to be failing when performing a HEAD with the following:

```
    - name: "Logstash"
      auth_key_sha1: 57319463de6c07d251516a65e04beea4e35a1122
      type: allow
      actions: ["indices:data/read/*","indices:data/write/*","indices:admin/template/*","indices:admin/create","cluster:monitor/*"]
      indices: ["my-index", "<no-index>"]
```
Testing the same call with GET seems to be fine, any ideas what the issue is?

**Comment by dwjvaughan** [comment]
Figured it out by monitoring the log with no restrictions. Needed to add the following to actions:

`"indices:admin/types/exists"`

**Comment by sscarduzio** [comment]
Cool! Will add to docs :)
