### ISSUE TITLE
Allow kibana ro access to create short URLs

### ISSUE THREAD

**Issue by retzkek** [sscarduzio/elasticsearch-readonlyrest-plugin#166]
Is it possible to allow readonly users to create short URLs in kibana without allowing full access to change the kibana index? 

Here's an example request log:

no block has matched, forbidding by default: { ID:f512f1a7a84e47f09d325cf87cfa474b, TYP:IndexRequest, USR:k, BRS:false, ACT:indices:data/write/index, OA:127.0.0.1, IDX:.kibana, MET:POST, PTH:/.kibana/u
rl/4694c9657fb6068f510b7465fbdb67fe, CNT:<OMITTED, LENGTH=273>, HDR:authorization,Connection,content-type,Host,Content-Length, EFF:0, HIS:[Kibana read-only->[kibana_access->false, indices->true]] }

**Comment by sscarduzio** [comment]
This is a massive idea, I really would love to make this possible. I think it would require the readonly rest Kibana companion plugin though. Needs investigation once the Kibana companion plugin exists.

**Comment by sscarduzio** [comment]
@rikatz would you mind to create a topic on the forum about this, so it doesn't get lost in these non-issue issues?

http://forum.readonlyrest.com/

**Comment by rikatz** [comment]
@sscarduzio you mean @retzkek right? :)

**Comment by retzkek** [comment]
@sscarduzio sure, I went ahead and opened a topic.

**Comment by sscarduzio** [comment]
AHAHA @rikatz sorry!

**Comment by rikatz** [comment]
NP :)

**Comment by danielmotaleite** [comment]
I use this to allow only certain operation in kibana:

## {{ user }}
###  Create NEW saved objects (but not overwrite) for {{ user }}
    - name: "Accept {{ user }} create objects"
      type: allow
      methods: [POST]
      auth_key: {{ user }}:{{ pass }}
      uri_re: ^/.kibana/.*\?op_type=create$
      kibana_access: rw

### READ-ONLY access for {{ user }}
    - name: "Accept {{ user }} user"
      type: allow
      methods: [GET,POST,HEAD]
      auth_key: {{ user }}:{{ pass }}
      kibana_access: ro

This allow one to create dashboards and visualizations, without allowing to remove/save existent ones. using the browser developer tools maybe you can do something similar
