### ISSUE TITLE
ES 5.2.0 support

### ISSUE THREAD

**Issue by coutoPL** [sscarduzio/elasticsearch-readonlyrest-plugin#167]
I'm tring to upgrade ES version in your plugin to the newest, but guys from ES did change their API - they removed `RestFilter` and AFAIK now should be used `RestHandler` instead. Did you try to migrate to the new API? I see that `RestFilter` worked as some interceptor of REST request. This is hard to achieve with `RestHandler` (I found `getRestHandlerWrapper` method but I don't know how to implement it to force it work as interceptor only).  Do you have any thoughts about it?

**Comment by sscarduzio** [comment]
I'm about to commit a working version. Yes I'm super pissed about the RestFilter API being removed without deprecation AND in a minor upgrade. 
What I wrote now works, but there will be incompatibilities with xpack, still have to try though if disabling "security" in xpack will make things compatible.

**Comment by sscarduzio** [comment]
you can download now https://readonlyrest.com

**Comment by coutoPL** [comment]
Thanks, but can you push your branch with ES 5.2.0 support. I'd like to try to add LDAP support to your library, but I'd be nice to do it with the newest version of ES.

**Comment by sscarduzio** [comment]
5.2.0 is the master branch now.

Should not matter for what you're trying to do though, the rules' code is completely decoupled from the ES-version dependent code (which I call "wiring").

You can see from the tests, there's just this RequestContext class that exposes basic Java types (nothing ES specific).

**Comment by coutoPL** [comment]
ok, great. Thanks a lot.

**Comment by sscarduzio** [comment]
BTW @coutoPL I'm super excited about LDAP! 

Recommendation: LDAP makes an external network call, and rule's code runs in a Netty worker thread. These threads should NEVER block otherwise all Elasticsearch API would stop eventually.

There's a great library that does this stuff for you called Unboundid, here's a pointer to the doc about LDAP asyncSearch:
https://docs.ldap.com/ldap-sdk/docs/getting-started/asynchronous.html

**Comment by sscarduzio** [comment]
Not sure about caching search results (which would be amazing to have eventually), is it provided or not by the lib? Otherwise there's Guava in ReadonlyREST which has really nice caching.

**Comment by coutoPL** [comment]
Ok, thanks for the hint. It's going to be LDAP support with fits in our requirements, but I think it'll be nice base to improve it. I don't want to promise anything (because out admin has just told me that we are going to use some staff from xpack) - so we should decide what to do with this problem.
