### ISSUE TITLE
Found authenticate failed with act cluster:monitor/main all the time

### ISSUE THREAD

**Issue by tophymastery** [sscarduzio/elasticsearch-readonlyrest-plugin#169]
I tried x-pack with ES 5.2.0 then remove it with 
elasticsearch-plugin remove

and after that I install readonlyrest-plugin

but after restart elasticsearch, the log keep print out error message below

> [2017-02-08T10:40:53,106][INFO ][o.e.p.r.a.ACL            ]  no block has matched, forbidding by default: { ID:f13a33fdd284475690a53880221bfebf, TYP:MainRequest, USR:elastic, BRS:false, ACT:cluster:monitor/main, OA:127.0.0.1, IDX:, MET:HEAD, PTH:/, CNT:<OMITTED, LENGTH=0>, HDR:Authorization,Connection,Host,Content-Length, EFF:0, HIS:[::KIBANA-SRV::->[auth_key_sha1->false]], [::LOGSTASH::->[indices->true, groups->false, actions->true]], [::Product_Team::->[kibana_access->false, indices->true, groups->false, actions->true]], [::Start_service::->[indices->true, groups->false, actions->true]] }

my guess it might be the default user:elastic from x-pack but I'm not sure how to check and remove it.

Note: I also tried to remove entire elasticsearch and reinstall again, this log still happen

Thank in advance

**Comment by sscarduzio** [comment]
Hello @tophymastery, yes looks like something (browser? Kibana daemon?) is sending HTTP requests on behalf of the "elastic" user. 
Kill any browser session, remove credentials from kibana.yml if present, restart kibana. Also, if you want to destroy all the data in ES, just `rm -rf data/*`.

**Comment by tophymastery** [comment]
thank @sscarduzio , now I can't reach that server coz it's internal network. Tomorrow I will try as your suggestion and will update the result here.
Thank again.

**Comment by tophymastery** [comment]
i try to close kibana browser and didn't see any log again
thank @sscarduzio
