### ISSUE TITLE
ro+ and kibana rule

### ISSUE THREAD

**Issue by danielmotaleite** [sscarduzio/elasticsearch-readonlyrest-plugin#172]
Hi

with the removal of the  `kibaba: ro+`, i assume that it should be replaced with `kibana: rw`, correct?
but the `ro+` allowed writes to kibana, but not to the ES indices, `rw` allow the first, how about the `readonly` of the all ES indices? we must use the `actions` to only allow reads? If so, we should replace the `ro+` with 2 new rules, one for `kibana: rw` and another (first) with a list of `actions` and type `forbid`

If so, please add that to the documentation. notice that the github documentation still uses `ro+` in many places

**Comment by sscarduzio** [comment]
Hello Daniel!
> with the removal of the kibaba: ro+, i assume that it should be replaced with kibana: rw, correct?

Yes, the meaning of kibana_access preset should only qualify the access level to Kibana operations. That is: read/read+write `.kibana` and read other indices. That replaces the old ro+ with rw and removes the too powerful old rw.
Sorry I could not understand what you mean with the second part of the question.

I updated the README.md: removed references to ro+ and to <no-index> which is not necessary anymore.

**Comment by danielmotaleite** [comment]
Ok, understood, the old _rw_ was the one that was really removed, the ro+ is the current _rw_  and isonly allows writes to the _.kibana_, everything else is _ro_. Perfect! thanks!

The second parts was related with new _rw_ and write to other indices, that i now know that  is not possible, so the question do not really make sense 😄 

I think you can clearly say in the docs that kibana: rw allows writes to .kibana only and it is readonly to the other indices. this makes clear to other people how it works. you want to use this to track the documentation update, if not, we can close this.

Thanks for the help (and the plugin!)

**Comment by sscarduzio** [comment]
I updated the docs https://readonlyrest.com/documentation#toc-2-3-elasticsearch-level

**Comment by danielmotaleite** [comment]
Looks good, thanks!
