### ISSUE TITLE
problem with auth or kibana option changed

### ISSUE THREAD

**Issue by danielmotaleite** [sscarduzio/elasticsearch-readonlyrest-plugin#173]
I have this config:

```
    - name: "Accept audit user"
      type: allow
      auth_key: audit:{{ pass }}
      kibana_access: ro
      methods: [GET,PUT,POST,HEAD]
      actions: ["indices:data/read/*","indices:data/write/*","indices:admin/get","indices:admin/create","indices:admin/exists"]
      indices: [audit-*]

```
In the past, i could create indices with user audit, but since 5.2.0 (i think) it start to fail and log this:

```
[2017-02-13T17:45:49,977][INFO ][o.e.p.r.a.ACL            ]  no block has matched, forbidding by default: {
 ID:58b710e8d3b343ffbb7816a089ccd3ef, TYP:CreateIndexRequest, USR:audit, BRS:true, ACT:indices:admin/create, OA:172.16.0.240, IDX:audit-staging, MET:PUT,
 PTH:/audit-staging, CNT:<OMITTED, LENGTH=135>, HDR:Authorization,Accept,User-Agent,Host,Content-Length,Content-Type, EFF:0, HIS:
 [Accept audit user->[kibana_access->false, indices->true, methods->true, auth_key->true, actions->true]],
```
it looks that is failing in the kibana, but i'm not changing kibana indices. is this a bug or kibana option changed the way of working?

**Comment by sscarduzio** [comment]
it's working correctly because creating an index named `audit-*` is NOT a kibana read only action. Remember all the rules inside a block are in logical AND.
So that rule means that we want to allow requests that are valid kibana read only AND match index pattern `audit-*` AND ... etc.

If you want to achieve a logical OR, just create a second block having the same auth_key, and allowing those actions and indices. That will work because blocks are evaluated in logical OR.

**Comment by danielmotaleite** [comment]
ok, i understand and it very logical... the strange part is that the same (bad) config worked in older versions! 😃 
Maybe in the past, the kibana only applied to the .kibana and that option was ignored in the other indices. Now it blocks writing to the other indices too. Anyway, the current code is more logical, specially when looking to the logs, so this is the correct behavior.

Again, thanks for the help!

**Comment by sscarduzio** [comment]
Yes it might have changed, but I think the current one the desired behaviour of kibana_access rule. 
First check the action is something we expect in a browser-kibana traffic pattern, then check if such action is expected towards the index.
