### ISSUE TITLE
Logging in ES 5.1.2

### ISSUE THREAD

**Issue by dwjvaughan** [sscarduzio/elasticsearch-readonlyrest-plugin#174]
I seem to be struggling to configure my log4j2.properties file to log to a separate file. I've tried this: https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/wiki/Supported-Rules#dedicated-and-logging-file-rotation but it still keeps hammering my /var/log/elasticsearch/cluster_name.log file with each and every access request.

I want to initially log all requests, but in the future only log failures, but all in a separate file so I can keep the ES core stuff separate.

I've very little experience in log4j so would appreciate any help on this?

Cheers,
Dave

**Comment by sscarduzio** [comment]
@dwjvaughan you have seen this, right?
https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/issues/146#issuecomment-279456372

**Comment by dwjvaughan** [comment]
Ah, sorry - I missed that. All working now, thank you!
