### ISSUE TITLE
typo?

### ISSUE THREAD

**Issue by danielmotaleite** [sscarduzio/elasticsearch-readonlyrest-plugin#175]
In the actions list we have:

```
indices:admin/mapping/put
indices:admin/mappings/fields/get
indices:admin/mappings/get
```

notice the missing S in the mapping/put ... or extra S on the others! :)

Is this one error from the docs or the plugin, or this list is from elasticsearch/kibana?

**Comment by sscarduzio** [comment]
Yeah I agree, that's weird, but all that list is generated by a bash script that scans all the .java files
That action in particular comes from here:

https://github.com/elastic/elasticsearch/blob/44ac5d057a8ceb6940c26275d9963bccb9f5065a/core/src/main/java/org/elasticsearch/action/admin/indices/mapping/put/PutMappingAction.java#L28

**Comment by danielmotaleite** [comment]
yep, i suspected that.

i just open a ES bug report: https://github.com/elastic/elasticsearch/issues/23220 , lets see what they say 😃

**Comment by sscarduzio** [comment]
They said it's intentional. Will close this one!

**Comment by danielmotaleite** [comment]
yep, i agree... may i suggest in your list, to put a space between the mapping and the mappings, so people can better see that they are differently named. It is annoying to restart a cluster just to find that we have a typo in the action filter ;)

**Comment by sscarduzio** [comment]
done!
