### ISSUE TITLE
Ordering of rules if there are more than 10

### ISSUE THREAD

**Issue by psaiz** [sscarduzio/elasticsearch-readonlyrest-plugin#177]
Hi again, 

I'm running 1.13.2, for es 5.2.0.  If there are more than 10 rules, the order in which they are applied is by string comparison (instead of numeric). I mean, imagine that in the configuration file we have defined the rules in order 0,1,2,3,4,5,6,7,8,9,10,11, the order in which they will be checked is 0,1,10,11,2,3,4,5,6,7,8,9.

Cheers, 
pablo

**Comment by sscarduzio** [comment]
Hey Pablo, nice one, I'm fixing this right now.
