### ISSUE TITLE
Issue on readonlyrest.com

### ISSUE THREAD

**Issue by haizaar** [sscarduzio/elasticsearch-readonlyrest-plugin#179]
Hi guys,

There seems to be issue with readonlyrest.com website - the version dropdown list does not seem to function:

![image](https://cloud.githubusercontent.com/assets/58201/23124819/8beba7ca-f777-11e6-900e-c9397869b9fa.png)

Chrome version 55.0.2883.87 running on Ubuntu 16.04 (64-bit)

**Comment by sscarduzio** [comment]
Fixed now. Thanks for reporting @haizaar

**Comment by haizaar** [comment]
Still fails for me. Tried with hard refresh.

**Comment by sscarduzio** [comment]
Same error?

**Comment by haizaar** [comment]
Yeap.

![image](https://cloud.githubusercontent.com/assets/58201/23131273/10edf904-f792-11e6-8e2b-f2f87955161b.png)

**Comment by sscarduzio** [comment]
OK it's not the same, I solved 1 of 2 😄!
About the other: turns out the ad blocker is messing my crash reporter tool. I tried to rename the file and host it internally in my site.
Try now please! :)

**Comment by haizaar** [comment]
Works golden. Thanks!
