### ISSUE TITLE
Logging.yml and Logs

### ISSUE THREAD

**Issue by Shifter2600** [sscarduzio/elasticsearch-readonlyrest-plugin#185]
I have added the proper logging config to the yml
logger:
  plugin.readonlyrest.acl.blocks.rules.impl: INFO, access_log_file
  plugin.readonlyrest.acl: INFO, access_log_file

additivity:
  plugin.readonlyrest.acl.blocks.rules.impl: false
  plugin.readonlyrest.acl: false

appender:
  access_log_file:
    type: dailyRollingFile
    file: ${path.logs}/${cluster.name}_access.log
    datePattern: "'.'yyyy-MM-dd"
    layout:
      type: pattern
      conversionPattern: "[%d{ISO8601}][%-5p][%-25c] %m%n"

My _access.log is getting SPAMMED and grows and grows as items are POST to ES and as GET ClusterHealthRequest.
Is there anyway to only have Errors with access sent to log?

**Comment by sscarduzio** [comment]
there was a snippet from @danielmotaleite 
```
logger.access_log_rolling.filter.regex.type = RegexFilter
logger.access_log_rolling.filter.regex.regex = .*USR:(kibana|beat|logstash),.*
logger.access_log_rolling.filter.regex.onMatch = DENY
logger.access_log_rolling.filter.regex.onMisMatch = ACCEPT
```
See http://forum.readonlyrest.com/t/feature-control-what-users-to-log-not-log/27/2

**Comment by ld57** [comment]
Yep we need to update the Wiki soon.

**Comment by sscarduzio** [comment]
it's done :)

**Comment by Shifter2600** [comment]
@sscarduzio  I don't see any where in the logging.yml that I can put this. Is this compatible with 2.4.x ES? or only 5.x

**Comment by sscarduzio** [comment]
The above is for 5.x

**Comment by Shifter2600** [comment]
@sscarduzio ya looks like I need to figure out the log4j syntax. 
Tried playing around with is with no success tonight. Will try again tomorrow. 
Found this but can't get it to work.
http://stackoverflow.com/questions/28102686/add-a-filter-to-appender-in-elasticsearch-logging-yml-syntax

**Comment by sscarduzio** [comment]
The only docs we have about 2.x logging tweaking is in the wiki
https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/wiki/Supported-Rules#dedicated-and-logging-file-rotation
