### ISSUE TITLE
how to combine the rules

### ISSUE THREAD

**Issue by sliontc** [sscarduzio/elasticsearch-readonlyrest-plugin#19]
Hi, I want to combine the rules to feed my following need:

only the request from local ip and with x-api-key set in header can be allowed.

Thanks.

**Comment by sscarduzio** [comment]
Not sure this is what you were looking for, but this is equivalent to ```if (origin==127.0.0.1 && header(x-api-key) == a1b2c3d4e5f6) OK else REJECT```
```
    - name: only localhost can pass, and has to carry an api key
      type: allow
      hosts: [127.0.0.1]
      api_keys: [a1b2c3d4e5f6]

```

**Comment by sliontc** [comment]
That's cool. Thanks.

**Comment by sliontc** [comment]
By the way, can I add port to the hosts?

**Comment by sscarduzio** [comment]
The port? What would be the expected behaviour? Can you .are an example?

**Comment by sliontc** [comment]
For example, only the connection from the remote host with port 1234 could be allowed access the ES.
So could I set the hosts like: hosts: [192.168.2.1:1234]?

**Comment by sscarduzio** [comment]
well, 99.9% of the times, the source port in a TCP connection is allocated randomly by the client's operating system. To be honest, I don't think this feature would add enough value to justify its presence in this product.
Unless there's some major use case (some specific cloud component?) that depends on this. But I've never heard of such.
