### ISSUE TITLE
readonly ldap setup

### ISSUE THREAD

**Issue by hello4usharath** [sscarduzio/elasticsearch-readonlyrest-plugin#192]
Hi,

Can you help how to configure ldap on elasticsearch.

Thanks
Sharath

**Comment by sscarduzio** [comment]
Hi @hello4usharath,

GitHub issues is for bugs. If there's not a bug and you want help with configuration, you can try asking in the [community forum](http://forum.readonlyrest.com) for free, or you can [hire me](https://sscarduzio.typeform.com/to/XGGPBT) to solve a specific problem.

Have a nice day!

**Comment by sscarduzio** [comment]
@hello4usharath any luck?
