### ISSUE TITLE
Problem with using Readonly rest with elasticsearch-head

### ISSUE THREAD

**Issue by nan008** [sscarduzio/elasticsearch-readonlyrest-plugin#194]
I have problem connecting to ES 5.2 with elasticsearch-readonlyrest-plugin 1.14.0, my elasticsearch-head is webserver/filesystem.

https://github.com/mobz/elasticsearch-head

As ES is asking for a  a cert with the request. I need to do something similar to Logstash but elasticsearch-head do not have this facility

ssl => true
cacert => ["/etc/logstash/Logstash_cert.pem"]

Even when I will go with the basic authorization but my ES is responding with log entry for elasticsearch-head.

[2017-03-15T12:34:01,231][ERROR][o.e.p.r.SSLTransportNetty4] [4DfeseL] exception in SSL transport: javax.net.ssl.SSLException: Received fatal alert: unknown_ca

Is there any way I can switch off the request for cert from this particular IP in elasticsearch.yml?

**Comment by sscarduzio** [comment]
Looks more like Head needs the equivalent of either of these two Kibana settings:

```yaml
elasticsearch.ssl.certificateAuthorities: [ "/path/to/your/CA.pem" ]
elasticsearch.ssl.verificationMode: none
```
or you need to fix your SSL cert, like: make sure your cert is not self-signed and chain is included in the JKS.

Keep in mind that if your cert is self signed and want to keep it like this, Head needs to implement the equivalent of "verificationMode" above.

**Comment by nan008** [comment]
Thanks for the answer , I opened the issue on their github as well and waiting for an answer as we do have self signed certs which are working perfectly with the rest of the environment. Just needed toverify if there is a config under the policy in readonly I can disable it for this particular block.
