### ISSUE TITLE
indices_rewrite misbehaves: final set is empty 

### ISSUE THREAD

**Issue by diegonc** [sscarduzio/elasticsearch-readonlyrest-plugin#195]
The method `RequestContext::getExpandedIndices` is always returning an empty set when I try to use an `indices_rewrite` rule making the `IndicesRewriteSyncRule::match` set the request context with an empty indices set .

**What I am trying to do**

My ElasticSearch cluster has one index per client named following the pattern `client-index-<clientId>` and I'm using the following rule in `elasticsearch.yml`:

```
  access_control_rules:
    - name: "Restrict access to user's index only"
      type: allow
      proxy_auth: "*"
      indices_rewrite: ["^(client-index)$", "$1-@user"]
      indices: ["client-index-*"]
```

The client then performs a search request to the virtual index `client-index` and ReadonlyREST should translate that index into the real `client-index-<clientId>` using a rewrite rule.

**What I expect to happen**

ReadonlyREST rewrites the index and the client gets its documents back from the ES API call.

**What actually happens**

ReadonlyREST tries to replace the indices set with an empty one; printing the following messages to ES logs:

```
[2017-03-22T18:42:00,378][INFO ][o.e.p.r.a.RequestSideEffects] Committing 2 effects
[2017-03-22T18:42:00,379][INFO ][o.e.p.r.a.RequestContext ] id: 648a7d67e754472ab3ebaa01ee1718d5 - Replacing indices. Old:[client-index] New:[]
[2017-03-22T18:42:00,379][INFO ][o.e.p.r.IndexLevelActionFilter] [sw-node-1] forbidden request: { ID:648a7d67e754472ab3ebaa01ee1718d5, TYP:SearchRequest, USR:1171, BRS:true, ACT:indices:data/read/search, OA:192.168.123.214, IDX:client-index, MET:GET, PTH:/client-index/dbf/_search, CNT:<OMITTED, LENGTH=0>, HDR:content-length,Accept,Connection,User-Agent,Host,Accept-Encoding,Authorization,Cache-Control,X-Forwarded-For,Postman-Token,Accept-Language,X-Forwarded-User, EFF:2, HIS:[Restrict access to user's index only->[indices->true, indices_rewrite->true, proxy_auth->true]], [Restrict access to user's index only->[]], [Local access is not restricted->[x_forwarded_for->false]] } Reason: ElasticsearchException[Attempted to set empty indices list, this would allow full access, therefore this is forbidden. If this was intended, set '*' as indices.]
```

**Analysis**

I've setup a reverse proxy that handles the authentication issue and verified that inside [`IndicesRewriteSyncRule::match`](https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/blob/master/src/main/java/org/elasticsearch/plugin/readonlyrest/acl/blocks/rules/impl/IndicesRewriteSyncRule.java#L74) the `@user` placeholder is correctly replaced.

Stepping into the code I've found that, in the match method mentioned above, the variable `oldIndices` is an empty set.
It's populated from the results of [`RequestContext::getExpandedIndices`](https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/blob/master/src/main/java/org/elasticsearch/plugin/readonlyrest/acl/RequestContext.java#L178), transcribed below.

```java
public Set<String> getExpandedIndices() {
  return new MatcherWithWildcards(getIndices()).filter(getAvailableIndicesAndAliases());
}
```

While debugging, the values I've observed are:

- `getIndices()` -> `["client-index"]`
As I understand it, these are the indices used in the request (a.k.a *virtual indices*)
- `getAvailableIndicesAndAliases()` -> `["client-index-1171"]`
And these ones come from the ES metadata which list all the existing indices in the cluster (a.k.a *real indices*)

The filter method then checks whether any *virtual index* contains (as in `String::contains`) each of the *real indices* and returns a set of those that pass the check.

So, in the example above, what gets done in the end is `"client-index".contains("client-index-1171")` which is false and then no index is returned from `getExpandedIndices`.

**Conclusion**

There's a couple of things here that feel wrong.

- Why are the indices in the request handled as if they were patterns by `IndicesRewriteSyncRule::match`? Unless I'm missing some ES feature, that doesn't make sense to me. For instance, if the client does a `GET /client-index*` then `getExpandedIndices` will start returning all existing indices matching that pattern.
- Why are the real indices involved at all? I think the rewrite rule should not care whether the final index actually exists. It should know about only the indices in the request, the pattern and the replacement.

Hope this makes sense 😃
Thanks

**Comment by sscarduzio** [comment]
Hello @diegonc!
Thanks for taking the time of explaining your question throughly. It was a total pain to go through what should be done with indices mangling all together.

That's why I left a [trail of comments](https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/blob/master/src/main/java/org/elasticsearch/plugin/readonlyrest/acl/blocks/rules/impl/IndicesSyncRule.java#L75) from when I was implementing IndicesSyncRule.

I hope following that trail and/or debugging line by line the [unit test](https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/blob/master/src/test/java/org/elasticsearch/plugin/readonlyrest/rules/IndicesRuleTests.java#L63) will expand on why I did that.

Now, to answer your question, the available indices are involved because of a feature known "reverse wildcard" matching, described [here](https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/issues/110#issuecomment-254164749)

BTW, I discovered this morning that the indices_rewrite fails because of a read-after-write of the request indices. I committed a version today where I [commented these few lines](https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/blob/master/src/main/java/org/elasticsearch/plugin/readonlyrest/acl/RequestContext.java#L181).

**Comment by diegonc** [comment]
> Now, to answer your question, the available indices are involved because of a feature known "reverse wildcard" matching, described here

Hmm, I'll have to read about Kibana to understand that; play a bit with it and see what kind of requests it calls 😄

>BTW, I discovered this morning that the indices_rewrite fails because of a read-after-write of the request indices. I committed a version today where I commented these few lines.

Oh, I'll need to update then, hehe. Thanks.

For the time being, I'm going to (ab)use the "client queries an index with a star" workaround. And if anything else comes out of the blue, leave a report here. Just noticed rewriting is a rather new feature.

**Comment by sscarduzio** [comment]
@diegonc inspired by this discussion, I just 💡 and committed an actual fix for the read-after-write problem.
