### ISSUE TITLE
Group member search attribute is hard coded

### ISSUE THREAD

**Issue by circuitousNerd** [sscarduzio/elasticsearch-readonlyrest-plugin#196]
The member attribute that is searched is hardcoded to uniqueMember. This is really unwieldy if it doesn't exactly match the existing ldap schema. Is it possible to get this adapted to be customisable?

**Comment by combatdud3** [comment]
`        try {
            CompletableFuture<List<SearchResultEntry>> searchGroups = new CompletableFuture<>();
            connectionPool.processRequestsAsync(Lists.newArrayList(
                    new SearchRequest(
                            new UnboundidSearchResultListener(searchGroups),
                            searchGroupBaseDN,
                            SearchScope.SUB,
                            String.format("(&(cn=*)(uniqueMember=%s))", user.getDN())
                    )),
                    timeout
            );`

The relevant code is here. I'm not great with java, so I was able to edit and recompile to suit my purposes. But I have no idea how to make it customisable.

**Comment by coutoPL** [comment]
In new version there is possibility to override `uid` and `uniqueMemeber` attributes.
https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/pull/197

**Comment by sscarduzio** [comment]
Thanks @coutoPL! I can merge this today in 1.14.1 so I release also for ES 5.3.0, or do you need more time to add anything else?

**Comment by coutoPL** [comment]
I'm preparing new feature, but it will be ready next week. So go ahead with releasing.

**Comment by sscarduzio** [comment]
wait, now I have to know what's boiling in that pot of yours, you can't leave me like this 😂

**Comment by coutoPL** [comment]
hahaha :D let's call it `suprise` :)

**Comment by sscarduzio** [comment]
Oh.. man!!! OK I'll wait 🍿👹

**Comment by combatdud3** [comment]
Thanks guys, I'm guessing this was already a work in progress, but either way that's an amazing response time!

I'm happy to close this issue if you guys are?
