### ISSUE TITLE
Is it possible to add logout feature

### ISSUE THREAD

**Issue by tophymastery** [sscarduzio/elasticsearch-readonlyrest-plugin#199]
Seem kibana lack of login and logout form.
After I open kibana and pass authenticate I can stay at kibana without session timeout.
So is it possible to add 
1. kibana login form
2. session timeout
3. kibana logout button

to management logged in session.

Or any work around for interim solution with nginx ?

**Comment by sscarduzio** [comment]
There should definitely be a native login form (Basic HTTP Auth) if you configured the plugin correctly. What's your conf and what do you want to do?

BTW session time out is supported, Kibana logout button is offered in a companion Kibana plugin which is paid for (will probably launch next week).

**Comment by sscarduzio** [comment]
Oh you mean you expected an HTML form line in X-Pack? Good idea, can be done in the next iteration of the Kibana plugin 👍

**Comment by sscarduzio** [comment]
Hey @tophymastery, I think you're going to like this 🎉 
https://readonlyrest.com/pro.html
