### ISSUE TITLE
Can't connect

### ISSUE THREAD

**Issue by florakarniav** [sscarduzio/elasticsearch-readonlyrest-plugin#20]
Hello,

I have elasticseach deployed on a VM and used this plugin to secure it. I added the default lines you give to the elasticsearch.yml file and now I can't connect to my elasticsearch service, even from inside the VM. 
curl http://127.0.0.1:9200
curl: (7) couldn't connect to host

Am I doing something wrong? Also, how can I allow my local machine IP  to connect to the elasticsearch instance on the VM?

thank you in advance

**Comment by sscarduzio** [comment]
Hello @florakarniav!
If you ran ES in a virtual machine in your laptop, then ES is listening on the VM's IP address, not on the localhost. 
Check what's the IP of your machine and point your curl commands to it.

**Comment by sscarduzio** [comment]
Have you resolved your issue? :)

**Comment by florakarniav** [comment]
Hi, it seems that the plugin wasn't matching my ElasticSearch version (I had 1.5 and the plugin was for 1.5.2) so even though it seemed like ElasticSearch was running it actually wasn't. Thank you for your immediate response and attention anyway! :)

**Comment by sscarduzio** [comment]
Glad to help! Nice to hear everything is fine.
