### ISSUE TITLE
release request 1.14.1 for es 2.4.1 and 2.4.4

### ISSUE THREAD

**Issue by ld57** [sscarduzio/elasticsearch-readonlyrest-plugin#201]
Hi Simone,

Could you release 1.14.1 for es 2.4.1 and 2.4.4 ?

I could not give a try to 1.14.0 yet :(, nor could not upgrade my es yet from es 2.4.1 to 2.4.4. ( being a bit superbusy)

**Comment by sscarduzio** [comment]
hey @ld57! Still have to backport 1.14.1 to 2.x. But I think it's worth to wait until 1.14.2 because there's a couple of PRs right now that I definitely want to include. 

BTW backporting stuff beyond 5.1 is becoming very time consuming, I warmly suggest to upgrade to the latest 5.x!

**Comment by ld57** [comment]
Hey @sscarduzio , 

well could not touch my plateform since 30+ days, and could not even prepare for a migration yet.
I had in plan to move up to 2.4.4, and no more until they allow me to go further in my demo :/

also If I am not too much impacted with 1.14.0 , I can implement it during next days and then you do not need to backport 1.14.2 .

as soon as I get freed a bit , I ll be more active.

**Comment by ld57** [comment]
got 1.15 , thanks @sscarduzio :)
