### ISSUE TITLE
does this plugin work with TCP port (9300)?

### ISSUE THREAD

**Issue by thientruongbka** [sscarduzio/elasticsearch-readonlyrest-plugin#204]

**Comment by sscarduzio** [comment]
No, not yet. As of now, we focus on managing encryption, authentication, authorization and audit of the REST interface (default port 9200).

But as a matter of fact, at the highest level this plugin operates (actions, indices) we could support the transport interface reusing the vast majority of the current code.

**Comment by thientruongbka** [comment]
oh, thank u!

**Comment by sscarduzio** [comment]
@thientruongbka would you mind to propose this feature in http://forum.readonlyrest.com ?
I think it's a good proposal and needs to be kept track of.

**Comment by thientruongbka** [comment]
Okay,
I think it's big problem if we lack of TCP authentication feature, I developed a client app with TransportClient and i can CRUD database without authentication user/pass, even though I use readonlyrest plugin.

**Comment by ld57** [comment]
Hi, 
On my side I secured inter node transport by using ssl wrapper, and authenticate using server AND client certificate.

In my opinion we should go in this, securing using client certificate and server certificate.

We had a discussion about this and for now effort are focused on front end side.

**Comment by sscarduzio** [comment]
I've been thinking about this, it would completely shift the focus of the project. Also I don't know how your program will handle connecting through proxies, going through firewalls and/or various NAT traversal systems.

@thientruongbka why did you choose transport for your app instead of HTTP? Was it really worth the few percent less chattiness?

**Comment by Remusss** [comment]
> No, not yet. As of now, we focus on managing encryption, authentication, authorization and audit of the REST interface (default port 9200).
> 
> But as a matter of fact, at the highest level this plugin operates (actions, indices) we could support the transport interface reusing the vast majority of the current code.

Is there a place where I can track the status of auth/authz etc over transport layer?

**Comment by sscarduzio** [comment]
IndexLevelActionFilter class, when the HTTP request is not there, I guess you have received a transport level request.

**Comment by Remusss** [comment]
I didn't mean to confuse you.
I was asking about the status of the implementation of readonlyrest for the transport layer.

**Comment by sscarduzio** [comment]
@Remusss sorry for the misunderstanding there is no intention to do so as I could not identify any sensible reason why. I merely acknowledged it's technically possible.
