### ISSUE TITLE
logstash-* return no results when one index is blocked

### ISSUE THREAD

**Issue by danielmotaleite** [sscarduzio/elasticsearch-readonlyrest-plugin#206]
Hi

So i have this configs:

```
    - name: "Accept admin user"
      type: allow
      auth_key:something

    - name: "Deny password indexes"
      type: forbid
      indices: [logstash-*-passwords,logstash-*-deadlocks-*]

```
The idea is that the logs that still contain passwords (being fixed) are restricted to the admins, but this is breaking the regular users searches. They usually use logstash-* to start searching and then restrict the indices after founding in what index their data is.

I suspect that the search is reaching the logstash-*-deadlocks-* and returning a error and breaking the remaining search from working.

Is there any workaround? if not, can you please add a option to "hide" instead of blocking the index?

Thanks

**Comment by sscarduzio** [comment]
how about you add another allow rule above the forbid one and allow deadlocks?

**Comment by danielmotaleite** [comment]
😃  
deadlocks index, as it dumps the SQL query, may also have passwords... so the objective is to block indexes that may have passwords

how about a option that instead of returning errors, return success, but empty data, as if the query didn't found anything... something enabled by rule would be perfect

example:
```
    - name: "Deny password indexes"
      type: ignore  (or remove or empty)
      indices: [logstash-*-passwords,logstash-*-deadlocks-*]

```

**Comment by sscarduzio** [comment]
A `type` value for just this would mean nothing for other queries that don't involve indices. Sounds like more a behaviour to attach to a modifier of the indices rule, right?

**Comment by danielmotaleite** [comment]
that would also work... or make "type: ignore" special and require always a index
As i do not know the code, not even java, i have no ideia what is easier to implement and manage :)
