### ISSUE TITLE
How to install this plugin for ES5.2.2

### ISSUE THREAD

**Issue by vg15** [sscarduzio/elasticsearch-readonlyrest-plugin#208]
Hi ,

I am aware in new ES version Site plugins has been removed and I  tried both the methods direct install and from file for both I am getting below error .Please help me to download it.
`ERROR: `elasticsearch` directory is missing in the plugin zip`

Regards
VG

**Comment by sscarduzio** [comment]
https://readonlyrest.com follow download link

**Comment by vg15** [comment]
Thanks,

One quick question , is it somehow possible to restrict user to their visualization or to their dashboard with this plugin ?

**Comment by sscarduzio** [comment]
Next release will allow this by dynamically rewriting requests to `.kibana` indices to their own `.kibana_$user`  index using the `indices_rewrite` rule. 

That rule is already present in the current version, but some bugs prevent it working well. Soon I will release a heavily refactored version that makes it work as intended.

So stay tuned and watch your email for new releases announcements. Alternatively just log in the forum http://forum.readonlyrest.com and you'll receive the announcement from there too.

**Comment by vishutux** [comment]
I also facing same problem "ERROR: `elasticsearch` directory is missing in the plugin zip", I am following steps mentioned in download link of https://readonlyrest.com, my Elasticsearch version is elasticsearch-5.3

Appreciate any help here.

**Comment by vg15** [comment]
Do not download directly from github.Use above link it will take you
separate page mention you personal I'd there you will get a download link.I
download this way and things worked.

**Comment by sscarduzio** [comment]
As @vg15 said, if you are not a developer, don't download anything from GitHub.

Get the zip from the official website: https://readonlyrest.com

**Comment by vishutux** [comment]
I downloaded from[]( https://readonlyrest.com/#downloadForm) only

**Comment by sscarduzio** [comment]
latest plugin version for this 5.2.2 is published
