### ISSUE TITLE
problem with ES 1.5.2

### ISSUE THREAD

**Issue by jeeremy** [sscarduzio/elasticsearch-readonlyrest-plugin#21]
Hello, I have elasticsearch 1.5.2 and I was trying to install elasticsearch-readonlyrest-v1.3_es-v1.5.2
During start elasticsearch service I receive:
[2016-01-28 15:51:07,102][ERROR][bootstrap                ] Exception
org.elasticsearch.common.inject.CreationException: Guice creation errors:

1) Error injecting constructor, java.lang.NoSuchMethodError: org.elasticsearch.rest.BaseRestHandler.<init>(Lorg/elasticsearch/common/settings/Settings;Lorg/elasticsearch/client/Client;)V
  at org.elasticsearch.rest.action.readonlyrest.ReadonlyRestAction.<init>(Unknown Source)
  while locating org.elasticsearch.rest.action.readonlyrest.ReadonlyRestAction

1 error
        at org.elasticsearch.common.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:344)
        at org.elasticsearch.common.inject.InjectorBuilder.injectDynamically(InjectorBuilder.java:178)
        at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:110)

I've tried with java 1.7.76, 1.8.05, 1.8.45 and 1.8.72 - still the same error

Due to the lack of positive results I decided to try version for ES 1.6 - elasticsearch-readonlyrest-v1.4_es-v1.6.0
For a short moment I though that it finally works but in few minutes I relized that it works only for IP but not for subnets. Config is correct because I've tried exactly the same configuration with my test machine with ES 2.1 (java 1.8.51)  and on it everything works fine! But I can't upgrade ES on production environment, it must be 1.5.2

In attachments you can see my config in elasticsearch.yml and part of ES log where I can see that ACL config is correctly interpreted. With this config on host 172.18.0.1 I receive 'Sorry, your request is forbidden' but when I change in config [172.18.0.0/24] to [172.18.0.1] then access is possible. As I mentioned - It doesn't work when I try to make configuration for subnets.

How can I force readonlyrest v1.4_es_1.6.0 to work with subnets configuration?
Or maybe there is a way to run elasticsearch-readonlyrest-v1.3_es-v1.5.2 ?

Attachments:
elasticsearch.yml works for ES 2.1 + elasticsearch-readonlyrest-v1.5_es-v2.1.1.zip and works without subnets support for ES 1.5.2 + elasticsearch-readonlyrest-v1.4_es-v1.6.0

elasticsearch.log  - it is a start sequence for ES 1.5.2 with readonlyrest v1.4_es_1.6.0

[elasticsearch.log.txt](https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/files/111883/elasticsearch.log.txt)
[elasticsearch.yml.txt](https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/files/111884/elasticsearch.yml.txt)

**Comment by sscarduzio** [comment]
yeah the main problem is that at the times of ES 1.5, this plugin did not yet receive the contribution behind the subnet feature. The subnets feature IIRC has been introduced after branching off of 1.x.

Ideally you'd just upgrade your ES version to 2.x and live happy ever after. Would you consider that?

**Comment by jeeremy** [comment]
As I see, we must seriously to consider it. Thanks for your reply.

**Comment by sscarduzio** [comment]
@jeeremy I'm curious how this went for you, did you decide to migrate or you would still benefit of a 1.x build?

**Comment by jeeremy** [comment]
Hey! Upgrade is not possible now. We decided to go this way: http://stackoverflow.com/questions/14115475/easy-way-to-make-an-elasticsearch-server-read-only

**Comment by sscarduzio** [comment]
You mean you went for the one-more-moving-part Nginx option? Yeah, I kinda tend to agree that is quite the most sensible alternative.
Anyway, I had a massive refactoring last weekend for 1.7 and it's much easier to port features back and forth between branches (each rule implementation is self contained into a class). If nothing more urgent comes in the way, I'm going to attempt to branch it out to support 1.x (you are one of many users have requested 1.x ports).

**Comment by jeeremy** [comment]
It would be great. I will return to your project as soon as possible.

**Comment by teebu** [comment]
sscarduzio, the reason why a lot of people are still using 1.x is because amazon offers 1.x. And I would like to test your plugin with our 1.7.

**Comment by sscarduzio** [comment]
@teebu wait, you can install plugins in AWS elasticsearch?

**Comment by teebu** [comment]
i dont know. we just use a ec2 machine. i assumed you could.

**Comment by sscarduzio** [comment]
https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/blob/PORT_ES_1.x/download/elasticsearch-readonlyrest-v1.7_es-v1.5.2.zip
