### ISSUE TITLE
Download links?

### ISSUE THREAD

**Issue by kunwon1** [sscarduzio/elasticsearch-readonlyrest-plugin#212]
It seems I have to provide an email address to download the software now. This is a major step backwards, when access to your open source software is gated by a human that has to approve or disapprove requests, it becomes much harder to justify using this in production

What happens if a year or two down the line there are even more hurdles to jump over before we download software

very disappointing

**Comment by sscarduzio** [comment]
@kunwon1 thanks for taking the time to type down your frustration points, always useful to have a feedback!
First a few notes, as the above statement is not 100% correct

* There's no human gatekeeper, it's fully automated: it takes 2 seconds to send yourself an email with personalized download link and installation instructions.

* It's the only way to keep the internet from caching old versions. This is a security software and I fix vulnerabilities continuously. So it's extra important you get always the latest available build.

Also, don't forget the source is open (GPLv3) and it's always been/will be all in GitHub.
Moreover, the build system is traceable. Every time I release a build, the CI produces a git tag so new and old builds are always reproducible and inspectable by any autonomous auditors anytime.

The automated email zip delivery is there for convenience, but also makes it possible to notify you guys a new version is out with critical security fixes.
Security is a process, not a product. You need a feedback loop, or you're doing it wrong.

Personally, I don't want to be in the business of shit security, and I'd like to discourage users willing to shoot themselves in the foot as much as I can. So the email system is here to stay, sorry.

But as I said, the code is there and so is your freedom to use it. If you really want to skip the email system, just clone the code, switch to the appropriate branch and run `bin/build.sh`. Your zip file will be there. No email required. 👍

**Comment by kunwon1** [comment]
It is gated, in that the number of versions available for download has decreased significantly. I requested a download link, and I was sent one, and by the time I clicked on it, it had expired. This is definitely controlled by a human gatekeeper, i've waited more than one day for the link, and when I get it I can't use it, so I must request from the human gatekeeper a new link, and probably wait another day. This is two days of waiting to get a newer version than the one I have. If I have to wait two days to get code that fixes security issues, when that code had previously been available for instant download, isn't that in and of itself a security issue?

I am going to attempt to build from source, thank you for your response

**Comment by sscarduzio** [comment]
the fact is that we're in a non-normal situation right now, I'm delaying the full release (for ES from 2.x to 5.3.x) because there's a shitty bug I'm fixing that when you hit a "type:forbid" rule, then we have no response.
Another thing is that @coutoPL is currently working on splitting ES wiring code from ReadonlyREST universal code. So it will be much easier to release everything all together for all the versions of ES.

**Comment by coutoPL** [comment]
Yes, slowly moving forward, but I think you shouldn't wait for me with releasing new version of ROR. I cannot estimate when I'll be ready (I wonder if I shouldn't split my task into small ones and PRing them one by one).

**Comment by sscarduzio** [comment]
@coutoPL sure, you could also open a PR and commit to it periodically (or even rollback and try different things). Much easier to discuss, review, give help, and for me to understand your whole reasoning gradually rather than all at once.

Up to you!

**Comment by sscarduzio** [comment]
Yep got it. Even if I'm so busy right now.
At the moment I'm preparing a presentation about ReadonlyREST. I will make a talk at CERN next Wed. Wish me luck!

http://cseminar.web.cern.ch/cseminar/

**Comment by coutoPL** [comment]
Wow, great news! So dude, break a leg 👍
