### ISSUE TITLE
Login popup

### ISSUE THREAD

**Issue by AtzeDeVries** [sscarduzio/elasticsearch-readonlyrest-plugin#22]
Hi,

First of all, thnx for this module, kinda cool!

So is there anyway to have a login popup for basic auth? So clou can (for example) access kibana with authentication from a browser.

**Comment by sscarduzio** [comment]
This would be really nice to have and quite easy to implement!
Will have a look tomorrow:)

**Comment by sscarduzio** [comment]
@AtzeDeVries if you install the latest v1.6 version (available for ES 2.1.1 and ES 2.1.0) you'll have this feature.

**Comment by AtzeDeVries** [comment]
Cool! thnx!

2016-02-18 11:53 GMT+01:00 Simone Scarduzio <notifications@github.com>:

**Comment by AtzeDeVries** [comment]
Hi,

I did not yet have time to test this, but i did and it works great! Thnx

**Comment by sscarduzio** [comment]
Glad to hear! :+1:  :rocket:
