### ISSUE TITLE
downloading from command line

### ISSUE THREAD

**Issue by nmaisonneuve** [sscarduzio/elasticsearch-readonlyrest-plugin#224]
Downloading from command line is complicated due to the current process via email.
(even if i take the link from the th email and use wget it does not work.)

is there a way to simplify that  or to give us the command line to download a given version.

Thanks Simon, 
Nicolas Maisonneuve

**Comment by sscarduzio** [comment]
Hello Nicolas, 
The link I give via email expires after a while to make sure people always come back to get the LATEST version (as vulnerabilities are patched regularly).
If you want to automate it, you have two ways:

* Check out the tag from git and run ./gradlew assemble, then get the zip from build/ folder
* Get it from the email, upload it somewhere **safe** (make sure nobody can tamper with the zip), wget it from there. 

PS: if you go for the second option, I recommend checking with the checksum provided in the email.
