### ISSUE TITLE
GroupsSyncRule should trigger basic auth prompt

### ISSUE THREAD

**Issue by sscarduzio** [sscarduzio/elasticsearch-readonlyrest-plugin#227]
Currently, when we reject a request,  we return an HTTP status code 401 only if  we find a block containing a rule that is subclass of `Authentication`. 

https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/blob/master/src/main/java/org/elasticsearch/plugin/readonlyrest/acl/blocks/Block.java#L139

I propose to add another condition to the `if` that forces to return 401 when a `GroupsSyncRule` or `ExternalAuthenticationAsyncRule` is present.
This is because whenever you declare a group, you are currently forced to also add an authentication rule.

@coutoPL Is there any other case among external connectors I didn't cover?

**Comment by coutoPL** [comment]
`Authentication` interface is a phantom type to mark rules with authentication functionality. `Authorization` interface is also a phantom type - for authorization. At the moment two classes are marked with this interface - `AsyncAuthorization` and `LdapAuthAsyncRule`. If we could mark missed rules with `Authorization` interface, our check function could look like this:

```
private boolean isAuthenticationOrAuthorizationRule(AsyncRule rule) {
    return rule instanceof Authentication ||
        (rule instanceof AsyncRuleAdapter && ((AsyncRuleAdapter) rule).getUnderlying() instanceof Authentication) ||
               rule instanceof Authorization ||
        (rule instanceof AsyncRuleAdapter && ((AsyncRuleAdapter) rule).getUnderlying() instanceof Authorization);
  }
```
or better - using helper:
```
private boolean isAuthenticationOrAuthorizationRule(AsyncRule rule) {
    return Authentication.class.isAssignableFrom(RulesUtils.classOfRule(rule)) || 
           Authorization.class.isAssignableFrom(RulesUtils.classOfRule(rule));
  }
```

**Comment by coutoPL** [comment]
And IMO there should be a validation check in `BlockSettings` class which should guard if any authentication settings rule is present when authorization one is.

**Comment by sscarduzio** [comment]
Yes and yes. Great idea. You got this or you want me to do it? I'm afraid to mess you up with these commits since there's a huge PR open.

**Comment by coutoPL** [comment]
Don't be afraid to change anything outside of ES package. Merge won't be so hard.  I'm leaving today and I'll be back on monday, so if you won't implement this till then, I would do that. In the `huge, opened PR` I have to figure out how to force gradle to run my tasks in every build. Now second and next builds have custom tasks marked as up-to-date. I don't know why. But this is a cause of failing integration tests.
