### ISSUE TITLE
integration tests don't pass in multi-version gradle setup

### ISSUE THREAD

**Issue by sscarduzio** [sscarduzio/elasticsearch-readonlyrest-plugin#232]
Hey @coutoPL let's move the brainstorming to here.
So this is quite a blocker for the project now because there's a queue of bugs to fix and fixing without reliable tests is kinda shooting in the dark 😭

Here is what I did till now:

* Cleared the testcontainers logs from the container stdout
* Cleared the gradle logs with TERM=dumb so logs are readable
* Noticed that some tests fail when executed all together with gradle, but never fail executed in isolation with IDE.
* Noticed that when they fail, the first test method of the class and **all the others in the class** fail too. (makes me think the container is not well initialized for some reason? See [CI log](https://travis-ci.org/sscarduzio/elasticsearch-readonlyrest-plugin/jobs/236629437)) 
* I suspected it was the concurrency of execution of the tests messing up with our static container cache (the ugly hack I proposed yesterday), so I forced gradle to execute one class at a time. NO LUCK still :(

### Container creation & JUnit
JUnit creates a new class instance the whole class every time it executes a test method. 
We don't want to create a container for every method, but a container for every task.
There's two roads to achieve 1container creation per 1class: 
@BeforeClass / @AfterClass container static cache handling (what we're doing)
@Rule (as suggested by [documentation](https://www.testcontainers.org/usage/database_containers.html#junit-rule)) 

I ran out of ideas, except implementing the @Rule thing, but I don't know if and how may concretely help. Any suggestions?

Latest CI log: https://travis-ci.org/sscarduzio/elasticsearch-readonlyrest-plugin/jobs/236629437

**Comment by coutoPL** [comment]
Yep, your merge was a bit premature. I saw that tests were not so reliable. I think that MultiContainer and MultiContainerDependent classes causes problems. My observations show that tests which use ESWithReadonlyRestContainer only, are always reliable. Did you notice that? If so, it might confirm my suspicions. 

As I said, I'll back to it. But earliest, tomorrow evening.

**Comment by sscarduzio** [comment]
Yeah too much excitement of the new build system.. Lesson learnt 👍 
Sure tomorrow is more than OK. Thanks bro. 👊

**Comment by sscarduzio** [comment]
Bash <3 Looking good! Is this ready to merge?
