### ISSUE TITLE
ROR causing excessive active tasks in ES

### ISSUE THREAD

**Issue by dwjvaughan** [sscarduzio/elasticsearch-readonlyrest-plugin#236]
I'm not 100% that this is ROR causing the issue, but I've noticed lots of hung tasks (`_cat/tasks`) in my ES (5.4.0) cluster when ROR is enabled. 

The tasks are `indices:admin/get` and correspond with failed authentication in the log (`no block has matched, forbidding by default` - `USR:[no basic auth header]`) which happens when you open Sense and get prompted for the user/password.

These tasks seem to hang around until the ES service is restarted. I'm not sure if it's causing an issue but on one cluster I have over 1500 active tasks for `indices:admin/get` now! Using latest version of ES and ROR, but this seems to be the case on older versions too.

Any suggestions greatly appreciated!

**Comment by sscarduzio** [comment]
Reproduced and fixed today, it was fucking difficult. Thanks for serving the reproducer test on a silver platter @dwjvaughan 🏅

**Comment by dwjvaughan** [comment]
Ah, so I'm not going crazy. Glad you got to the bottom of it, and thanks for the confirmation.
