### ISSUE TITLE
URI Regex Not working :(

### ISSUE THREAD

**Issue by rikatz** [sscarduzio/elasticsearch-readonlyrest-plugin#24]
So, I've been trying to use the plugin and it was working fine, so I decided to put some more limits on my index with the following rule:

    - name: Write Access
      type: allow
      uri_re: ^.*\:9200\/indexkatz.*
      api_keys: [readwrite]
      methods: [OPTIONS,GET,POST,PUT]

But when trying to use this index, I receive access denied. If I just remove the line of the 'uri_re' and still use the Api-Key (and the other options) the ACL still working fine (I'm able to index, search but not to delete the index).

Don't know if I'm missing something :)

Thanks!

**Comment by rikatz** [comment]
OK, so I figured out that the docs are wrong, and used the following uri_re:

uri_re: ^/indexkatz.*

Now this is working ;)

**Comment by rikatz** [comment]
Created the Merge Request #25 to fix this

**Comment by sscarduzio** [comment]
Brilliant, thanks for contributing!
