### ISSUE TITLE
How to install readonlyRest from `jar` file for ES 2.3.4

### ISSUE THREAD

**Issue by sudhishkr** [sscarduzio/elasticsearch-readonlyrest-plugin#245]
I am trying to setup `readonlyRest` for our ES nodes running version `2.3.4`.

I have followed your build instructions from [here](https://readonlyrest.com/documentation/index.html#Installation).

I had to do a little pre-steps because I wanted to pin to a particular version which was `2.3.4`. Here are the steps I followed : 
     - `wget https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/archive/v1.13.3_es2.3.4.zip` 
     - `unzip v1.13.3_es2.3.4.zip` 
     - `cd v1.13.3_es2.3.4`
     - `brew install maven` # i am using a mac
     - `sh /bin/build.sh`
     - `cd target/*.jar` # pull the generated jar file

Now once I pull the `jar` file out, my understanding is I should be able to run `java -jar *.jar` and thats about it. I run into this error : 

```
>>java -jar readonlyrest-1.13.3.jar 
no main manifest attribute, in readonlyrest-1.13.3.jar
```
Now I need a manifest file/attribute to get going. 

I am also a little lost in the procedure following this as the documentation is confusing me a little for the configuration side of things.

Would appreciate a little help for my current problems. Thanks!

**Comment by sudhishkr** [comment]
```

**Comment by sscarduzio** [comment]
Download any build from the official site and you'll have an email with instructions.

**Comment by sudhishkr** [comment]
Ok thanks. Got this to work. Will send in some feedback for documentation shortly.
