### ISSUE TITLE
plugin security not working

### ISSUE THREAD

**Issue by sLuvpreet33** [sscarduzio/elasticsearch-readonlyrest-plugin#246]
Firstly, thanks for this.

I have installed it on ubuntu 16.04 LTS, elasticsearch version 5.3.2

I installed this plugin of matching version with elastic.
I have a free license for x-pack.

Here is my config, 

    xpack.security.enabled: false

    readonlyrest:
    enable: true
    response_if_req_forbidden: Access denied!!!

    access_control_rules:

      - name: "localhost"
        type: allow
        hosts: [localhost]

      - name: "::admin::"
        auth_key_sha256: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        type: allow
        actions: ["indices:admin/create","indices:data/write/index","indices:data/write/bulk","indices:data/write/bulk[s]","indices:data/write/delete","indices:data/read/get","indices:data/read/explain","indices:data/read/field_stats","indices:data/read/mget","indices:data/read/msearch","indices:data/read/mtv","indices:data/read/scroll","indices:data/read/scroll/clear","indices:data/read/search","indices:data/read/tv"]
        indices: ["*"]

 But, after installing this, I can still request on elasticsearch and get all the data.

    monitoring-server@monitoring-server:~$ curl -XGET 'localhost:9200/_cat/indices?v&pretty'
    health status index                           uuid                   pri rep docs.count docs.deleted store.size pri.store.size
    yellow open   local7-default-logs             6Od96QIuQPSlrUbSsDZQWw   5   1         53            0    180.7kb        180.7kb

Why is it not working, is my config correct ?

**Comment by ld57** [comment]
Hi,

it is because of the block
```
  - name: "localhost"
    type: allow
    hosts: [localhost]
```

this block give full access to everything in ES, if you execute your curl query from the host where ES and RoR are installed

remove it, restart ES, and retry

**Comment by sLuvpreet33** [comment]
Okay, I removed it, restarted it and then tried it again,

    server@server:~/ansible-tower-setup-3.1.3$ curl -u admin:cyCle123 -XGET 'localhost:9200/_cat/indices?v&pretty'
    Access denied!!!

My username and password is correct. I obtained hash for them and added it in the file.

Still access denied ?

**Comment by sscarduzio** [comment]
You can inspect the log line in ES and see the history field, it will tell you what rule is matching and what is not.

BTW, remove that indices: ["*"] because it's exactly like not having it, except it may slow down processing.
