### ISSUE TITLE
LDAP User Based Authorisation 

### ISSUE THREAD

**Issue by shubhamverma27** [sscarduzio/elasticsearch-readonlyrest-plugin#247]
Hi, @sscarduzio , In the LDAP Settings like we mention groups for authorisation.
I wanted to mention it only for specific user id not group from ldap but user from ldap.
How to do that?

**Comment by shubhamverma27** [comment]
I tried 
   access_control_rules:
    - name: "TESTING"
      ldap_authentication:
        name: "ldap1"
      groups:
        - cool_kids
      kibana_access: rw
      kibana_index: .kibana-drakkhen
      indices: [ '.kibana', 'blah' ]

    users:
    - username: drakkhen
      groups:
      - cool_kids
but its working for all users then?? not the specified username

**Comment by shubhamverma27** [comment]
@sscarduzio  A little help here, please?

**Comment by sscarduzio** [comment]
Yeah I think as of now you cannot do that. You can propose this as a feature request in the forum.

**Comment by shubhamverma27** [comment]
@sscarduzio is there anyway to implement it? I just want to authenticate the user via LDAP and then authorize him based on his user id @{user} and not LDAP group (Locally)
Can I use If condition in the yml or anything??

**Comment by sscarduzio** [comment]
You know, something like 6-7 months ago I implemented a Javascript rule which accepted a code fragment.. Never published the feature because back then was kinda an overkill.
