### ISSUE TITLE
SSL is Disabled when enabled in config

### ISSUE THREAD

**Issue by gusnuf** [sscarduzio/elasticsearch-readonlyrest-plugin#253]
Using the latest 1.16.8_es5.5.0, I see this log entry:`[o.e.p.r.e.SSLTransportNetty4] SSL is disabled`

My ROR config is unchanged from a prior release with working SSL and has `http.type: ssl_netty4` and `readonlyrest.ssl.enable: true`

I believe commit 625e9247909c66ae79c3824bf2b0275cd0e388b7 "fix settings prefix offset" is the culprit.  On line 65 of RorSettings.java you unwrap `raw_global.readonlyrest` into `raw`, which I believe removes the outer `readonlyrest` wrapper from the config's path structure. 

However, `SSL_PREFIX` is still `readonlyrest.ssl` so on line 94 when the `enable` setting is queried it is considered missing.

Hopefully I'm steering you in the right direction.

**Comment by sscarduzio** [comment]
Hello Grahame, great report and analysis. I just fixed this, and moving all the integration tests to use SSL from now on, so this kind of regressions (in settings and functionality of SSL) are caught early next time.
