### ISSUE TITLE
RoR installation should it be only on Master nodes? or data nodes as well?

### ISSUE THREAD

**Issue by sudhishkr** [sscarduzio/elasticsearch-readonlyrest-plugin#256]
I am trying to understand if RoR plugin install is needed only on the master nodes OR can they also be setup on the data nodes?

I am running into issues with RoR plugin on the data nodes, and the ES process failing to start.

I am new to this plugin and still trying to understand whats the right way to consume this. Woudl appreciate a little information around this before i make code changes to push this only our master nodes.

**Comment by sscarduzio** [comment]
This plugin only affects the behaviour of the HTTP interface of Elasticsearch (the one running by default on port 9200). 
Data nodes mainly communicate with their peers and master using the transport interface (normally running on port 9300).

Install it only in the nodes that expose the HTTP interface and you intend to protect.

For example if you want to protect or segregate the data seen in Kibana, install ReadonlyREST in the Elasticsearch nodes that Kibana connects to.

**Comment by sudhishkr** [comment]
Thanks @sscarduzio
