### ISSUE TITLE
Kibana short url fails to load upon enabling basic auth

### ISSUE THREAD

**Issue by anandeur** [sscarduzio/elasticsearch-readonlyrest-plugin#259]
Generated shortened URL:
http://<serverIP>:5601/goto/cc53da21315575db0b204f500037c0fa

Upon enabling basic auth, getting the following error message:
_{"statusCode":406,"error":"Not Acceptable","message":"Short url target path must be in the format \"/app/{{appId}}\", found \"/\""}_

Though this works just fine if the user is already logged in!

Browser: Chrome 60.0.3112.90 (Official Build) (64-bit)
Kibana Version: 5.4.1
ReadOnlyREST Version: 1.16.8_es5.4.1

**Comment by sscarduzio** [comment]
Interesting, the host part of the URL is missing. That makes for an invalid URL to begin with.
Have you tried if it produces the same faultyURLs without the plugin installed?

Also, are you using the Kibana plugin or just the ES one?

**Comment by anandsingh23** [comment]
My Bad. The shortened url is actually _http://hostname:5601/goto/cc53da21315575db0b204f500037c0fa_
Is there a separate kibana pugin available for ROR? Didn't find any mention in the documentation.
Anyways, I found this issue mentioned here - https://github.com/elastic/kibana/issues/10456

**Comment by sscarduzio** [comment]
Hi @anandsingh23,

The Kibana plugin is part of the ReadonlyREST PRO and ReadonlyREST Enterprise commercial offers. 

See the offers compared here: [http://readonlyrest.com/#chart]( http://readonlyrest.com/#chart)
