### ISSUE TITLE
ReadOnlyREST's inbuilt RO (read only) access permits user to delete kibana index pattern

### ISSUE THREAD

**Issue by anandsingh23** [sscarduzio/elasticsearch-readonlyrest-plugin#260]
ReadOnlyREST's inbuilt **RO (read only) access** permits the user to delete a pre-defined index pattern from Kibana's management console.

ElasticSearch version: 5.4.1
Kibana Version: 5.4.1
ReadOnlyREST Version: 1.16.8_es5.4.1

**Comment by sscarduzio** [comment]
Hi @anandsingh23, the index pattern access is exceptionally let through as part of an enhancement we made with @psaiz to enhance the user experience of RO users. But I agree with you that letting RO users delete the index patterns is way too much.

Contextually to the same session, we agreed that it's important for ReadonlyREST to still offer a tight RO mode, which we called `ro_strict`. You can read about it in the [docs](https://readonlyrest.com/documentation/#Rules--Elasticsearch_level).

The RegEx we set up back then was this:

https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/blob/master/core/src/main/java/org/elasticsearch/plugin/readonlyrest/acl/blocks/rules/impl/KibanaAccessSyncRule.java#L127

I'll chat with @psaiz and dig down what was the requirement to let through also index pattern requests.

**Comment by sscarduzio** [comment]
I spoke with @psaiz and basically I can remove the "index-pattern" from the RegEX. Expect this fix in 1.16.10 in a few days tops.

**Comment by anandsingh23** [comment]
Thanks @sscarduzio for an expedited resolution
