### ISSUE TITLE
Have you considered moving users out of elasticsearch.yml?

### ISSUE THREAD

**Issue by javiercanillas** [sscarduzio/elasticsearch-readonlyrest-plugin#263]
I find quite annoying to restart the whole cluster right after I put a new user into ElasticSearch. Have you consider moving user data into a index within ES? Or maybe into another file that you can reference from configuration and enable a refresh thread from time to time to reload them?

**Comment by sscarduzio** [comment]
We already have dynamic settings loaded from index. It's part of ROR pro.

https://readonlyrest.com/pro.html

**Comment by krism74** [comment]
Hi @sscarduzio : Apologies for posting in a wrong thread. I am unable to open a new request here, the submit button is greyed out for some reason. Any reason for that?

**Comment by sscarduzio** [comment]
@krism74 no idea, GH issues maybe? Try opening a topic on https://forum.readonlyrest.com

**Comment by sscarduzio** [comment]
related: we can have now ROR settings in a separate file readonlyrest.yml (living in the same dir with elasticsearch.yml)
