### ISSUE TITLE
Audit log to optionally log executed queries

### ISSUE THREAD

**Issue by tozuan** [sscarduzio/elasticsearch-readonlyrest-plugin#266]
I believe that there are many cases where sensitive information is stored in ElasticSearch and there is a reason to give access to the data for some people, but still need to be able to detect malicious or unnecessary access. In other words, it would be good for audit log to also record the executed query. And also possibly amount of returned documents. 

Requirements would be following:
1. Add new setting "audit_include_query" - default false
2. Include request's body in the audit log in case the setting is true. If the request body is too large, it could be truncated.

With a quick glance, I'm unsure how would it be possible to get amount returned documents.

If others also agree, I could drop in a pull request for this.

**Comment by sscarduzio** [comment]
Hi @tozuan, we have a voting system for this in https://forum.readonlyrest.com "new features" section.

Anyway, at a glance, looks like it would be useful to restrict this to selected indices, as it has a considerable impact in performance and storage. Therefore the boolean would become an array of strings, i.e. `audit_include_query: ["bla-*", "sensitive-index", "*-personal" ]`
