### ISSUE TITLE
Docs : define "admin" role for "kibana_access" option

### ISSUE THREAD

**Issue by fbaligand** [sscarduzio/elasticsearch-readonlyrest-plugin#267]
Currently, in documentation, for "kibana_access" option, we can see "ro", "ro_strict" and "rw" possible values.

But on this youtube video (https://www.youtube.com/watch?v=K4A29-1ZNz8) and on forum (https://forum.readonlyrest.com/), we can see another possible value : "admin".

=> Could you add in documentation this new possible value ("admin") and explain the difference with "rw" value ?

**Comment by sscarduzio** [comment]
https://readonlyrest.com/documentation/#Rules--Rules--Elasticsearch_level--KibanaAccess_rule

**Comment by fbaligand** [comment]
Thanks @sscarduzio !
