### ISSUE TITLE
Add "server" possible value to "kibana_access"

### ISSUE THREAD

**Issue by fbaligand** [sscarduzio/elasticsearch-readonlyrest-plugin#268]
Presently, for "kibana_access" option, there is no specific value which matches kibana server user needs (monitor, ...).

It would be great to add a new possible value "server" (for example) which matches precisely kibana server needs.
It would allow to not grant everything to kibana server user.

**Comment by sscarduzio** [comment]
this is an awesome idea

**Comment by fbaligand** [comment]
Great to see you love the idea !

**Comment by fbaligand** [comment]
Currently, To do that, I use a rule with  kibana_access=admin and another rule with actions="cluster:monitor/*"

Maybe it would be relevant to just enhance "admin" profile ?

**Comment by fbaligand** [comment]
@coutoPL why do you close the issue?
The feature has been implemented?

**Comment by coutoPL** [comment]
no plans due to implementation.

@sscarduzio if it's still valid, please create a jira and I reopen the issue. If not, it won't be implemented in near future.

**Comment by sscarduzio** [comment]
@fbaligand we implemented something along these lines, the "unresticted" mode. The reason we don't have a "server" with only the subset of actions the kibana server uses are multiple:

1. The level of permissions necessary for Kibana server would be pretty close to total, so not a great benefit.
2. Kibana has become a central administration point for the whole cluster,  and new features are added continuously. Would be a total hassle to maintain the list of authorized actions for server. It already is for rw, ro, ro_strict, admin.

**Comment by fbaligand** [comment]
Thanks for the detailed explanation.
So "kibana_access: admin" is the recommended way to answer this need?

**Comment by sscarduzio** [comment]
No, admin won't work for the kibana server. Just leave kibana_access out from that block as usual.

**Comment by fbaligand** [comment]
Ok, thank you for the precision.
