### ISSUE TITLE
Use case for LDAp Integration 

### ISSUE THREAD

**Issue by krism74** [sscarduzio/elasticsearch-readonlyrest-plugin#269]
Here is my Usecase
We have a  multi-tenant environment where the kibana is used predominantly to display data. We use logstash extensively to gather the data and push to ES. Users are authenticated by LDAP in another portal and are presented with a view to kibana. We are looking to use an authentication + authorization strategy for Kibana. We do not want to use shield because of obvious reasons. 

1.    Multi-Tenant
2. 	LDAP based groups/roles.
3. 	Users may belong to one tenant or more than one
4. 	Each tenant can have multiple indices
5. 	Tenant level restrictions on indices [ admins can view all indices, marketing can view only their view]
6. 	Users from tenants belong to atleast one role, possiblity of multiple roles exist.

![image](https://user-images.githubusercontent.com/6234481/30144457-f9fd7eee-9350-11e7-9017-feb771ef094d.png)
	
Given this scenario do you think we can use this plugin to acheive the requirement?

thanks much
kris

**Comment by sscarduzio** [comment]
Yes this should be possible. It is basically what is in the youtube demo, but with LDAP. Of course for the Kibana multi-tenancy and tenancy/group switching you would need the Kibana plugin that comes with ROR Enterprise.
