### ISSUE TITLE
 Plugin [readonlyrest] is incompatible with Elasticsearch [2.1.2]

### ISSUE THREAD

**Issue by ghorkov** [sscarduzio/elasticsearch-readonlyrest-plugin#27]
I received the following error message:

ERROR: Plugin [readonlyrest] is incompatible with Elasticsearch [2.1.2]. Was designed for version [2.1.1]

Is it possible to override this? or are you able to provide support for Elasticsearch 2.1.2? 

Thank you

**Comment by sscarduzio** [comment]
https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/blob/master/download/elasticsearch-readonlyrest-v1.7_es-v2.1.2.zip?raw=true
