### ISSUE TITLE
LDAP group search dependent on DN

### ISSUE THREAD

**Issue by macpoint** [sscarduzio/elasticsearch-readonlyrest-plugin#273]
Hi,
if I setup the plugin to use this group base DN, my groups are found, no issues:

`search_groups_base_DN: "cn=sub_group,cn=groups,dc=company,dc=com"`

However, if I set

`search_groups_base_DN: "cn=groups,dc=company,dc=com"`

no groups are found, although I would expect even more groups should pop up in the result: 

```
[2017-09-14T16:33:45,400][DEBUG][o.e.p.r.a.d.l.l.GroupsProviderLdapClientLoggingDecorator] Trying to fetch user [id=user@company.com, dncn=USER_NAME,L=AMER,DC=COMPANY,DC=COM] groups from LDAP [ldap1]
[2017-09-14T16:33:56,170][DEBUG][o.e.p.r.a.d.l.l.GroupsProviderLdapClientLoggingDecorator] LDAP [ldap1] returned for user [user@company.com] following groups: []
```

Test LDAP queries are returning expected results

```
ldapsearch -h ldap.company.com -x -b "cn=groups,dc=company,dc=com" "(&(cn=*)(uniqueMember=cn=USER_NAME,L=AMER,DC=COMPANY,DC=COM))" dn
...
# numEntries: 21
```

```
ldapsearch -h ldap.company.com -x -b "cn=sub_group,cn=groups,dc=company,dc=com" "(&(cn=*)(uniqueMember=cn=USER_NAME,L=AMER,DC=COMPANY,DC=COM))" dn
...
# numEntries: 14
```

I am suspicious that some timeout may occur when searching just `cn=groups,dc=company,dc=com` as potentially LOTS of groups may be returned since it seems that no return attribute is specified

```
"(&(cn=*)(%s=%s))", userGroupsSearchFilterConfig.getUniqueMemberAttribute(),
              Filter.encodeValue(user.getDN())
```

(I am not a Java programmer so I may be wrong here). Please note that I specify `dn` in the example ldapsearch as a returning attribute. The delay in the above log snippet may indicate a long timeout between the two messages (11 seconds).

**Comment by sscarduzio** [comment]
Are you aware of the timeout settings in the LDAP connector?
https://readonlyrest.com/documentation/#Users_and_Groups--LDAP_connector

**Comment by macpoint** [comment]
Yes, I have tried extending both timeouts to 30s but still no luck - I get `java.io.IOException: Connection reset by peer` as the LDAP server cuts the connection. 

If specifying the `dn`, the response is very fast:

```
time ldapsearch -h ldap.company.com -x -b "cn=groups,dc=company,dc=com" "(&(cn=*)(uniqueMember=cn=USER_NAME,L=AMER,DC=COMPANY,DC=COM))" dn
...
# numEntries: 21

real	0m1.070s
user	0m0.008s
sys	0m0.020s
```

Without that, some bad recursion is most likely occurring as it seems to me that the query is trying to search groups within all groups found...

**Comment by macpoint** [comment]
One additional note to this:
it may be enough to make the group search filter configurable so that I can override the `cn=*` part of the filter, i.e. by specifying the search filter such as, `(&(objectClass=group)(uniqueMember=cn=USER_NAME,...))` (or whatever the group name attribute is)

**Comment by sscarduzio** [comment]
how would you imagine this in terms of mocked up yaml settings?

**Comment by macpoint** [comment]
Something like
`search_groups_filter: "(objectClass=group)" # user defined setting`

this setting would complete the search filter template by ANDing it with the `uniqueMember` search filter stub:

`(&SEARCH_GROUPS_FILTER_DEFINED_BY_USER(uniqueMember=cn=USER_NAME,...))`

Or maybe an option to specify the whole search string would give even more freedom...

**Comment by sscarduzio** [comment]
I find the second option very liberating, as it delegates everything to the user (which 9/10 is more competent than me on LDAP) 😅

**Comment by macpoint** [comment]
For me, even the first option would be sufficient. But I admit that the second might satisfy most users and if you are able to inject the user `dn` to the query, I think it is the best option.

(though I can imagine someone might even want to use dynamic LDAP attributes generated on-the-fly by some LDAP servers (such as `memberOf`), but that's another story...)

**Comment by macpoint** [comment]
I tried specifying the `cn` attribute for the `SearchRequest` (in `UnboundidGroupsProviderLdapClient.java`) and it helped a lot. It now queries just the `cn` attribute, avoiding any recursion (and it seems that `cn` is actually the only attribute that the [code is interested in](https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/blob/master/core/src/main/java/org/elasticsearch/plugin/readonlyrest/acl/definitions/ldaps/unboundid/UnboundidGroupsProviderLdapClient.java#L86) to get the user groups so it should be there):

```java
      connection.getConnectionPool().processRequestsAsync(
        Lists.newArrayList(
          new SearchRequest(
            new UnboundidSearchResultListener(searchGroups),
            userGroupsSearchFilterConfig.getSearchGroupBaseDN(),
            SearchScope.SUB,
            String.format(
              "(&(cn=*)(%s=%s))", userGroupsSearchFilterConfig.getUniqueMemberAttribute(),
              Filter.encodeValue(user.getDN())
            )
          , "cn")),
        requestTimeout.toMillis()
      );
```

**Comment by sscarduzio** [comment]
Oh nice, so if I merge this we can have a generically more optimised query because it selects just the cn? Not clear to me how this avoid any recursion though.

**Comment by sscarduzio** [comment]
Also I think a potential obstacle to the free query string would be the escaping of the user DN (which is encoded with  Filter.encodeValue(user.getDN()) )

**Comment by macpoint** [comment]
Yes, specifying `cn` will query (and return) just the `cn` of the groups, which is all you need. 

To sum this up, I think the most feasible solution to this is:

1. Add an option to specify `group_search_filter` (this value should replace the `cn=*`), which we can use to specify the groups we are interested in. Example value: `"(objectClass=group)(cn=application*)"` - this will search groups with `group` objectClass, but only those starting with `application` string. The resulting search filter will be `(&(objectClass=group)(cn=application*)(uniqueMember=cn=USER_NAME,...))`
2. Add an option to specify the group_name_attribute (default `cn`). This will be the attribute requested by the LDAP search (the attribute that carries the group name)

**Comment by sscarduzio** [comment]
@macpoint can you check the commit I just made?

**Comment by macpoint** [comment]
@sscarduzio thanks for the commit!

It works ok for my sample build, just 1 note. The search filter [here](https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/blob/fec4fe8fca10a97cb37e881802bf36c3e730eff9/core/src/main/java/org/elasticsearch/plugin/readonlyrest/acl/definitions/ldaps/unboundid/UnboundidGroupsProviderLdapClient.java#L78) should go without parentheses (something like `"(&%s(%s=%s))"`), otherwise the configuration looks weird when specifying multiple filters:

`group_search_filter: "objectClass=orclGroup)(cn=application*"`

This is better:

`group_search_filter: "(objectClass=orclGroup)(cn=application*)"`

Other that that, it works well.

**Comment by sscarduzio** [comment]
Hi @macpoint I need your help: can you review latest commit? 

* I rearranged the [parens](https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/blob/master/core/src/main/java/org/elasticsearch/plugin/readonlyrest/acl/definitions/ldaps/unboundid/UnboundidGroupsProviderLdapClient.java#L78)
 
* I isolated the problem that was breaking [this test](https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/blob/master/core/src/test/java/org/elasticsearch/plugin/readonlyrest/acl/definitions/ldaps/UnboundidGroupsProviderLdapClientTests.java#L58). That is, the fact we added group_name_attribute  as a parameter to [this function](https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/blob/master/core/src/main/java/org/elasticsearch/plugin/readonlyrest/acl/definitions/ldaps/unboundid/UnboundidGroupsProviderLdapClient.java#L83).

**Comment by macpoint** [comment]
> I rearranged the parens

It seems to me that this only reverts https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/commit/716d11a111b3e4ff75a3bb020afd57b43ef5f606 ... is it what you meant?

> I isolated the problem that was breaking this test. That is, the fact we added group_name_attribute as a parameter to this function.

Seems ok to me (if that's temporary)...

**Comment by macpoint** [comment]
Just realized one more thing - the [getAttributeValue](https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/blob/master/core/src/main/java/org/elasticsearch/plugin/readonlyrest/acl/definitions/ldaps/unboundid/UnboundidGroupsProviderLdapClient.java#L89) function should retrieve the `group_name_attribute` value from the LDAP response instead of the hardcoded `cn` because the user expects this attribute carries the actual group name.

**Comment by sscarduzio** [comment]
If I remove the parentheses, the test fails. This is the query string it generates without parentheses

```
(&cn=*(uniqueMember=cn=Eric Cartman,ou=People,dc=example,dc=com))
```

```
LDAPException(resultCode=87 (filter error), errorMessage='Expected an opening parenthesis in the provided filter string at position 2.')

```
How would you make this test work?

**Comment by macpoint** [comment]
Yes, that's why the `group_search_filter` must be provided full in the config (this means with parentheses). Few examples:
```
group_search_filter: "(objectClass=group)(cn=application*)"
group_search_filter: "(objectClass=group)"
group_search_filter: "(cn=*)"
```
It is quite common approach, actually...

**Comment by sscarduzio** [comment]
I think [now](https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/blob/master/core/src/main/java/org/elasticsearch/plugin/readonlyrest/acl/definitions/ldaps/unboundid/UnboundidGroupsProviderLdapClient.java#L73) it makes sense :)

**Comment by macpoint** [comment]
@sscarduzio ok, great, the tests seem to be passing now 👍

**Comment by sscarduzio** [comment]
@macpoint thanks for the guidance on this one. The last thing I'd like to ask you is if you could create a documentation sentence for the two new settings we just introduced?

**Comment by macpoint** [comment]
Sure, here it is:

`group_search_filter` - LDAP search filter (or filters) to limit the user groups returned by LDAP. This filter will be joined (with `&`) with `unique_member_atttribute=user_dn` filter resulting in this LDAP search filter: (&YOUR_GROUP_SEARCH_FILTER(unique_member_atttribute=user_dn)). Examples:
```
group_search_filter: "(objectClass=group)"
group_search_filter: "(objectClass=group)(cn=application*)"
group_search_filter: "(cn=*)" # basically no group filtering
```

`group_name_attribute` - group object attribute that carries its name (group name). Example:
```
group_name_attribute = "cn"
```

**Comment by sscarduzio** [comment]
Thanks @macpoint!

> group_name_attribute - group object attribute that carries its name (group name).

Is this equivalent to say:
`group_name_attribute` - the group object attribute that contains the names of the ROR groups

**Comment by macpoint** [comment]
Yes, the groups (or group names) are translated to RoR groups by the application. So you can say  _the LDAP group object attribute that contains the names of the ROR groups_

**Comment by sscarduzio** [comment]
updating the docs right now.
