### ISSUE TITLE
Auditing: Make the implementation of the serialization tool configurable

### ISSUE THREAD

**Issue by elaPa** [sscarduzio/elasticsearch-readonlyrest-plugin#275]
It would be useful to be able to specify the format/fields of the audit logs.
As discussed, this could be achieved by providing the custom implementation of SerializationTool.java

Currently, there is no way of injecting custom SerializationTool (it is hardcoded in RequestContext.java and ResponseContext.java). 
Make it possible to provide the custom SerializationTool either by a java option or ideally YAML setting.

**Comment by sscarduzio** [comment]
@elaPa please see #293 :)

**Comment by elaPa** [comment]
Thank you so much for implementing this!
