### ISSUE TITLE
ENV vars in readonlyrest.yml

### ISSUE THREAD

**Issue by sommarnatt** [sscarduzio/elasticsearch-readonlyrest-plugin#283]
Hi!

Just a small feature request, probably not that important, but ran into it and debug refused to tell me anything ;)

Using ES + ROR with docker and using ENV vars in elasticsearch.yml works well, however readonlyrest.yml doesn't seem to work with ENV vars.

Seems like a solid plugin otherwise, great work!

**Comment by sscarduzio** [comment]
Hi @sommarnatt,

Thanks for bringing this up, I didn't think about this before. Makes sense, will add it to the pipeline.

**Comment by coutoPL** [comment]
see: https://github.com/beshu-tech/readonlyrest-docs/blob/master/elasticsearch.md#environmental-variables
