### ISSUE TITLE
Suggestions to improve documentation

### ISSUE THREAD

**Issue by trondhindenes** [sscarduzio/elasticsearch-readonlyrest-plugin#285]
Here's my list of things I feel should be in the documentation, that I've learned as I've worked with ReadonlyRest. I would submit a doc PR, but I'd like to get these verified before doing so.

1. A kibana access rule still requires an index spesification: From the docs it's easy to assume that this is sufficient:
```
    - name: kibana-regular
      groups: ["kibana-regular"]
      kibana_access: rw
```
This seems to not be the case, the rule still needs to speficy the index to apply the "kibana access rule" onto:
```
    - name: kibana-regular
      groups: ["kibana-regular"]
      kibana_access: rw
      indices: [".kibana"]
```

2. Wildcards: Docs don't call out explicitly how to use wildcards to simplify rules and where they are allowed. Can I use a wildcard in the middle of an action rule? In an index? Wildcard "rules" should be described.

**Comment by sscarduzio** [comment]
Awesome, let's move it to https://github.com/beshu-tech/readonlyrest-docs !
