### ISSUE TITLE
Found an instance of CompositeIndicesRequest that could not be handled: report this as a bug immediately! DeleteRequest

### ISSUE THREAD

**Issue by Cytior** [sscarduzio/elasticsearch-readonlyrest-plugin#290]
Since I've seen a similar issue reported here, this is mine !

Full line : 
`
[2017-11-07T14:35:57,822][ERROR][o.e.p.r.e.r.RCTransactionalIndices] Found an instance of CompositeIndicesRequest that could not be handled: report this as a bug immediately! DeleteRequest
`

Using ElasticSearch 5.4.0 and readonlyrest-1.15.0_es5.4.0

**Comment by sscarduzio** [comment]
@Cytior: this is not the case anymore. Install the latest ROR please, the current version is 1.16.13.

**Comment by Cytior** [comment]
Thanks for the quick reply.
I will upgrade our plugin soon.
