### ISSUE TITLE
unrecognized action indices:admin/mappings/get

### ISSUE THREAD

**Issue by trondhindenes** [sscarduzio/elasticsearch-readonlyrest-plugin#296]
I'm in the middle of a rolling update to Elasticsearch 6, and keep getting this message in my logs:
`[2017-11-25T17:57:57,720][INFO ][t.b.r.a.b.r.i.KibanaAccessSyncRule] RW access to Kibana, but unrecognized action indices:admin/mappings/get reqID: 22503156-2099699376#14300`
This is happening on the ES6 node. Not sure what it is, but I thought I'd report it anyway.

**Comment by askids** [comment]
I have seen this action in ROR logs with v5.5.1 also. So not specific to ES6. But I see this once in a while.

**Comment by coutoPL** [comment]
it's already fixed
