### ISSUE TITLE
uid in unique_member_atttribute

### ISSUE THREAD

**Issue by StupidScience** [sscarduzio/elasticsearch-readonlyrest-plugin#300]
Hello.
It is always `unique_member_atttribute=user_dn` in group search filter.
But in my case it should be `unique_member_atttribute=user_uid`.

I understand how to hardcode it but don't think this is the best solution.
Any chance to get an option in settings? Something like `user_attribute_in_group`.

**Comment by slavavalkanova** [comment]
I am having the same issue -
even when I use the unique_member_atttribute: "member"  , in the debug logs I can see that it is returning
[DEBUG][t.b.r.a.d.l.u.UnboundidGroupsProviderLdapClient] LDAP search string: (&(cn=*)(uniqueMember=CN=***

Can you please get in touch with us? Thanks.

**Comment by slavavalkanova** [comment]
Hi mate,
As I had the same issue, the attribute is working, but what we are using is mispelled:  triple "t"
Just write it properly and it will work:  unique_member_attribute

**Comment by Vebryn** [comment]
> 
> 
> Hello.
> It is always `unique_member_atttribute=user_dn` in group search filter.
> But in my case it should be `unique_member_atttribute=user_uid`.
> 
> I understand how to hardcode it but don't think this is the best solution.
> Any chance to get an option in settings? Something like `user_attribute_in_group`.

Same for me #478
