### ISSUE TITLE
ReadonlyREST login failed

### ISSUE THREAD

**Issue by ramaswamy27** [sscarduzio/elasticsearch-readonlyrest-plugin#303]
Hi All,
I am newbie to ReadonlyREST which feature is newly added to my existing ELK cluster. Initially, the installation and configuration went fine after lot of changes made that used to work LDAP authentication as well.  Later I realized that we need a fresh configuration then I deleted VM and deployed and configured ReadonlyREST. Now, i am unable to login ReadonlyREST  with basic credentials defined in my kibana.yml.

I am suspecting issue with the ReadonlyREST setting might be cached on one of my Elasticsearch nodes. Please correct me, if it wrong and help out here.

**Comment by sscarduzio** [comment]
are you using also the kibana plugin?

**Comment by ramaswamy27** [comment]
Hi,
Yes, we configured kibana-5.6.3 and readonlyrest_kbn_pro-1.16.14_es5.6.3.

**Comment by sscarduzio** [comment]
Not sure I understood the problem well, but you could have old settings in the ".readonlyrest" index if you used the cluster-wide settings GUI in Kibana. I suggest deleting the index from ES and start over.

**Comment by ramaswamy27** [comment]
Thank you for update. I could resolve the issue by exploring elasticsearch readonly logs. Any how the log format and the shortname patterns in log such as CGR:, BRS:, OA:, CNT: and other are not much informative. Could you please explain briefly about the patterns.

**Comment by sscarduzio** [comment]
Hey @ramaswamy27 thanks for the suggestion, I added the description of each field in [ROR ES documentation](https://github.com/beshu-tech/readonlyrest-docs/blob/master/elasticsearch.md#interpreting-logs)
