### ISSUE TITLE
Documentation doesn't reflect ES 6.1.0 changes

### ISSUE THREAD

**Issue by floggle** [sscarduzio/elasticsearch-readonlyrest-plugin#305]
See: https://discuss.elastic.co/t/elasticsearch-6-1-0-settings-parser-error/112805

A valid config setting in earlier versions of ES/RoR no longer works. The documentation doesn't state what should be used instead for 6.1.x

I'm not that person, but I get the same error.

**Comment by floggle** [comment]
Ah, I see: https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/issues/301

However the documentation doesn't reflect that. It says explicitly:
"Edit  config/elasticsearch.yml  and add your configuration as seen in examples."

Conversely, the term "readonlyrest.yml" doesn't appear anywhere in the docs.
Also, the error you get when you don't have a "readonlyrest" attribute is:
"tech.beshu.ror.commons.settings.SettingsMalformedException: Could not find required attribute 'readonlyrest'"

Which isn't isn't saying it's in a separate file. Reading that I'd think (and did think) the issue was with the elasticsearch.yml file.

**Comment by sscarduzio** [comment]
Hey @floggle thanks for bringing this up. Where do you see this string in the docs? 

> "Edit config/elasticsearch.yml and add your configuration as seen in examples."

For some reason I can't find it!

**Comment by carlosavim** [comment]
It's written in the readme of the repo.
> 1. Install the plugin
> 
> Download the binary release for your Elasticsearch version from the official website.
>
> 2. Configuration
> 
> Append either of these snippets to config/readonlyrest.yml
> ...

`config/readonlyrest.yml` doesn't exist and even if u create it in Elasticsearch root (`/usr/share/elasticsearch`), its still displaying the error above.

There are the errors:

- The config is never found if placed in anywhere other then in `/etc/elasticsearch/elasticsearch.yml`
- If placed in `/etc/elasticsearch/elasticsearch.yml`, the config is found but the error `tech.beshu.ror.commons.settings.SettingsMalformedException: IllegalStateException[only value lists are allowed in serialized settings]` appears then.

I never succeed to make the plugin work on ES6.1.1.

**Comment by sscarduzio** [comment]
Hello @carlosavim! the `readonlyrest.yml` should be placed in the same folder of `elasticsearch.yml`.
In order to allow the parsing of this file, remove any ROR related YAML from `elasticsearch.yml` before, otherwise will try to parse it first.

I will add a log message revealing where ROR is trying to find the `readonlyrest.yml` nevertheless.

**Comment by sscarduzio** [comment]
actually you should already be able to grep this line in the log, which will reveal the path where ROR is trying to find its `readonlyrest.yml`.
>          "Could not find settings in "

**Comment by carlosavim** [comment]
Hello,
Thanks for the help @sscarduzio, the plugin is working now with ES6.1.1
Moving the config file to `/etc/elasticsearch/readonlyrest.yml` made it on CentOS.
