### ISSUE TITLE
Exception in thread "main" sun.net.ftp.FtpLoginException: Invalid username/password

### ISSUE THREAD

**Issue by tilllt** [sscarduzio/elasticsearch-readonlyrest-plugin#310]
I know this is probably a very stupid mistake i made but i really dont know what is causing this:
1. entered email adress to get link to readonlyrest
2, got mail with link
3. cannot copy link and download with wget on server, ERROR 403.
4, Downloaded on laptop, put readonlyrest on server, with this result:

`/usr/share/elasticsearch# bin/elasticsearch-plugin install file://usr/share/elasticsearch/readonlyrest-1.16.15_es6.1.2.zip                                                                                -> Downloading file://usr/share/elasticsearch/readonlyrest-1.16.15_es6.1.2.zip                                                                                                                                     Exception in thread "main" sun.net.ftp.FtpLoginException: Invalid username/password                                                                                                                                        at sun.net.www.protocol.ftp.FtpURLConnection.connect(FtpURLConnection.java:315)                                                                                                                                    at sun.net.www.protocol.ftp.FtpURLConnection.getInputStream(FtpURLConnection.java:400)                                                                                                                             at org.elasticsearch.plugins.InstallPluginCommand.downloadZip(InstallPluginCommand.java:326)                                                                                                                       at org.elasticsearch.plugins.InstallPluginCommand.download(InstallPluginCommand.java:245)                                                                                                                          at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:213)                                                                                                                           at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:204)                                                                                                                           at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)                                                                                                                          at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)                                                                                                                                        at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:75)                                                                                                                                                at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)                                                                                                                                        at org.elasticsearch.cli.Command.main(Command.java:90)                                                                                                                                                             at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:48)`

**Comment by sscarduzio** [comment]
https://github.com/beshu-tech/readonlyrest-docs/blob/master/elasticsearch.md#installing

**Comment by tilllt** [comment]
These instructions dont work 1:1 for me since my EMail client is not on my server. So i need to "transport" the link i received over to my server. First i copied the link "as is" but bash cannot deal with & characters in a pasted url. So i wrapped the url in doublequotes and tried to download it with wget, now i get:
`
Resolving readonlyrest-data.s3.amazonaws.com (readonlyrest-data.s3.amazonaws.com)... 52.218.52.153                                                                                                                 Connecting to readonlyrest-data.s3.amazonaws.com (readonlyrest-data.s3.amazonaws.com)|52.218.52.153|:443... connected.                                                                                             HTTP request sent, awaiting response... 400 Bad Request                                                                                                                                                            2018-02-01 00:01:00 ERROR 400: Bad Request. `

**Comment by tilllt** [comment]
The error message i originally posted is what i get when i use my laptop to download the plugin, then copy it to the server, then try to install it there.

**Comment by sscarduzio** [comment]
you are missing a slash after the "file", it's not `file://usr..`, but `file:///usr`

This is the correct one:
```
/usr/share/elasticsearch# bin/elasticsearch-plugin install file:///usr/share/elasticsearch/readonlyrest-1.16.15_es6.1.2.zip
```

**Comment by tilllt** [comment]
Aha, i thought i had tried that before. Thanks.
