### ISSUE TITLE
Disable searching on data in Kibana

### ISSUE THREAD

**Issue by bm1391** [sscarduzio/elasticsearch-readonlyrest-plugin#313]
Hi there,

I'm trying to disable the ability to search on data (through search bar or devTools console) in order to prevent/mitigate people from issuing large and/or expensive queries to elasticsearch. 

Here are my actions allowed:

>     actions: ["indices:data/read/search","cluster:monitor/*","cluster:monitor/nodes/*","indices:data/read/mget","indices:admin/get","indices:data/read/msearch"]

The above seems to be the minimum to allow Kibana to work but I can still search on the data. Here are some of the logs I am receiving.

> [2018-02-08T18:41:41,246][INFO ][t.b.r.a.ACL              ] ALLOWED by { name: 'Accept everything from the localhost', policy: ALLOW} req={ ID:303197989-1756714446#329, TYP:SearchRequest, CGR:N/A, USR:admin(?), BRS:false, ACT:indices:data/read/search, OA:127.0.0.1, IDX:.kibana, MET:POST, PTH:/.kibana/_search?size=1000&from=0, CNT:<OMITTED, LENGTH=277>, HDR:Authorization,Connection,Content-Length,content-type,Host, HIS:[Accept everything from the localhost->[methods->true, hosts->true, actions->true]] } 

It seems I need a way to parse out and check if the 'TYP' field is equal to 'SearchRequest'.

Is there a way to do this? If not, is their a better way to achieve this goal?

Thanks a lot for a great tool btw, will hopefully be using it in production soon!

**Comment by sscarduzio** [comment]
Hi @bm1391!
Interesting request but, at the Elasticsearch level, I'm not sure you can effectively distinguish between searches coming from dev tools and similar ones coming from Kibana visualizations.
You can certainly work your way back from log lines to build a white list of licit queries using a combination of actions and uri_re rules, however I'm not sure it's going to be exhaustive.

No we don't have a rule to create policies about the request types, as action strings do a way better job for creating rules as they are very wildcard friendly (their name goes from the generic to the specific i.e. "indices:data/read/search".

A good way to distinguish between queries coming from the dev tools kibana app would be the Kibana plugin. We could add a feature such that the Kibana plugin would send the current Kibana app name in every query, so the ACL in Elasticsearch could make decision upon that information. I.e. we could have a "kibana_app" rule.

**Comment by bm1391** [comment]
Thanks for getting back. I think I'll have to deal with allowing the search. It seems like implementing a uri_re for the search rules could be easily bypassed anyhow.
