### ISSUE TITLE
Error with rest.action.multi.allow

### ISSUE THREAD

**Issue by seanziee** [sscarduzio/elasticsearch-readonlyrest-plugin#315]
I'm playing around with implementing this and everything works fine but when I added this line which you say is important for production `rest.action.multi.allow_explicit_index: false` I get an error from Kibana  and I can't get it regardless of user. I'm using nginx with OwnHome & ROR in conjunction: ES version 5.6.3. Once I get this up and running I'd love to contribute it as a config to use OwnHome with ROR. 

This is the error from Kibana:
 ```Kibana must be able to specify the index within Elasticsearch multi-requests (rest.action.multi.allow_explicit_index=true).```

Any idea why this is happening?

**Comment by sscarduzio** [comment]
Yeah that’s a really old suggestion. Where is it documented?

**Comment by seanziee** [comment]
https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin#disallow-explicit-indices
