### ISSUE TITLE
Add support for environment variable injection in readonlyrest.yml

### ISSUE THREAD

**Issue by fbaligand** [sscarduzio/elasticsearch-readonlyrest-plugin#318]
The standard elasticsearch.yml config supports environment variable injection. 
With syntax: ${MY_ENV_VAR}

It would be great that readonlyrest.yml supports environment variable injection too. 

It can be useful, for instance, to inject ldap password in configuration.

**Comment by sscarduzio** [comment]
DONE.

**Comment by sscarduzio** [comment]
are you able to test this from master?

**Comment by fbaligand** [comment]
Wow, I’m really impressed ! You’ve implemented the feature less than 24h after my issue ! You’re awesome !

I will try to test it tonight!

Thanks again for your reactivity!

**Comment by sscarduzio** [comment]
![giphy](https://user-images.githubusercontent.com/1327189/36742120-e2d9f1ce-1bb4-11e8-9d5a-7f0f8cb2a4db.gif)

**Comment by fbaligand** [comment]
I tested the feature, but it didn't work :(

Here are the steps I did : 
- build ror zip, based on tag `v1.16.17-pre2_es6.2.1`
- install ror plugin on Elasticsearch 6.2.1
- set this configuration in readonlyrest.yml : 
```
readonlyrest:
    access_control_rules: 
    - name: "::ADMIN::"
      auth_key: admin:${ADMIN_PWD}
```
- start ES, with `ADMIN_PWD=adminpwd`
- launch command : `curl -u admin:adminpwd localhost:9200/` and get error `403 Forbidden`
- Here's the "forbidden log" generated by ROR : 
`[2018-02-28T15:53:12,718][INFO ][t.b.r.a.ACL              ] [35mFORBIDDEN by default req={ ID:1792895642-301347999#86, TYP:MainRequest, CGR:N/A, USR:admin(?), BRS:true, ACT:cluster:monitor/main, OA:127.0.0.1, IDX:<N/A>, MET:GET, PTH:/, CNT:<N/A>, HDR:Accept,Authorization,content-length,Host,User-Agent, HIS:[::ADMIN::->[auth_key->false]] }`

For information, I run my test with Windows 10. Does the feature work only on Linux/FreeBSD ?
Else, could you reproduce my use case, and tell me if it works for you ?

**Comment by fbaligand** [comment]
@sscarduzio 
I just reviewed your code that replaces env variables and realized that the syntax you choose is `${ENV:ENV_VAR_NAME}`.

So two points : 
- I just tested with this syntax and it works fine now !
- I really think it would be better to use the same syntax than Elasticsearch : `${ENV_VAR_NAME}`
https://www.elastic.co/guide/en/elasticsearch/reference/current/settings.html#_environment_variable_substitution

**Comment by sscarduzio** [comment]
@fbaligand thanks for testing this and for the quick feedback. You are right, will amend.

**Comment by fbaligand** [comment]
Nice !

**Comment by fbaligand** [comment]
I tested successfully the feature in version 1.16.18 !
=> I close the issue.
