### ISSUE TITLE
Providing requested index to (basic auth) external authentication service

### ISSUE THREAD

**Issue by marczahn** [sscarduzio/elasticsearch-readonlyrest-plugin#321]
Hi,

first: This plugin is great! It provides almost exactly what we need. There is just one important thing that is missing for our use case.

It is actually a general question but in our case just for the basic auth: Is it possible or planned to provide the requested index to the endpoint that is handling the authorization? By now only user and password are sent.

The context is that we have a multi tenancy environment and we need to check a user against the requested index itself.

**Comment by sscarduzio** [comment]
The information about if the index is allowed or not derives from how ES parses the request. If you are interested in checking if somebody is allowed to an index/alias you just try to search with a HTTP request to that index, including your credentials.

I.e.  checking if foo has access to index1:
```
GET http://es:9200/index1/_search 
Authorization: Basic <base64(foo:pass)>
```
if 200 is returned: yes, otherwise no.

I hope this helps, otherwise provide more context to your requirement

**Comment by marczahn** [comment]
I am afraid, I don't get it. The problem is, that the auth endpoint of the basic auth has no information about the requested index. It can only access user and password from the request.

**Comment by sscarduzio** [comment]
I don't get either, are you talking about our Kibana plugin or simply Elasticsearch?

**In the case this is all about ES+ROR**
If I understood correctly, your app needs to know if a certain user can or not read an index in particular.
This can already be done in one single API call as I explained.

Furthermore, our ES plugin does not have a dedicated login "endpoint". Where did you read about one?

**Comment by marczahn** [comment]
I guess, we are cross talking :-)

> Furthermore, our ES plugin does not have a dedicated login "endpoint". Where did you read about one?

The plugin itself not, of course

For clarification here an excerpt of our config:

~~~
readonlyrest:
    response_if_req_forbidden: Forbidden by ReadonlyREST ES plugin

    access_control_rules:
      ...
      actions: ["indices:data/*", "indices:admin/mapping/put", "indices:admin/mappings/*", "indices:admin/aliases*", "indices:admin/flush"]
      indices: ["some_prefix_*"]
      external_authentication: "ext1"
      verbosity: error

    external_authentication_service_configs:

    - name: "ext1"
      authentication_endpoint: ".../auth/es/tenant"
      success_status_code: 204
      cache_ttl_in_sec: 60
~~~

When the endpoint defined in ext1 is called there is no information about the requested index Only username and password are provided. But we need the index name since we do not know which one exactly has been requested.

**Comment by sscarduzio** [comment]
@marczahn sorry I completely misunderstood your question. 
Today this is how the RBAC works in ROR:
- authentication (username resolution): optionally external
- authorisation (group resolution): optionally external
- permissions (actions, kibana_access): internally declared
- resources (indices, paths, http methods, uri_re, etc): internally declared

So you can resolve groups and users via an external system, but the permissions of users and groups on resources need to be encoded inside the YAML.

Fortunately, thanks to dynamic variables, you can use the resolved user name as part of the name of the resources i.e.

```yml
indices: [".kibana_@{user}"]
```

This helps in the sense that when you add a user in LDAP or external system, you don't also need to update the YAML.

Would this work for you?

**Comment by sscarduzio** [comment]
@marczahn, and random googler from the future: we now have external to internal groups mapping, which definitely helps in implementing RBAC.

https://github.com/beshu-tech/readonlyrest-docs/blob/master/elasticsearch-details/groups-rule-mapping.md
