### ISSUE TITLE
1.16.18 plugin binary for 2.4.6 has broken plugin-descriptor.properties, fails to install

### ISSUE THREAD

**Issue by skyshard** [sscarduzio/elasticsearch-readonlyrest-plugin#331]
The properties file in the built plugin still has placeholders instead of values, causing installation to fail:

```name=${descriptor.name}
version=${descriptor.pluginVersion}
description=Safely expose Elasticsearch REST API
classname=tech.beshu.ror.es.ReadonlyRestPlugin
java.version=1.8
elasticsearch.version=${descriptor.esVersion}
# ES 2.x compatibility
site=false
jvm=true
isolated=false
```

vs 

```
name=readonlyrest
version=1.16.18
description=Safely expose Elasticsearch REST API
classname=tech.beshu.ror.es.ReadonlyRestPlugin
java.version=1.8
elasticsearch.version=2.4.6

# ES 2.x compatibility
site=false
jvm=true
isolated=false
```

**Comment by kalloa** [comment]
I've noticed exactly the same issue in readonlyrest-1.16.19_es2.4.5.zip

**Comment by kalloa** [comment]
Thanks for fast reply. It means that this issue won't be fixed?

Just for testing, I replaced placeholders with appropriate values and then the installer finished without issues.

**Comment by kalloa** [comment]
Ok, no problem. Finally, we decided to use the latest version of ES (6.2.4) where ReadonlyREST works like charm.

**Comment by sscarduzio** [comment]
I'm extremely happy of your decision 👏👏👏👏👏👏👏
