### ISSUE TITLE
actions tag is not working, pop-up comes with authentication, but never allows to see the indices 

### ISSUE THREAD

**Issue by ghost** [sscarduzio/elasticsearch-readonlyrest-plugin#332]
Hi Team,

I am currently ising readonlyrest plugin with elasticsearch and trying to create read only users for particular indices, when added below config in elasticsearch.yml file and restarted the service.

when I login using elastic/changeme credentials, it works fine and i am able to view all indices. when I tried to use user1/changeme it re-prompts authentication pop-up. could you please help me on this.

readonlyrest:
 enable: true
 response_if_req_forbidden: Access denied!!!

 access_control_rules:

-  name: "readonly user"
    auth_key: user1:changeme
    actions: ["indices:data/read/*"]
    indices: ["logstash-*"]

-  name: "ElasticSearch API and Kibana Authentication"
    auth_key: elastic:changeme
    #verbosity: error
    type: allow

Thanks,
Deepak

**Comment by sscarduzio** [comment]
if you see the Elasticsearch log, you can spot a lot of "FORBIDDEN" lines. That testifies that a Kibana session (I guess you are using Kibana)  entails many requests with many other actions, not simply some indices reads.

The correct way of allowing usage of Kibana is the "kibana_access" macro rule (which underpins a selected set of actions).

Please refer to the [documentation](https://github.com/beshu-tech/readonlyrest-docs/blob/master/elasticsearch.md#kibana_access-rule), and the [readme examples](https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin#use-case-multi-user-kibana--authenticated-logstash).
