### ISSUE TITLE
java exception when installing the plugin on windows from local zip file

### ISSUE THREAD

**Issue by hgc2002** [sscarduzio/elasticsearch-readonlyrest-plugin#337]
this always fails on windows:

`
elasticsearch-plugin install file://readonlyrest-1.16.18_es5.6.8.zip`

the plugin program always try to download the zip file, no matter it is already copied into local (current) folder.

the only way to install the plugin has been faking the download using a web server, so running like:

`elasticsearch-plugin install http://localhost:8000/readonlyrest-1.16.18_es5.6.8.zip`

and it worked perfectly.

**Comment by sscarduzio** [comment]
You need to use absolute paths to install locally. I remarked this in the docs:

https://github.com/beshu-tech/readonlyrest-docs/blob/master/elasticsearch.md#installing
