### ISSUE TITLE
DLS bug with .kibana index

### ISSUE THREAD

**Issue by seanziee** [sscarduzio/elasticsearch-readonlyrest-plugin#341]
Hi, 

Just testing out the DLS and I've run into a problem. If I create access control based off of a user using a filter to act as DLS, then that user cannot access it's own `.kibana` index. In my case, I create access control based off the filter `country:"Red"`. But when trying to create an index pattern or even access the index pattern that I've already created for that user, I get an error that there is a conflict. I was able to figure out that what probably is happening is the `.kibana` index doesn't have the field `country` and it definitely doesn't equal `red`, so it hides the results of the .kibana index.

Ideally the DLS doesn't apply to the .kibana indices. A work around is creating a group that the user will then have access to the kibana indices, but it's bulky and I think worth looking into.

**Comment by sscarduzio** [comment]
@seanziee please share your whole settings file, omitting the secrets of course.

**Comment by seanziee** [comment]
Sure thing, note that I'm using this with `Own_home` which is why I need to give permissions to `".kibana_@{X-Forwarded-User}",".kibana_public"`. Creating a separate group like this isn't a huge deal, but the problem is that for someone using DLS for the first time, they will enter `indices: ["events",".kibana"]` and then the filter, and be confused that they are getting an non obvious error in Kibana because they gave the permissions to that index and yet it's not working. The reason is because the filter is acting on the `.kibana` index also. Does that make sense?

readonlyrest:
  enable: true
  #ssl:
    #enable: true
    #keystore_file: "/elasticsearch/plugins/readonlyrest/keystore.jks"
    #keystore_pass: readonlyrest
    #key_pass: readonlyrest


  response_if_req_forbidden: Sorry, your request is forbidden.

  access_control_rules:
  - name: Admins
    type: allow
    groups: ["Admin"]
    indices: ["*"]

  - name: Basic Kibana Access
    type: allow
    kibana_access: ro
    indices: [".kibana_@{X-Forwarded-User}",".kibana_public"]
    groups: ["basicKibanaAccess"]
    # The filtering in the access control for each user type actually blocks the .kibana index also. So it's important that each user is in 2 groups, kibana access, and their own data access.
  
 - name: User1 login
    type: allow
    indices: ["events"]
    groups: ["user1group"]
    filter: "{\"bool\": {\"must\": [{\"term\": {\"user.keyword\": {\"value\": \"user1\"}}}]}}"
  
  - name: User 2 login
    type: allow
    indices: ["events"]
    groups: ["user2group"]
    filter: "{\"bool\": {\"must\": [{\"term\": {\"user.keyword\": {\"value\": \"user2\"}}}]}}"


  - name: "::KIBANA-SRV::"
    type: allow
    auth_key: kibana:kibana

  - name: "::LOGSTASH::"
    auth_key: logstash:logstash
    actions: ["cluster:monitor/main","indices:admin/types/exists","indices:data/read/*","indices:data/write/*","indices:admin/template/*","indices:admin/create"]
    indices: ["logstash-*"]

  users:
    #"username" has to be the same as the "proxy_auth"
  - username: admin
    proxy_auth: "admin"
    groups: ["Admin"]

  - username: user1
    proxy_auth: "user1"
    groups: ["user1group","basicKibanaAccess"]
  
  - username: user2
    proxy_auth: "user2"
    groups: ["user2group","basicKibanaAccess"]
```

**Comment by sscarduzio** [comment]
I think you must construct the "filter" string to allow ALSO the kibana index. But to do so, you need the dynamic variables in filter. Which is present in 1.16.20-pre3

**Comment by seanziee** [comment]
Can one define an index in a filter?

**Comment by sscarduzio** [comment]
Every document in ES has a "_index" field, you could use that.

**Comment by seanziee** [comment]
Ok, but maybe if a user defines `kibana_access` and filters, the kibana_access would override all the filters for .kibana* indices? It's more of a usability thing because once you know this is the problem, then finding a workaround isn't too bad. But the issue is if you commit this then it takes a long while to trace it back. Just an idea, if you're okay with how it's being run now then we can close this.

**Comment by sscarduzio** [comment]
How about using the expressiveness of the ACL logic and separate the two concerns (kibana usage and indices access) in two blocks.

```yml
- name: Kibana access alone
   auth_key: user1:pass
   indices: [".kibana"]
   kibana_access: ro

- name: data indices for user1 (read only because of filter)
   auth_key: user1:pass
   indices: ["logstash-*"]
   filter: "{\"bool\": {\"must\": [{\"term\": {\"user.keyword\": {\"value\": \"user1\"}}}]}}"
 
```
