### ISSUE TITLE
SAML and/or OAuth2 support

### ISSUE THREAD

**Issue by barryib** [sscarduzio/elasticsearch-readonlyrest-plugin#346]
Is SAML and/or OAuth2 support planned ?

**Comment by sscarduzio** [comment]
Yeah it's planned for ROR enterprise, after we publish field level security for ROR Free (the ES plugin)

**Comment by barryib** [comment]
Closing this. The feature is now available in ROR V1.16.27 Entreprise.

Thanks @sscarduzio for your work.

**Comment by sscarduzio** [comment]
Tell me if you are going to take it in use, need feedback :)
