### ISSUE TITLE
Handle delete_by_query using POST in ROR

### ISSUE THREAD

**Issue by sahil-sharma** [sscarduzio/elasticsearch-readonlyrest-plugin#348]
Greetings ReadOnlyREST,

I have a query. Let's assume I have assigned a user to the group where POST is defined as a method. And, if the user is firing _delete_by_query using POST request then the user is able to delete the indices. Logically, the user should not be able to delete but the user is using the POST as method hence he satisfies the logic.
Is there any way in ROR where we can restrict or handle such kind of requests? If such issues have already been addressed then please redirect me to that link else suggest us on this.

Reference: [https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-delete-by-query.html](url)

It would be of great learning to us.
Thanks!

**Comment by sahil-sharma** [comment]
Greetings @sscarduzio, 

Thanks for your reply. Yes, ES doesn't follow REST semantics correctly.
I did give a try to use actions for specific indices rather than assigning methods but it failed. Or I couldn't understand the solution suggested by you in a correct way.

And, [Action rule](https://github.com/beshu-tech/readonlyrest-docs/blob/master/elasticsearch.md#action-rule) are uniform API end-point to ES or it is just an example to illustrate. Just correct me on this as I am not clear on this.

Could you please share an example with us so that it would be easy for us to understand how can we leverage RoR functionality in a decent way?

**Comment by sscarduzio** [comment]
@sahil-sharma depends what's the requirement. Can you formalise it for me in a whitelist fashion? 
 i.e:
✅ The users can only search, ....
🚫The user should not be able to delete, ...

**Comment by sahil-sharma** [comment]
Let's have a user: Sam
And, Sam is having an access to CompanyA index but only in Read/Write (GET, POST) operations. But in any possible way, he should or cannot perform delete operation on CompanyA index.
Can we achieve such thing using RoR (indirectly bypassing delete_by_query method) though the user can do perform POST?
I hope it is clear now.
Thanks!

**Comment by sscarduzio** [comment]
how about:
```yml
 - name: Sam
    auth_key: sam:pass
    actions: ["indices:data/read/*", "indices:data/write/*", "indices:admin/mappings/fields/get", "indices:admin/mappings/get", "indices:admin/create"]
```

Try and see, if there is some "FORBIDDEN" log line, just see the "ACT" field and consider adding that action name to the list.

**Comment by sahil-sharma** [comment]
Hi @sscarduzio 
Thanks for the solution you suggested. I tried this but it didn't work. Let me explain my steps:
Indices: company1 and company2 (having some random data)
My readonlyrest.yml
`
readonlyrest:
  enable: true
  response_if_req_forbidden: Forbidden by Ops Team!!!

  access_control_rules:
    - name: Read/Write to all the Indices but can't delete
      type: allow
      methods: ["GET"]
      indices: ["company1", "company2"]
      groups: ["appadmin"]
      verbosity: error

    - name: Read/Write/Delete to all the Indices
      type: allow
      methods: ["GET", "POST", "PUT", "DELETE"]
      indices: ["company1", "company2"]
      actions: ["cluster:monitor/state"]
      groups: ["superadmin"]
      verbosity: error

    - name: No access to cluster
      type: forbid
      groups: ["outsider"]
      verbosity: info

    - name: Sam delete by query
      auth_key: sam:demo
      actions: ["indices:data/read/*", "indices:data/write/*", "indices:admin/mappings/fields/get", "indices:admin/mappings/get", "indices:admin/create","indices:admin/get", "cluster:monitor/state"]

  users:
    - username: keith
      auth_key: keith:demo
      groups: ["appadmin"]

    - username: adam
      auth_key: adam:demo
      groups: ["superadmin"]

    - username: bob
      auth_key: bob:demo
      groups: ["outsider"]
`
My queries:
* Sam is able to see the both the indices when making a GET request. Maybe because of {"cluster:monitor/state"}. If yes then if we remove this from actions then sam is not able to make a GET request even. Ideally he should view company1 index.
* Sam is able to add data in company1 index as well as in company2 index which we want to restrict.
* Sam is able to fire delete_by_query on company1 index and can easily delete the index which we don't want
Please suggest how can we achieve this.
One silly question:
Action rules are indices:admin/create and other related options are elasticsearch specific or RoR.
Thanks in advance!

**Comment by sscarduzio** [comment]
Hi @sahil-sharma 
1. where in your settings did you specify sam has access only to company1? Maybe you forgot to add the indices rule for sam?

2. You told me sam should be able to read and write, that's why I suggested you that set of actions

3. Can you paste the ES log line that shows the allowed delete by query? I.e. tail ES logs, send a delete by query and read that "ALLOWED" log line.

**Comment by sahil-sharma** [comment]
Hi @sscarduzio ,
My apologies for not adding that indices for sam user. After adding sam is not able to view company2 index while firing GET query.
` - name: Sam delete by query
      auth_key: sam:demo
      indices: ["company1"]
      actions: ["indices:data/read/*", "indices:data/write/*", "indices:admin/mappings/fields/get", "indices:admin/mappings/get", "indices:admin/create","indices:admin/get", "cluster:monitor/state"]`

But, it is OK for sam to add content in company1 index but he should not delete the content in company1 while executing delete_by_query method which he is able to do.
Below are the snapshots of the commands:
delete_by_query:
![delete_sam](https://user-images.githubusercontent.com/5774379/39694524-3f7f3836-5205-11e8-980b-01bc8abf46f3.png)
ES_Logs:
![es_logs](https://user-images.githubusercontent.com/5774379/39694534-459cc8fa-5205-11e8-8bda-b454f830fc95.png)
Please highlight where we are wrong and what are we doing wrong.
Thanks!

**Comment by sscarduzio** [comment]
OK here's the problem. The delete by query action is  `indices:data/write/delete/byquery` so it gets allowed by our "indices:data/write/*" wildcard. 

There is two solutions to this:

1. Expand the wildcard, leaving delete/byquery off.
```yml
actions: ["indices:data/read/*",  "indices:data/write/bulk*", "indices:data/write/index*", "indices:data/write/update*", "indices:admin/mappings/fields/get", "indices:admin/mappings/get", "indices:admin/create","indices:admin/get", "cluster:monitor/state"]
```

2. Create a forbid block ABOVE the current "sam" block:
```yml
    - name: Sam forbid all delete
      auth_key: sam:demo
      type: forbid
      actions: ["*delete*"]

    - name: Sam delete by query
      auth_key: sam:demo
      actions: ["indices:data/read/*", "indices:data/write/*", "indices:admin/mappings/fields/get", "indices:admin/mappings/get", "indices:admin/create","indices:admin/get", "cluster:monitor/state"]

```

**Comment by sahil-sharma** [comment]
@sscarduzio ,
Thank you for your instant response.
I assume the second method is more relevant and easy to locate what permissions are forbidden for this user.  Just a random doubt that in second method we are defining two actions for the same user but ACL's works in a sequential way. Does it ruin any functionality?
And, is there any documentation for the [Action Rules](https://github.com/beshu-tech/readonlyrest-docs/blob/master/elasticsearch.md#action-rule) to have a better understanding how we can use them more efficiently?
Thanks!

**Comment by sscarduzio** [comment]
@sahil-sharma being able to split logic in two blocks is exactly why the ACL model is better than a declarative configuration file. No extra constructs to learn when things are a bit more complex.

Actions name seem mysterious, but once you learn to analyse the "ACT" (action) and "HIS" (ACL evaluation history) fields in the ES logs, you just add rules by trial and error.
I.e Keep an eye when you see a "FORBIDDEN" line in the logs, see what the user was trying to do by observing method, path, and action name. Then add an extra action to your ACL block if you need to.

**Comment by sahil-sharma** [comment]
@sscarduzio ,
Thank you so much for explaining it. It will really help us. I am trying multiple use-cases and will reach out to you in case I need some guidance from you. For now, I am closing this.
Thank you once again!
