### ISSUE TITLE
Ability to load keystore password and key password from different source

### ISSUE THREAD

**Issue by The-Yoda** [sscarduzio/elasticsearch-readonlyrest-plugin#355]
Right now, the keystore and key password is hardcoded in config file, which is not secure.

There need to be a way for users to define their own class to fetch the details either from elasticsearch keystore(from 6.x).

This would be similar to custom AuditlogSerializer.

**Comment by sscarduzio** [comment]
Hi @The-Yoda could you take AuditLogSerializer as an example and create a PR? Super busy with other features right now.

**Comment by The-Yoda** [comment]
Will take it up this weekend.
