### ISSUE TITLE
Indices with wildcards

### ISSUE THREAD

**Issue by danielmotaleite** [sscarduzio/elasticsearch-readonlyrest-plugin#36]
Trying to limit the access to the indices, i build this config:

```
    - name: Accept oms user
      type: allow
      methods: [GET,POST,HEAD]
      auth_key: user:pass
      indices: [logstash-*-live-*,.kibana]
      kibana_access: ro
```
This way, the user will be able to check the live logs, but not the other ones
trying to login it works, but then it start to ask for auth and the log reports that the 
index `logstash-2016.03.31-live-web` in not in the list.

So looks like the indices filter is not applying the wildcards, just doing literal match.
i tried substring - `indices: [live,.kibana]` - but it also didn't work. Is this a bug or i'm doing it wrongly? What is the correct way to do this?

Thanks!

**Comment by sscarduzio** [comment]
Yup, this should be easy and adds a lot of value. Thanks for coming up with it :+1:

**Comment by danielmotaleite** [comment]
Thank you too for the plugin and the amazing support! :smiley:
