### ISSUE TITLE
Limiting access by term

### ISSUE THREAD

**Issue by itles** [sscarduzio/elasticsearch-readonlyrest-plugin#360]
Hello,
is it possible limit access to ES data by term?
E.g.:
We allow access for tomcat-* and jboss-* indices. Futhermore we can limit access on this indices by term: 

```
{
  "indices" : [
    {
      "names" : [ "jboss-*", "tomcat-*" ],
      "query" : {
        "term" : { "app" : "app-only-for-this-group" }
      }
    }
  ]
}
```

Is this possible and which **syntax** I should use?

**Comment by sscarduzio** [comment]
this depends from FLS (field level security) which is coming out soon.

**Comment by coutoPL** [comment]
it's documented here: https://github.com/beshu-tech/readonlyrest-docs/blob/master/elasticsearch.md#fields
