### ISSUE TITLE
UI Failure caused by kibana_hide_apps: ["dev_tools"]

### ISSUE THREAD

**Issue by bradvido** [sscarduzio/elasticsearch-readonlyrest-plugin#364]
Using version 6.2.4:

adding `kibana_hide_apps: ["dev_tools"]` to the config causes the nav bar to look odd:
![image](https://user-images.githubusercontent.com/884611/40495934-20e206b0-5f3e-11e8-84ca-3f684aaf4766.png)

It also breaks kibana because clicking on any of the enabled apps changes the url but then shows nothing in the content panel (no errors in JS console either):
![image](https://user-images.githubusercontent.com/884611/40496028-61416b1a-5f3e-11e8-83ee-f7f50d5a63b3.png)

**Comment by sscarduzio** [comment]
Hi @bradvido!
It should be "kibana:dev_tools" not "dev_tools"

**Comment by sscarduzio** [comment]
you are doing it right, see the URL. Just keep in mind that sometimes it's  just "app" and sometimes "app:sub_app"

**Comment by bradvido** [comment]
thanks, this fixed my issue and can be closed
