### ISSUE TITLE
Custom index pattern for readonlyrest_audit-*

### ISSUE THREAD

**Issue by bradvido** [sscarduzio/elasticsearch-readonlyrest-plugin#366]
Instead of the default `readonlyrest_audit-YYYY-MM-DD`, we'd like to use a monthly pattern because we don't have so many requests that the index needs to roll daily. 

Is there any way to do this via a configuration parameter?

**Comment by sscarduzio** [comment]
hello @bradvido yes there is! Starting with ROR 1.16.20 (will soon released)

See this: https://forum.readonlyrest.com/t/set-readonlyrest-audit-index/398/8?u=sscarduzio

**Comment by bradvido** [comment]
awesome, thanks. I'll try it when it's released

**Comment by bradvido** [comment]
Was this feature released in 1.16.20?
I have 1.16.20 of ROR Elasticsearch and  Kibana Pro installed, with this config line:
`audit_index_template: "'readonlyrest_audit'-yyyy-mm" `
But still, it is creating daily indices instead of monthly.

**Comment by HagK** [comment]
Hi Brady, 

your 'template' defines indices  one per minute  ... 60 per year 

the java dateTime abbreviation differs from unix-style   use uppercase 
MM  for months 

# DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

regards 

Hagen 

Am 2018-06-12 16:05, schrieb Brady Vidovic:

> Was this feature released in 1.16.20?
> I have 1.16.20 of ROR Elasticsearch and Kibana Pro installed, with this config line:
> audit_index_template: "'readonlyrest_audit'-yyyy-mm"
> But still, it is creating daily indices instead of monthly.
