### ISSUE TITLE
Anonymous read only access - admin access after providing login & pass

### ISSUE THREAD

**Issue by CPS86** [sscarduzio/elasticsearch-readonlyrest-plugin#37]
Hi Simone,

I've downloaded your read-only rest plugin for elasticsearch.
Good that finally someone implemented so awesome thing. Good job!
 
Is it possible to set up your plugin as following:
- Anonymous users will have only read-only access, they cannot save/modify anything. However they can search for data (Discover tab in Kibana), they can open dashboards as well in read only mode. 
- Other users who provide Login & Password, will have save/modify permissions as well.
 
Thanks in advance.

**Comment by sscarduzio** [comment]
Hello @CPS86, thanks, I'm glad this thing is being useful! And please don't hesitate to make it more useful by proposing new features or ideas for better documentation :rocket: 

For your first and second questions: absolutely yes!
It's still undocumented (will do that during the weekend), please refer to these provisional instructions:

https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/issues/31#issuecomment-203482758

What ES version are you using? I can make a build for you if necessary.

**Comment by CPS86** [comment]
Hi thanks for reply. I have already posted my msg in #31 issue. 

I think my is redundant now. 😊

**Comment by sscarduzio** [comment]
All right, mate. Closing this one.
