### ISSUE TITLE
es62x doesn't exist

### ISSUE THREAD

**Issue by markxtji** [sscarduzio/elasticsearch-readonlyrest-plugin#371]
Hi @sscarduzio ,

why the folder ex62x doesn't exist ?
and the building of ex62x will go to ex61x directory, this is quite confusing.

**Comment by sscarduzio** [comment]
hi @markxtji,
it works like this: as long as it's possible to build from the old code base, we don't create a separate sub project.

In this case 6.2.x plugins can be built from the same code base of 6.1.x, therefore we don't need to duplicate that code.

Instead when the changes are too big, we need to create a new gradle subproject.
