### ISSUE TITLE
External authentication

### ISSUE THREAD

**Issue by Sneijky** [sscarduzio/elasticsearch-readonlyrest-plugin#374]
Hello,

I'm trying to use JIRA api to authenticate with external authentication.
JIRA api uses Authentication : basic <base64 email:password>, therefore I think it should be possible to use it to external authentication.

The request I'm using below returns code 200 if the authentication is valid.

I have the following problem:
- Kibana credentials pop-up
- Enter JIRA credentials and kibana loads
- Once kibana is loaded credentials pop-up keeps poping and can't access using the JIRA credentials, only kibana:kibana work.

What in trying to do is that after entering the JIRA credentials the user can have normal access to Kibana.

Would appreciate any help
My configuration:
`readonlyrest:

    ssl:
      enable: true
      keystore_file: "/elasticsearch/plugins/readonlyrest/keystore.jks"
      keystore_pass: readonlyrest
      key_pass: readonlyrest

    response_if_req_forbidden: Forbidden by ReadonlyREST ES plugin

    access_control_rules:

    # We trust Kibana's server side process, full access granted via HTTP authentication
    - name: "::KIBANA-SRV::"
      # auth_key is good for testing, but replace it with `auth_key_sha256`!
      auth_key: kibana:kibana
      verbosity: error # don't log successful request

    - name: Accept requests from users with valid JIRA credentials
      methods: GET
      external_authentication: "ext1"

    external_authentication_service_configs:

    - name: "ext1"
      authentication_endpoint: "my_jira/rest/auth/1/session"
      success_status_code: 200
`

**Comment by sscarduzio** [comment]
I see a wrong authentication endpoint, it should be a full URI
As per documentation:
```
      authentication_endpoint: "http://external-website1:8080/auth1"
```
