### ISSUE TITLE
ACL after deploying to openshift

### ISSUE THREAD

**Issue by markxtji** [sscarduzio/elasticsearch-readonlyrest-plugin#375]
Hi @sscarduzio ,

this is a question rather than an issue.
I setup the rules like the following :

`

readonlyrest:

    access_control_rules: 

    - name: "Accept all requests from localhost and Drupal"

      hosts: ["nginx-php","elasticsearch","cli","localhost"]

    - name: "Everything else can only query the index."

      indices: ["*"]

      actions: ["indices:data/read/*","cluster:monitor/health"]

`
what I want to archive is : 
- accept all all  from localhost and services in the same project
- the others will only have readonly access.

it is running fine on my Mac, because the hostname equal to the service name I defined in my docker compose file.
But after deploying to openshift, the hostnames  will change to be the pod names which are  dynamic for every deployment.  So the first rule will not work as expected.

Is there any method to implement the rules to archive what I want ?
thank you.

**Comment by markxtji** [comment]
or is there any method to use environment variables in readonlyrest.yml?

**Comment by sscarduzio** [comment]
yes there is, have you seen the official documentation?

https://github.com/beshu-tech/readonlyrest-docs/blob/master/elasticsearch.md#environmental-variables
