### ISSUE TITLE
Unable to use http external authentication in readOnlyRest : It says no basic auth header

### ISSUE THREAD

**Issue by priyansha2609** [sscarduzio/elasticsearch-readonlyrest-plugin#377]
My elastic search is hosted on sharmpri-dev.nyc.abc.com:9200 and readonly rest config looks like this 

 - name: Just certain indices, and read only
      indices: ["consultation*"] # index aliases are taken in account!
      methods: GET
      indices: ["consultation_workflow"]
      external_authentication: "ext1"

    external_authentication_service_configs:

    - name: "ext1"
      authentication_endpoint: "https://www.google.com"
      success_status_code : 200
      cache_ttl_insec: 6

When i hit the elastic search simply from browser i get the below error.
I am not sure if i need to make a change in elastic search config to be able to accept authorization headers.
As per the below error it seems the auth header is not being passed to read only rest.

FORBIDDEN by default req={ ID:482062665-1229073679#49, TYP:GetRequest, CGR:N/A, USR:[no basic auth header], BRS:true, KDX:null, ACT:indices:data/read/get, OA:10.13.42.11, DA:10.219.25.227, IDX:consultation_workflow, MET:GET, PTH:/consultation_workflow/consultation/1, CNT:<N/A>, HDR:{Accept=text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8, Accept-Encoding=gzip, deflate, Accept-Language=en-US,en;q=0.9, Cache-Control=max-age=0, Connection=keep-alive, content-length=0, Host=sharmpri-dev.nyc.deshaw.com:9200, Upgrade-Insecure-Requests=1, User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36}, HIS:[Just certain indices, and read only->[external_authentication->false]] }

**Comment by sscarduzio** [comment]
because there is no credentials. You have to have credentials before you use external auth.
