### ISSUE TITLE
Supporting elasticsearch 6.3.1

### ISSUE THREAD

**Issue by noghte** [sscarduzio/elasticsearch-readonlyrest-plugin#378]
I see your last commit message says elasticsearch 6.3.1 is supported, but the official website seems not updated.
Is there any guide to unofficially build the plugin? Or download the binaries from somewhere else?

**Comment by sscarduzio** [comment]
Hi @noghte! I'm about to release 1.16.22 with important fixes and 6.3.1 support.
Of course you can always build it for yourself. It's open source! Look inside bin/build.sh and pick your command :)

**Comment by sscarduzio** [comment]
released
