### ISSUE TITLE
log spam

### ISSUE THREAD

**Issue by danielmotaleite** [sscarduzio/elasticsearch-readonlyrest-plugin#38]
In my syslog i'm receiving a lot of events like this:
Apr  1 14:40:16 ES1 elasticsearch[14690]: KIBANA ACCESS DENIED {action: indices:data/write/bulk[s] OA:/192.168.0.10:42842 M: POST <not available>
Apr  1 14:40:16 ES1 elasticsearch[14690]: KIBANA ACCESS DENIED {action: indices:data/write/bulk[s] OA:/192.168.0.10:42842 M: POST <not available>
Apr  1 14:40:16 ES1 elasticsearch[14690]: KIBANA ACCESS DENIED {action: indices:data/write/bulk[s] OA:/192.168.0.10:42842 M: POST <not available>

i assume that are the topbeat causing this, but they have their own auth and config to be accepted... so i don't understand where this is coming, nor how to fix this (or reduce this event to DEBUG if not important). I'm currently logging INFO in the ES.

**Comment by sscarduzio** [comment]
Well spotted, it’s a shitty printf to stdout I accidentally committed to the testing build I packaged for you. 
You won’t see that in the official plugin version.

**Comment by danielmotaleite** [comment]
Perfect! thanks!
