### ISSUE TITLE
Found an instance of CompositeIndicesRequest that could not be handled

### ISSUE THREAD

**Issue by andreapalaia** [sscarduzio/elasticsearch-readonlyrest-plugin#393]
I got this error while re-indexing and I am reporting it as requested.

> [ERROR][t.b.r.e.RequestInfo      ] Found an instance of CompositeIndicesRequest that could not be handled: report this as a bug immediately! ReindexRequest

This happened with elasticsearch 6.4 + readonlyrest 1.16.26

Irrespective of this error, I am forbidden to re-index any index by the following forbid rule
```
    - name: My forbid rule
      type: forbid
      groups: ["devs"]
      indices: ["very_special_index"]
      actions: ["indices:data/*", "indices:admin/delete"]
```
even if the index I am trying to re-index is not the one specified in the rule. Can the two issues be related?

**Comment by sscarduzio** [comment]
Hey @andreapalaia thanks for reporting this, can you show the log line that says "FORBIDDEN" corresonding to  this ReindexRequest?

**Comment by sscarduzio** [comment]
BTW, I found the issue with the log. It was a false positive. Thanks :-)

**Comment by andreapalaia** [comment]
Hey @sscarduzio glad to hear that is was a false positive!

Here is the log entry that corresponds to this index request:

`FORBIDDEN by { name: 'My forbid rule', policy: FORBID, rules: [groups, indices, actions]} req={ ID:738562901-1073597961#344, TYP:ReindexRequest, CGR:N/A, USR:test-user, BRS:false, KDX:null, ACT:indices:data/write/reindex, OA:127.0.0.1, DA:127.0.0.1, IDX:very_special_index, MET:POST, PTH:/_reindex, CNT:<OMITTED, LENGTH=94>, HDR:{authorization=<OMITTED>, content-length=94, x-forwarded-host=kibana.staging, x-forwarded-proto=http, Connection=close, x-forwarded-port=33994, content-type=application/json, Host=localhost:9200, x-forwarded-for=127.0.0.1}, HIS:[user-a->[auth_key_sha256->false]], [user-b->[auth_key_sha256->false]], [user-c->[auth_key_sha256->false]], [user-d->[auth_key_sha256->false]], [::KIBANA-SRV::->[auth_key_sha256->false]], [My forbid rule->[indices->true, auth_key_sha256->true, actions->true]] }`

What is not clear to me is is why I got forbidden for a ReindexRequest on an index that is the one in the log. Any input is appreciated :)

**Comment by sscarduzio** [comment]
@andreapalaia well, as you can see in the log line you pasted, all rules in the forbid block match. Including the indices rule, as the discovered target index of the request is "very_special_index". You can see this where the log says `IDX:very_special_index`.

What were you trying to reindex?

**Comment by andreapalaia** [comment]
@sscarduzio the log line is indeed detailed and clear. It corresponds though to a ReindexRequest of  index_1 into index_2

`curl -X POST "localhost:9200/_reindex" -H 'Content-Type: application/json' -d'{"source":{"index":"index_1"},"dest":"index":"index_2"}}'

which has nothing to do with the "very_special_index" in the log.

**Comment by sscarduzio** [comment]
damn, that's very weird. Can you reproduce this reliably? How can I reproduce it?

**Comment by coutoPL** [comment]
fixed here:
https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/pull/455
