### ISSUE TITLE
 [ES 6.4.0][RR 1.16.29] Kibana Canvas Plugin

### ISSUE THREAD

**Issue by juelian** [sscarduzio/elasticsearch-readonlyrest-plugin#395]
Hi,

i got this error when trying to use the Kibana Plugin Canvas:

`[2018-11-19T11:31:19,559][ERROR][t.b.r.e.RequestInfo      ] Found an instance of CompositeIndicesRequest that could not be handled: report this as a bug immediately! SqlQueryRequest`

`[2018-11-19T11:31:19,559][INFO ][t.b.r.a.ACL              ] [35mFORBIDDEN by default req={ ID:806859363--101845525#3219, TYP:SqlQueryRequest, CGR:N/A, USR:[no basic auth header], BRS:false, KDX:null, ACT:indices:data/read/sql, OA:192.168.73.27, DA:192.168.73.156, IDX:, MET:POST, PTH:/_xpack/sql?format=json, CNT:<OMITTED, LENGTH=199>, HDR:{authorization=<OMITTED>, x-forwarded-user=robot, Connection=keep-alive, host=localhost:5601, content-type=application/json, Content-Length=199}, HIS:[::Robot::->[auth_key_sha256->false]], [::Kibana server::->[auth_key_sha256->false]], [admin->[proxy_auth->false]], [display->[proxy_auth->false]], [userX->[proxy_auth->false]], [recruiting->[proxy_auth->false]] } [0m`

**Comment by sscarduzio** [comment]
Thank you for reporting this, This is a X-Pack class, that's why it remained outside of the radar. Will try to include it.

**Comment by coutoPL** [comment]
ES SQL is supported by ROR since 1.18.8 :)
