### ISSUE TITLE
Compatibility Issues with Kibana 3.0.0

### ISSUE THREAD

**Issue by jd4man** [sscarduzio/elasticsearch-readonlyrest-plugin#4]
Kibana 3.0.0 makes requests to elastic search from within the browser, so I can't find a way to whitelist all the requests made by Kibana using only the tools given by this plugin. I want Kibana to be able to function properly (using POST and GET methods), but still limit access to the rest API in the normal way. 

The only way that I've been able to get around this is by whitelisting the IP of my machine, which for use by an entire organization, does not scale well. Is there a way that I could isolate requests from Kibana specifically by request URL? As of right now, I can't find a way.

**Comment by sscarduzio** [comment]
I guess you solved this, didn't you?

**Comment by sscarduzio** [comment]
closing this, I guess you've found your way.
