### ISSUE TITLE
Cookbook style documentation

### ISSUE THREAD

**Issue by sscarduzio** [sscarduzio/elasticsearch-readonlyrest-plugin#40]
Write a series of wiki pages to show off various use cases, their description and their solution.
Link the recipes in the main README.md (which needs to be much smaller).

**Comment by Shifter2600** [comment]
@sscarduzio 
I can help with some of this.

**Comment by sscarduzio** [comment]
Awesome @Shifter2600! Sent you an email with some specs

**Comment by ld57** [comment]
I m up to help too, but do not know what is the cookbook style. any direction to see an example ?

**Comment by sscarduzio** [comment]
Yay, more volunteers! 

Basic guide lines about what I mean with cookbook style:

## Structure
* Title = description of the end result
* Brief intro about what real business case are you solving with this solution
* Present the shiny final result (screenshot helps)
* List the ingredients: software versions used, state if the reader needs anything specific (i.e. a cookbook about Letsencrypt SSL would need a public IP).
* Step by step instructions until the final result. If it's long, break the list down into phases using nested headings: i.e. 
```md
## Download and install the plugin", "Configure Kibana", etc.
bla bla
### Downloading the plugin for your version
bla bla
### Installing the plugin
bla bla
```

### General Tips
-  People love copy-paste code snippets and screenshots. Use the triple-backticks + language name to have nice looking snippets
i.e.
```bash
$ ls $ES_HOME
```
And for Yaml too:

```yaml
readonlyrest:
    enable: true
    ssl:
      enable: true
```
- Use the project's wiki to compose a document in Github flavored markdown. I have a templating system that mocks 100% GH markdown, it's going to look great!

**Comment by ld57** [comment]
okay , good way. I will build one.

Ld
