### ISSUE TITLE
when objectClass=posixGroup, can't get user groups.

### ISSUE THREAD

**Issue by kingmorning** [sscarduzio/elasticsearch-readonlyrest-plugin#402]
Hi, i use this plugin to connect LDAP, 
In our LDAP, i can get user info by uid, but can not get user groups.(objectClass=posixGroup . not groupOfNames)
I checked the source code, and find. 
`   String searchString = String.format(
        "(&%s(%s=%s))",
        userGroupsSearchFilterConfig.getGroupSearchFilter(),
        userGroupsSearchFilterConfig.getUniqueMemberAttribute(),
        Filter.encodeValue(user.getDN())
    );`
user.getDN() has too many things, we just need a uid.
so i changed this code , just use user.getUid() in the searchString, and got the groups success.

I think maybe the searchString should be build by objectClass.

**Comment by sscarduzio** [comment]
@coutoPL  any comments on this?

**Comment by coutoPL** [comment]
We plan to reimpIement LDAP rules in a moment. I'll take this into consideration.

**Comment by Vebryn** [comment]
Related to #300 and #478
