### ISSUE TITLE
Your project sscarduzio/elasticsearch-readonlyrest-plugin is using buggy third-party libraries [WARNING]

### ISSUE THREAD

**Issue by FDU-SE-LAB** [sscarduzio/elasticsearch-readonlyrest-plugin#404]
Hi, there!
We are a research team working on third-party library analysis. We have found that some widely-used third-party libraries in your project have major/critical bugs, which will degrade the quality of your project. We highly recommend you to update those libraries to new versions.    
We have attached the buggy third-party libraries and corresponding jira issue links below for you to have more detailed information.
  1  org.apache.logging.log4j log4j-core (tests-utils/build.gradle)
  version: 2.11.1

  Jira issues:
  NameAbbreviator skips first fragments
  affectsVersions:2.11.0,2.11.1
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2365?filter=allopenissues
  Predeployment of PersistenceUnit that using Log4j as session logger failed (#198)
  affectsVersions:2.11.1
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2397?filter=allopenissues
  Exceptions are added to all columns when a JDBC Appender's ColumnMapping uses a Pattern
  affectsVersions:2.11.1
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2413?filter=allopenissues
  NullPointerException when closing never used RollingRandomAccessFileAppender
  affectsVersions:2.10.0,2.11.1
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2418?filter=allopenissues
  AbstractAppender.setHandler(null) should not set a null ErrorHandler
  affectsVersions:3.0.0,2.11.1
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2441?filter=allopenissues
  ErrorHandler should be invoked with the failing LogEvent when possible
  affectsVersions:3.0.0,2.11.1
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2444?filter=allopenissues
  RollingRandomAccessFileManager ignores new file patterns from programmatic reconfiguration
  affectsVersions:2.11.1
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2457?filter=allopenissues
  ColumnMapping literal not working
  affectsVersions:2.11.1
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2466?filter=allopenissues
  org.apache.log4j.SimpleLayout and ConsoleAppender missing in log4j-1.2-api
  affectsVersions:2.11.1
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2476?filter=allopenissues
  BasicContextSelector cannot be used in a OSGI application
  affectsVersions:2.11.1
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2482?filter=allopenissues

  2  org.apache.httpcomponents httpclient (tests-utils/build.gradle)
  version: 4.5.2

  Jira issues:
  org.apache.http.impl.client.AbstractHttpClient#createClientConnectionManager Does not account for context class loader
  affectsVersions:4.4.1;4.5;4.5.1;4.5.2
  https://issues.apache.org/jira/projects/HTTPCLIENT/issues/HTTPCLIENT-1727?filter=allopenissues
  Memory Leak in OSGi support
  affectsVersions:4.4.1;4.5.2
  https://issues.apache.org/jira/projects/HTTPCLIENT/issues/HTTPCLIENT-1749?filter=allopenissues
  SystemDefaultRoutePlanner: Possible null pointer dereference
  affectsVersions:4.5.2
  https://issues.apache.org/jira/projects/HTTPCLIENT/issues/HTTPCLIENT-1766?filter=allopenissues
  Null pointer dereference in EofSensorInputStream and ResponseEntityProxy
  affectsVersions:4.5.2
  https://issues.apache.org/jira/projects/HTTPCLIENT/issues/HTTPCLIENT-1767?filter=allopenissues
  [OSGi] WeakList needs to support "clear" method
  affectsVersions:4.5.2;5.0 Alpha1
  https://issues.apache.org/jira/projects/HTTPCLIENT/issues/HTTPCLIENT-1772?filter=allopenissues
  [OSGi] HttpProxyConfigurationActivator does not unregister HttpClientBuilderFactory
  affectsVersions:4.5.2
  https://issues.apache.org/jira/projects/HTTPCLIENT/issues/HTTPCLIENT-1773?filter=allopenissues
  Why is Retry around Redirect and not the other way round
  affectsVersions:4.5.2
  https://issues.apache.org/jira/projects/HTTPCLIENT/issues/HTTPCLIENT-1800?filter=allopenissues

  3  commons-io commons-io (tests-utils/build.gradle)
  version: 2.6

  Jira issues:
  .gitattributes not correctly applied
  affectsVersions:2.6
  https://issues.apache.org/jira/projects/IO/issues/IO-516?filter=allopenissues
  FilenameUtils.normalize should verify hostname syntax in UNC path
  affectsVersions:2.6
  https://issues.apache.org/jira/projects/IO/issues/IO-559?filter=allopenissues
  Missing Javadoc in FilenameUtils causing Travis-CI build to fail
  affectsVersions:2.6
  https://issues.apache.org/jira/projects/IO/issues/IO-570?filter=allopenissues

  4  commons-codec commons-codec (core/build.gradle)
  version: 1.10

  Jira issues:
  Bug in HW rule in Soundex
  affectsVersions:1.10
  https://issues.apache.org/jira/projects/CODEC/issues/CODEC-199?filter=allopenissues
  Charsets Javadoc breaks build when using Java 8
  affectsVersions:1.10
  https://issues.apache.org/jira/projects/CODEC/issues/CODEC-207?filter=allopenissues
  Javadoc for SHA-224 DigestUtils methods should mention Java 1.8.0 restriction instead of 1.4.0
  affectsVersions:1.10
  https://issues.apache.org/jira/projects/CODEC/issues/CODEC-209?filter=allopenissues
  Don't deprecate Charsets Charset constants in favor of Java 7's java.nio.charset.StandardCharsets
  affectsVersions:1.10
  https://issues.apache.org/jira/projects/CODEC/issues/CODEC-219?filter=allopenissues
  HmacUtils.updateHmac calls reset() unnecessarily
  affectsVersions:1.10
  https://issues.apache.org/jira/projects/CODEC/issues/CODEC-221?filter=allopenissues
  InputStream not closed
  affectsVersions:1.10;1.11
  https://issues.apache.org/jira/projects/CODEC/issues/CODEC-225?filter=allopenissues
  StringUtils.newStringxxx(null) should return null; not NPE
  affectsVersions:1.10
  https://issues.apache.org/jira/projects/CODEC/issues/CODEC-229?filter=allopenissues
  URLCodec.WWW_FORM_URL should be private
  affectsVersions:1.10
  https://issues.apache.org/jira/projects/CODEC/issues/CODEC-230?filter=allopenissues
  StringUtils.equals(CharSequence cs1; CharSequence cs2) can fail with String Index OBE
  affectsVersions:1.10
  https://issues.apache.org/jira/projects/CODEC/issues/CODEC-231?filter=allopenissues
  URLCodec is neither immutable nor threadsafe
  affectsVersions:1.10
  https://issues.apache.org/jira/projects/CODEC/issues/CODEC-232?filter=allopenissues

  5  org.apache.logging.log4j log4j-core (commons/build.gradle,core/build.gradle)
  version: 2.9.0

  Jira issues:
  Test classes do not close resources and use deprecated methods
  affectsVersions:2.9.0
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-1997?filter=allopenissues
  Marker examples should not use deprecate flow APIs
  affectsVersions:2.9.0
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2029?filter=allopenissues
  ClassCastException: org.apache.logging.log4j.simple.SimpleLoggerContext cannot be cast to org.apache.logging.log4j.core.LoggerContext
  affectsVersions:2.9.0
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2030?filter=allopenissues
  Messages appear out of order in log file (was: Log4j2 log file not reflecting application log function calls)
  affectsVersions:2.8.2;2.9.0;2.9.1
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2031?filter=allopenissues
  Curly braces in parameters are treated as placeholders
  affectsVersions:2.8.2;2.9.0;2.10.0
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2032?filter=allopenissues
  Regression in ProviderUtil.hasProviders for 2.9.0
  affectsVersions:2.9.0
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2033?filter=allopenissues
  Update Apache Kafka Client from 0.11.0.0 to 0.11.0.1
  affectsVersions:2.9.0
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2049?filter=allopenissues
  NullPointerException in LogManager.getLogger when called from anonymous class initializer
  affectsVersions:2.9.0
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2050?filter=allopenissues
  Log4j-config.xsd should make AppenderRef optional for each Logger element
  affectsVersions:2.9.0;2.9.1
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2073?filter=allopenissues
  Configuration builder classes should look for "onMismatch"; not "onMisMatch".
  affectsVersions:2.4;2.4.1;2.5;2.6;2.6.1;2.6.2;2.7;2.8;2.8.1;2.8.2;2.9.0;2.10.0
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2219?filter=allopenissues
  fix the CacheEntry map in ThrowableProxy#toExtendedStackTrace to be put and gotten with same key
  affectsVersions:2.6.2;2.7;2.8;2.8.1;2.8.2;2.9.0;2.9.1;2.10.0;2.11.0
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2389?filter=allopenissues

  6  commons-lang commons-lang (tests-utils/build.gradle)
  version: 2.6

  Jira issues:
  Remove unnecessary synchronization from registry lookup in EqualsBuilder and HashCodeBuilder
  affectsVersions:2.6
  https://issues.apache.org/jira/projects/LANG/issues/LANG-1230?filter=allopenissues
  LocaleUtils - DCL idiom is not thread-safe
  affectsVersions:2.6
  https://issues.apache.org/jira/projects/LANG/issues/LANG-803?filter=allopenissues
  Exception when combining custom and choice format in ExtendedMessageFormat
  affectsVersions:2.5;2.6
  https://issues.apache.org/jira/projects/LANG/issues/LANG-917?filter=allopenissues

Sincerely~
FDU Software Engineering Lab
Jan 7th,2019

**Comment by sscarduzio** [comment]
Hi, thanks. I only will update the dependencies of non-test packages.

**Comment by sscarduzio** [comment]
Hi, thanks. I only will update the dependencies of non-test packages.
