### ISSUE TITLE
Need internode_ssl (transport layer ssl) to work

### ISSUE THREAD

**Issue by hq-mot** [sscarduzio/elasticsearch-readonlyrest-plugin#406]
Hi Simone,
Can I know when the transport layer internode communication changes be merged in to master?
Can I expect it to be built into readonlyrest plugin very soon or for this month (Februrary 2019)?
Thank you very much.

**Comment by sscarduzio** [comment]
working on this ATM, will be available (at least initially) for ES 6.x alone.

**Comment by craigsands** [comment]
Hello, @sscarduzio ,
I was just wondering if there was any further progress on this?

**Comment by sscarduzio** [comment]
The code is there, manually tested and not well documented. I created an internal issue for this RORDEV-54 so that we have integration tests in place and create more decent documentation.

/cc @coutoPL

**Comment by coutoPL** [comment]
this is done. Doc can be find here: https://github.com/beshu-tech/readonlyrest-docs/blob/master/elasticsearch.md#internode-communication---transport-module
