### ISSUE TITLE
Add a rule to match a query "action"

### ISSUE THREAD

**Issue by sscarduzio** [sscarduzio/elasticsearch-readonlyrest-plugin#41]
Ability to match by action (a la Shield). Examples of actions:  

```
      "cluster:monitor/nodes/info"
      "cluster:monitor/health"
      "indices:admin/exists"
      "indices:admin/mappings/fields/get"
```

**Comment by nitram4** [comment]
wow, we are really getting free "Shield" and fast track "search guard" :-) And the response time is awesome - Thanks for involvement

**Comment by sscarduzio** [comment]
Hahahha @nitram4 thanks for the boost of confidence:) 

By the way is there is any other feature you'd like to see?
