### ISSUE TITLE
[readonlyrest_kbn] got an error [403] Forbidden for path /

### ISSUE THREAD

**Issue by Guruhbk** [sscarduzio/elasticsearch-readonlyrest-plugin#413]
Hi, I'm trying to use multi-tenancy in readonlyrest. So I followed this document. [https://github.com/beshu-tech/readonlyrest-docs/blob/master/multitenancy_guide.md](multitenancy_guide). I did exactly the same. But unfortunately, I could only log in as kibana:kibana and not as any other users. 
**Kibana Error**
`  log   [06:35:02.008] [error][readonlyrest_kbn] got an error [403] Forbidden for path /
  log   [06:35:02.024] [info][readonlyrest_kbn] try extract credentials from JSON
  log   [06:35:11.462] [info][readonlyrest_kbn] try extract credentials from JSON
  log   [06:35:11.465] [info][readonlyrest_kbn] try extract credentials from JSON
  log   [06:35:11.472] [error][ror] identity error: undefined
`

**Elasticsearch Error.**
`[2019-03-05T12:09:34,683][INFO ][t.b.r.a.ACL              ] [vEtFfiK] FORBIDDEN by default req={ ID:1102256757-974396710#2593, TYP:RRAdminRequest, CGR:N/A, USR:sales_admin_usr(?), BRS:false, KDX:null, ACT:cluster:admin/rradmin/refreshsettings, OA:127.0.0.1, DA:0.0.0.0, IDX:<N/A>, MET:GET, PTH:/_readonlyrest/metadata/current_user, CNT:<N/A>, HDR:{authorization=<OMITTED>, Connection=close, content-length=0, Host=localhost:9200}, HIS:[::KIBANA-SRV::->[auth_key->false]], [ADMIN_SALES->[auth_key->false]] } 
`

**Comment by sirdrug** [comment]
I have the same error

**Comment by sscarduzio** [comment]
I added a paragraph to the guide, make sure you disable xpack security :

https://github.com/beshu-tech/readonlyrest-docs/blob/master/multitenancy_guide.md#important-disable-xpack-security-module
