### ISSUE TITLE
 Make it work with Marvel (free edition)

### ISSUE THREAD

**Issue by sscarduzio** [sscarduzio/elasticsearch-readonlyrest-plugin#42]
Following up from #31 with @nitram4:

We'd need to:
1. Install Marvel https://register.elastic.co/marvel_register
2. See what actions the dashboard performs on what indices
3. Obtain the most minimal conf. recipe for RO dashboard access
4. Obtain the most minimal conf. recipe for RW dashboard access
 
ref. for Kibana we had this official document that laid out the conf for us, didn't find anything similar for Marvel.
https://www.elastic.co/guide/en/shield/shield-1.2/_shield_with_kibana_4.html

**Comment by nitram4** [comment]
Actually i have tested it and it works as expected. I have user and have it granted .marvel* index and everytime intry to access those indexes im asked for password. For example in Kibana when I am in discovery tab it asks me for passpwrd and when i switch to Marvel app it again asks me for password.
Anyway I dont see any reason to integrate it in any way with "+" role as it is not needed for Kibana anyway.
Kibana has to have it granted (for kibana user "kibana_server") as it is checking the statusnof .marvel index when starting but ro is enough.

**Comment by sscarduzio** [comment]
@nitram4 ok so you suggest we add the possibility to check for the existence of ".marvel" for the kibana_access rule? 
Interesting that Kibana checks for Marvel, any idea of why this happens? Does this happen in the vanilla Kibana without plugins?

**Comment by nitram4** [comment]
Yes, and to have "kibana_server" to be able to read from it.

**Comment by nitram4** [comment]
I believe we can close this issue, since there is no noeed to implement it to the plugin. If user has right to .marvel indices it can open marvel app from kibana and see the data (of course has to authenticate again) 
Anyway its working. Kibana server should have it granted at least "ro".

**Comment by sscarduzio** [comment]
Makes sense! Thanks @nitram4
