### ISSUE TITLE
Rest authentication code

### ISSUE THREAD

**Issue by mohankumaru** [sscarduzio/elasticsearch-readonlyrest-plugin#422]
I want to know which folder has the code for rest authentication.

**Comment by sscarduzio** [comment]
that's super vague, what do you want to do?

**Comment by sscarduzio** [comment]
I guess they've been forked enough this year, lol.

**Comment by sscarduzio** [comment]
No but seriously I suggest you use the plugin API, as they also do internally for features that go in the main distribution. See:

https://github.com/elastic/elasticsearch/tree/master/plugins
