### ISSUE TITLE
Support session time out

### ISSUE THREAD

**Issue by sscarduzio** [sscarduzio/elasticsearch-readonlyrest-plugin#43]
Following up from #31 with @nitram4
### Less invasive, no-persistence solution (attempt, see if it works)

When the client authenticates via Basic HTTP Auth (without the cookie), we accept the request and set a cookie with no expiration time containing the timestamp of the first login.

Every time the client comes with the authentication in the headers, we check his cookie. If it's too old than the configured value, we delete its cookie and respond 401.
### If this does not work for some reason

We'd need server side storage for the sessions. Guava has some in memory cache with time and size based eviction (and there's also some overflow to disk solution around it). 
We could also store stuff in our own index, but that's a very heavy handed solution for this task. Maybe for later bigger features may be worth it?

**Comment by danielmotaleite** [comment]
i don't know Guava, but remember that you need to share the session cookies between all elasticsearch nodes. index already in all nodes (or at least can fetch then, like the no-data nodes)

**Comment by sscarduzio** [comment]
You got a point, let's have an index in ES for us and be good with it. It's the most generic solution that supports a coherent cache if one wants to do load balancing across multiple ES REST nodes.

But at this point we'd somehow need to make sure the YML configuration is also coherent, wouldn't we?

**Comment by nitram4** [comment]
I have been using this plugin in current version for a while (mainly through kibana) but everytime I restart Chrome and access Kibana I get popup window for authentication. So basically its only about logoff after certain time when the browser is open. It is security enhancement but the main concern is working.
