### ISSUE TITLE
After installing Readonlyrest-1.17.5_es7.0.0.zip elk is not working.

### ISSUE THREAD

**Issue by sharathmankala** [sscarduzio/elasticsearch-readonlyrest-plugin#437]
Hi Team,
Today we are upgraded our ELK Stack to 7.0.0. also we upgraded Readonlyrest.
After upgrading  ELK is not running.
We are getting below error

ncaught exception in thread [main] org.elasticsearch.bootstrap.StartupException: SettingsException[Failed to get setting group for [] setting prefix and setting [pidfile] because of a missing '.']

**Comment by sscarduzio** [comment]
Hi this is a known bug unfortunately. 1.17.6 is around the corner.

**Comment by sharathmankala** [comment]
now can we try ?

**Comment by sscarduzio** [comment]
it's available, go get it: https://readonlyrest.com/download

**Comment by sharathmankala** [comment]
As you Suggested we downloaded latest version from readonlyrest.
But still we are facing same issue.

Please find Below logs :

2019-04-30T07:24:32,256][INFO ][o.e.x.m.p.l.CppLogMessageHandler] [] [controller/25718] [Main.cc@109] controller (64 bit): Version 7.0.0 (Build cdaa022645f38d) Copyright (c) 2019 Elasticsearch BV
[2019-04-30T07:24:32,936][WARN ][t.b.r.e.ReadonlyRestPlugin] [][ReadonlyRestPlugin] could not check if had remote ES clusters: Failed to get setting group for [] setting prefix and setting [pidfile] because of a missing '.'
[2019-04-30T07:24:32,984][INFO ][t.b.r.e.IndexLevelActionFilter] [] Settings observer refreshing...

**Comment by coutoPL** [comment]
@sharathmankala are you able to share minimal configuration which causes the fail?

**Comment by sharathmankala** [comment]
readonlyrest:
    prompt_for_basic_auth: false
    response_if_req_forbidden: Sorry, your request is forbidden.

    access_control_rules:

    - name: "Name"
      auth_key: Name:xxxxxx

    - name: "Name"
      auth_key: Name:xxxxxx
      kibana_access: rw
      indices: [ ".kibana", "idex-*", "web-nginx-error-*", "index-xyz-*" , "index-comp-*" , "index-kertes-*" , "index-2019-*" , ".monitoring" , "elastalert_status_status" , "elastalert_status" , "elastalert_status_error" , "elastalert_status_past" , "elastalert_status_silence"]
      kibana_hide_apps: ["timelion", "kibana:dev_tools" , "kibana:management","elastalert-kibana-plugin","apm"]

**Comment by HagK** [comment]
Am 2019-04-30 10:51, schrieb Mateusz Kołodziejczyk:
> @sharathmankala [1] are you able to share minimal configuration which
> causes the fail?

it seems, this WARN occures, if no remote cluster is defined.
I have the same warning on ES 6.7.1 with ROR 1.17.4

https://www.elastic.co/guide/en/elasticsearch/reference/master/modules-cross-cluster-search.html

triggered by unction hasRemoteClusters
    try:
     return 
!clusterService.getSettings().getAsGroups().get("cluster").getGroups("remote").isEmpty();



ROR works fine here with this WARN, but 7.0 not tested yet.


regards
Hagen

**Comment by sharathmankala** [comment]
installed version is  readonlyrest-1.17.6_es7.0.0.zip

**Comment by coutoPL** [comment]
@sharathmankala I haven't notice that this is a warn message. Previously, you had an exception. As @HagK said, ROR should work without it. Did you check if your rules are working fine?

**Comment by sharathmankala** [comment]
with out ROR working fine.
we tested.

**Comment by coutoPL** [comment]
sorry, don't get it. Would you describe what issue are you faced? In your first post you are talking about exception. We've fixed it. Now, you get only a warn message. So, your ES with ROR should launch and be ready for handling requests. 

Is there sth concrete that doesn't work for you?

**Comment by sharathmankala** [comment]
After upgrading elk with ROR we are unable to start ELK stack.
i have checked in elk logs found  below info
2019-04-30T07:24:32,256][INFO ][o.e.x.m.p.l.CppLogMessageHandler] [] [controller/25718] [Main.cc@109] controller (64 bit): Version 7.0.0 (Build cdaa022645f38d) Copyright (c) 2019 Elasticsearch BV
[2019-04-30T07:24:32,936][WARN ][t.b.r.e.ReadonlyRestPlugin] [][ReadonlyRestPlugin] could not check if had remote ES clusters: Failed to get setting group for [] setting prefix and setting [pidfile] because of a missing '.'
[2019-04-30T07:24:32,984][INFO ][t.b.r.e.IndexLevelActionFilter] [] Settings observer refreshing...


Then i have removed ROR plugin and then  restarted ELK stack working fine.
So i concluded issue with ROR.

**Comment by coutoPL** [comment]
@sharathmankala ok, could you send full start log? The warn you send should not cause starting failure. Please, also enable debug log level.
