### ISSUE TITLE
Investigate compatibility with Shield plugin for Kibana

### ISSUE THREAD

**Issue by sscarduzio** [sscarduzio/elasticsearch-readonlyrest-plugin#44]
Following up from #31 with @nitram4

There could be the possibility to mimic the Shield REST API for login/logout. Shield's Kibana plugin is free to install and source is not uglified, so that's encouraging.

The most delicate part is to mock the original Shield API paths, worth investigating because we could have a proper login form rather than basic auth's browser modal window in Kibana.

**Comment by nguoianphu** [comment]
It'll be a great enhancement! I'm waiting for it. :+1:

**Comment by sscarduzio** [comment]
What would this add? Besides the need for installing the shield plugin for having a CSS login?
