### ISSUE TITLE
Kibana Unable to Access after installing latest ROR

### ISSUE THREAD

**Issue by sharathmankala** [sscarduzio/elasticsearch-readonlyrest-plugin#449]
After adding below yaml i am getting below error on kibana
{"message":"Sorry, your request is forbidden.: [undefined] Sorry, your request is forbidden.","statusCode":403,"error":"Forbidden"}

Note: with out ROR yaml file i am able to access kibana dashboard.

ROR installed version : readonlyrest-1.18.0_es7.0.1.zip

readonlyrest:
    prompt_for_basic_auth: false
    response_if_req_forbidden: Sorry, your request is forbidden.

    access_control_rules:

    - name: "Sharath"
      auth_key: smankala:AKDHYU

**Comment by sscarduzio** [comment]
Hi @sharathmankala, 
Are you using our kibana plugin too?

**Comment by sharathmankala** [comment]
No.
After installing Elasticseacrh ROR i am getting  below error

{"message":"Sorry, your request is forbidden.: [undefined] Sorry, your request is forbidden.","statusCode":403,"error":"Forbidden"}

**Comment by coutoPL** [comment]
try: `prompt_for_basic_auth: true`

**Comment by sharathmankala** [comment]
Working Fine.
Thanks For your Help.
