### ISSUE TITLE
Restricting access to indices within `kibana_access`

### ISSUE THREAD

**Issue by dcoueron** [sscarduzio/elasticsearch-readonlyrest-plugin#45]
I have just upgraded my elasticsearch install to 2.3.1 thinking innocently that your build for 2.3.0 would work...

**Comment by sscarduzio** [comment]
Hello @dcoueron, I just released the new build and updated the documentation with the new link. 

By the way, please share your experience using this plugin! What's good, what should be better, what new features you'd like to see and so on.

Enjoy!

**Comment by dcoueron** [comment]
Thanks for the quick release!
What I want to do is to allow readonly access through Kibana to my users but not for all indices.
I did not manage to do that, is it possible ?

I tried this:
```
    - name: Communauté gouvernance WebAPI
      type: allow
      kibana_access: ro
      indices: [my_index]
      auth_key: user:passwd
```

**Comment by sscarduzio** [comment]
Sorry I can't give you a tested solution for this as I'm travelling right now, I'm not even sure what goes wrong, but for now I'd try using the wildcard indices:

> type: allow
> kibana_access: ro
> indices: [my_index, .kibana*]
> auth_key: user:passwd

**Comment by sscarduzio** [comment]
any success with this @dcoueron?

**Comment by dcoueron** [comment]
Sorry, I'm not in office this week :-)
I'll get back to you as soon as I have a chance to try it.

Le mer. 13 avr. 2016 10:41, Simone Scarduzio <notifications@github.com> a
écrit :

**Comment by dcoueron** [comment]
Hello @sscarduzio 
It seems to work but not when my Kibana Dashboard includes some markdown widgets. It's strange because such widgets don't query any data from kibana

**Comment by sscarduzio** [comment]
@dcoueron BTW, you can get a lot of info from the logs: when the plugin blocks a request, it logs all the request context (including the action field). If you see something that should pass and is blocked send it to me and I can include it in the Kibana passthrough rule.

**Comment by dcoueron** [comment]
Hi, In which log should I look ? Is there some kind of log level to set somewhere ?

**Comment by sscarduzio** [comment]
Set the whole ES to debug mode, you can grep for "{ action: "

**Comment by sscarduzio** [comment]
If you want to see all the request contexts (not only the blocked ones) put ES in trace mode and the grep is the same.

**Comment by dcoueron** [comment]
Found my issue : When creating a markdown widget, Kibana tries to query the default index (kibana settings) even if no data is returned !
The workaround we used is to create an empty index, defined as default in kibana that every user can read.

Thanks for your help !

**Comment by sscarduzio** [comment]
@dcoueron wait, the default index = ".kibana" ? as opposed to what index? (supper happy you figured it out btw!)

**Comment by dcoueron** [comment]
.kibana is the "internal" index used by kibana to store its data. By "default index" I mean the index that will be searched by default when a user opens kibana.
![image](https://cloud.githubusercontent.com/assets/6373497/14716449/621db408-07ed-11e6-88ac-6ceb7adcfbc8.png)

**Comment by sscarduzio** [comment]
@dcoueron are you all right with this? can we close this issue? 
BTW: I'd like your opinion on a new feature I was thinking of adding: how about I let the users (optionally) write two javascript call backs: i.e. `onRequest` and `onResponse` where people can write custom business logic to accept/reject requests according to action, indices, method, etc. or even modify the request/response body, add/remove headers on the fly?
What do you think? :)
