### ISSUE TITLE
ELK 7.1.0 Support

### ISSUE THREAD

**Issue by AshenOfValheru** [sscarduzio/elasticsearch-readonlyrest-plugin#450]
Hi All,

Just wondering if support for ELK 7.1.0 is around the corner?

Require it for another plugin that only supports that version at the moment unfortunately.

Great plugin by the way.

**Comment by muhviehstah** [comment]
change es70x/gradle.properties to esVersion=7.1.0 and build with ./gradlew --stacktrace es70x:ror '-PesVersion=7.1.0'


works fine

**Comment by AshenOfValheru** [comment]
That's great thank you for the turn around, haven't looked yet but is there a similar fix for the enterprise kibana plugin as well?

**Comment by sscarduzio** [comment]
both Kibana and Elasticsearch plugins are now aligned to the latest version 7.1.1
