### ISSUE TITLE
How to force a rule to have an empty x_forwarded_for 

### ISSUE THREAD

**Issue by waldo2188** [sscarduzio/elasticsearch-readonlyrest-plugin#466]
First, you have made a really good work with this plugin, so thanks to all contributors.
My question is about the x_forwarded_for rule.

I run elasticsearch and kibana behind a reverse proxy with other applications (with Docker). For now, all the app use Elasticsearch without restriction, and Elasticsearch can’t be reached from the outside of our network. But I have the need to open my Elasticsearch to the world and restrict access. Everything work fine and are easy to setup.

But I want to create a rule that allow internal app to call Elasticsearch without any authentication, just based on the host IP (172.18.0.0/24).

If I set this kind of rule, every app in our network can call Elasticsearch without authentication: 
```
  - name: "::Docker Network ::"
    type: allow
    hosts: ["172.18.0.0/24"]
```
But as I wrote, I want to be able to call Elasticsearch from outside the server. So, I defined a route in the reverse proxy that redirects to Elasticsearch.

In this case, the host IP is the one of the reverse proxy and the x_forwarded_for handle the real IP.
So, the rule defined above applies. And this isn’t a good thing, because everyone can call the Elasticsearch service.

My question is, how can I define in a rule that the x_forwarded_for parameter must be null? In this way, I prevent the use of the rule when the call come from the outside.

**Comment by sscarduzio** [comment]
Have you seen the [headers rule](https://github.com/beshu-tech/readonlyrest-docs/blob/master/elasticsearch.md#headers)?
You could use it to check that the x-forwarded-for header is not null.

**Comment by waldo2188** [comment]
I've tried with header. I've made two rules one to forbid if x-forwarded-for is in, and one who allow if the header contain a specific host value:

```
  - name: "::FROM WEB::"
    type: forbid 
    headers: ["X-Forwarded-For:*"] 

  - name: "::Docker Network::"
    type: allow
    hosts: ["172.0.0.0/8"]
    headers: ["host:elasticsearch*9200"] 
```
This configuration work fine, but please tell me if I’m using it in the right way.

In the second rule, I want to check if the value of `host` is ` elasticsearch:9200`. But the char `:` between `elasticsearch` and `9200` isn’t accepted by the plugin. Am I wrong ?

**Comment by sscarduzio** [comment]
the problem is that
```
  - name: "::FROM WEB::"
    type: forbid 
    headers: ["X-Forwarded-For:*"]
```
this block is going to match, and because the type forbid , the request is going to be rejected leaving the second block unreachable.

**Comment by waldo2188** [comment]
Good, that is exactly what I want.  
Thank you, a lot, for your help. We can close this issue.
