### ISSUE TITLE
ACL based on a field value

### ISSUE THREAD

**Issue by elvarb** [sscarduzio/elasticsearch-readonlyrest-plugin#48]
Is it possible to have acl based ofn a field value? the classic example if you have a field called "env" and all docs are in the same index, you could then limit access to specific data, env:prod, env:test, env:dev.

This could either be done by modifying the request before it reaches ES or by stripping out documents before they leave ES.

**Comment by sscarduzio** [comment]
This is quite advanced, needs a bit of research. But if I recall correctly Search Guard has something similar and I could take some inspiration.

Nice one though, thanks for the cool idea!

#TODO

**Comment by sscarduzio** [comment]
@elvarb I was thinking about supporting a javascript callback where people can apply custom business logic like this one. Would you be interested?

**Comment by elvarb** [comment]
How would that work?

**Comment by sscarduzio** [comment]
A field in the yaml would basically be a multiline string with a function in JS. Imagine the rule:
```
name: script rule
type: allow
script: >
  function onRequest(reqContext) {
      reqContext.getIndices() ...
     if(reqContext.getAction() == 'blah') {
      return false; // NO_MATCH
     }
    if(reqContext.getOriginAddress() == '127.0.0.1' ) { return true; }
  }
```

But what I'd like to do is also this:

```
name: script rule
type: allow
script: >
  function onResponse(response) {
    var r = JSON.parse(response);
     r = r.property = { manipulatedProperty: "stuffHere"};
    return r;
  }
```
Is this too low level? Would it be useful?

**Comment by Globegitter** [comment]
X-Pack calls this document level security btw and they also offer field level security: https://www.elastic.co/guide/en/x-pack/current/field-and-document-access-control.html
I think having both of these would be very useful and I suppose with the `response_script` option one could probably use that to filter out certain fields or documents. I think also the `request_script` looks pretty useful.
