### ISSUE TITLE
LDAP groups not recognised and kibana access issues

### ISSUE THREAD

**Issue by abrahamjoel** [sscarduzio/elasticsearch-readonlyrest-plugin#480]
Hi, I am using readonlyrest ES and kibana plugins. I have configured it to authenticate ES from my active directory. When trying to delegate access to groups, I am quite unsuccessful. Access is provided to all users in LDAP tree for ES. Also in kibana dashboard, following error shows up
`Could not login: { "username": "XXXXX", "authHeaders": "", "hiddenApps": [], "sid": "051a5ee7-b397-4767-bc20-a2ae83ce4867", "expiresAt": 1565262020863 } {}` when trying to login.

Following is my readonlyrest.yml
  `readonlyrest:
    response_if_req_forbidden: Access Forbidden by readonlyrest

    access_control_rules:
    - name: full access for backend group
      type: allow                                           # Optional, defaults to "allow", will omit from now on.
      ldap_authentication:
        name: "ldap1"                                       # ldap name from below 'ldaps' section
        groups: ["BackendDev"]       # group within 'ou=unixGroups,dc=example,dc=com'
        verbosity: error
      indices: ["*"]
      actions: ["*"]
    - name: kibana access for backend group
      type: allow                                           # Optional, defaults to "allow", will omit from now on.
      ldap_authentication:
        name: "ldap1"                                       # ldap name from below 'ldaps' section
        groups: ["*"]       # group within 'ou=Groups,dc=example,dc=com'
        verbosity: error
      kibana_access: admin
      kibana_index: ".kibana"
      indices: [“*"]
    ldaps:
    - name: ldap1
      host: "******.******.com"
      port: 389                                                     # optional, default 389
      ssl_enabled: false                                            # optional, default true
      ssl_trust_all_certs: true                                     # optional, default false
      bind_dn: "CN=Administrator,CN=Users,DC=******,DC=io"                         # optional, skip for anonymous bind
      bind_password: "***********"                                     # optional, skip for anonymous bind
      search_user_base_DN: "OU=unixUsers,DC=******,DC=io"
      user_id_attribute: "sAMAccountName"                                      # optional, default "uid"
      search_groups_base_DN: "OU=unixGroups,DC=******,DC=io"
      unique_member_attribute: "member"                                # optional, default "uniqueMember"
      connection_pool_size: 200                                      # optional, default 30
      connection_timeout_in_sec: 100                                 # optional, default 1
      request_timeout_in_sec: 200                                    # optional, default 1
      cache_ttl_in_sec: 60                                          # optional, default 0 - cache disabled
      group_search_filter: "(objectClass=group)(CN=*)"   # optional, default (cn=*)
      group_name_attribute: "cn"`

Any help will be greatly appreciated. Thanks in advance!!

**Comment by coutoPL** [comment]
hi @abrahamjoel you should check your ES logs. It is the place where you find an answer why your request for forbidden. You can enable debug level of logs to see more (eg. LDAP queries and responses)
