### ISSUE TITLE
filter not working in a cluster

### ISSUE THREAD

**Issue by balamvijay91** [sscarduzio/elasticsearch-readonlyrest-plugin#489]
Hi,

readonlyrest filter is not working in a cluster with 3 nodes. Elasticsearch gives all the results without filtering the data. It is working fine when we have only one elasticsearch node. Below is my readonlyrest.yml and elasticsearch.yml. Please, let me know if something is wrong in my configuration

Versions: 
Elasticsearch 6.4.3
readonlyrest-1.17.6-ES6.4.3-plugin

**elasticsearch.yml:**

cluster.name: cluster-sample
node.name: node1
http.port: 9200
transport.tcp.port: 9300
network.host: 0.0.0.0
discovery.zen.ping.unicast.hosts: [ node1, node2, node3 ]
discovery.zen.minimum_master_nodes: 3
gateway.recover_after_nodes: 2
indices.query.bool.max_clause_count: 100000
bootstrap.system_call_filter: false
http.max_content_length: 1024mb
indices.memory.index_buffer_size: 1024MB
xpack.watcher.enabled: false
xpack.security.enabled: false
xpack.monitoring.enabled: false
xpack.ml.enabled: false
xpack.graph.enabled: false

**readonlyrest.yml:**

readonlyrest:
  enable: true
  response_if_req_forbidden: Sorry, your request is forbidden.
  access_control_rules:
  - name: "::admin::"
    proxy_auth:
        proxy_auth_config: "proxy-user"
        users: ["admin"]
    actions: ["indices:data/read/*", "indices:data/write/*", "indices:data/write/bulk", "indices:admin/template/*", "indices:admin/create", "indices:admin/delete", "indices:admin/aliases", "indices:admin/aliases/get", "indices:admin/aliases/exists", "indices:admin/mapping/put", "indices:admin/mappings/get", "indices:admin/mappings/fields/get", "indices:data/read/field_stats", "indices:data/read/msearch", "indices:admin/settings/update", "cluster:admin/settings/update", "indices:monitor/*", "cluster:monitor/*"]
    indices: ["*"]
    verbosity: error
  - name: "::KIBANA-SRV::"
    auth_key: kibana:kibana
    type: allow
    kibana_hide_apps: ["readonlyrest_kbn", "timelion", "kibana:dev_tools", "kibana:management", "apm", "monitoring", "kibana:discover","kibana:visualize"]
  - name: "::myuser::"
    type: allow
    proxy_auth:
        proxy_auth_config: "proxy-user"
        users: ["myuser"]
    actions: ["indices:data/read/*", "indices:data/write/*", "indices:admin/template/*","indices:admin/create","indices:admin/delete", "indices:admin/aliases", "indices:admin/aliases/exists", "indices:admin/mapping/put", "indices:admin/mappings/get", "indices:admin/mappings/fields/get", "indices:data/read/field_stats", "indices:data/read/msearch"]
    indices: ["@{x-forwarded-tenant}"]
    filter: '@{x-tenant-header}'
    verbosity: error
  - name: "::myuser kibana::"
    proxy_auth:
        proxy_auth_config: "proxy-user"
        users: ["myuser"]
    kibana_access: ro
    kibana_hide_apps: ["readonlyrest_kbn", "timelion", "kibana:dev_tools", "kibana:management", "apm", "monitoring", "kibana:discover","kibana:visualize"]
    indices: [".kibana_@{x-forwarded-tenant}", ".kibana_sandbox"]
  - name: "::ADMIN::"
    proxy_auth:
        proxy_auth_config: "proxy-user"
        users: ["admin"]
    kibana_access: admin
  proxy_auth_configs:
      - name: "proxy-user"
        user_id_header: "x-forwarded-user"

**Comment by coutoPL** [comment]
@balamvijay91 it was a bug, but it's already fixed (https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/pull/479). Please, upgrade ROR to the newest version available and everything should work as expected

**Comment by balamvijay91** [comment]
@coutoPL Its working after upgrading to the latest version. Thanks a lot!!!
