### ISSUE TITLE
Opening the POST Search API

### ISSUE THREAD

**Issue by LiorBu1** [sscarduzio/elasticsearch-readonlyrest-plugin#49]
According to the Elastic documentation, the search API can be used with `POST`.

What is the best way to allow the search API to be opened to all?

I considered using something like `uri_re: .*/_search/.*`.  Would this make sense?

**Comment by sscarduzio** [comment]
`uri_re` is a last resort, it's much better if you manage to do this at `actions` level. My suggestion is to reverse engineer what actions your app uses:
- install and enable my plugin with only one block of rules like so:
````
 - name: Just inspecting my app's traffic
      type: allow
````
- set ES logs in trace mode (`conf/logging.yml`)
- grep ES logs for this line: `checking request:`.
- now run your app and see what actions are being seen in the logs

Now the grep should show how ES parser sees the actions performed by your app. You can now put together a rule to allow only those actions. Keep in mind wildcards are valid. E.g.

```
 - name: Allow just certain actions I saw in the logs
      type: allow
      actions: [ indices:data/read/*, indices:data/search/*, indices:data/msearch/*]
```
 
I hope it helps!

**Comment by LiorBu1** [comment]
It worked but I had to use double quotes, like this:

```
  - name: Allow Public Search
      type: allow  
      actions: [ "indices:data/read/*", "indices:data/search/*", "indices:data/msearch/*"]
```

Thanks!

**Comment by sscarduzio** [comment]
Brilliant, closing this one :)
