### ISSUE TITLE
Support ilm (Index Lifecycle Management) related actions

### ISSUE THREAD

**Issue by jianchen2580** [sscarduzio/elasticsearch-readonlyrest-plugin#507]
ES ilm need "manage_ilm" for cluster and "manage" and "manage_ilm" for indices
which actions should i use for support above privileges?
[Actions]( https://github.com/beshu-tech/readonlyrest-docs/blob/master/elasticsearch.md#actions) list for ES 5.1.2.

**Comment by sscarduzio** [comment]
Updated documentation with actions list to the current ES master branch.

```
 "cluster:admin/ilm/_move/post" 
 "cluster:admin/ilm/delete" 
 "cluster:admin/ilm/get" 
 "cluster:admin/ilm/operation_mode/get" 
 "cluster:admin/ilm/put" 
 "cluster:admin/ilm/start" 
 "cluster:admin/ilm/stop" 
```

This is what you are looking for I presume
