### ISSUE TITLE
Allow RW access to a specific type of an index

### ISSUE THREAD

**Issue by Nos2015** [sscarduzio/elasticsearch-readonlyrest-plugin#51]
Hi,

Is there a way to allow read/write access to a specific type of an index ?
For example, if I have a type posts and comments inside a ES index.
I would like to unauthorized write access to posts (only readonly) and allow to customer to add comment on the type comments ( I would like to use update, bulk api, insert).

Best regards,

**Comment by sscarduzio** [comment]
Hey Morin, good idea! That would be nice to have! I’ll add this as an enhancement. As soon as I can I will group a few features and set up a milestone, so I’ll know what to work on.
