### ISSUE TITLE
kibana_access ro: not working update for kibana index

### ISSUE THREAD

**Issue by stegan** [sscarduzio/elasticsearch-readonlyrest-plugin#512]
Hello!
I found out issue after migration from **6.8** to **7.3**: user (with kibana_access ro) see basic auth requests after adding/deleting fields in Kibana's Discover, it's needed access for such requests.
As I correctly understood such requests are related to "Popular fields" feature.
I checked uriPath & action:
**6.8:** `/.kibana/doc/index-pattern%3A88471bb0-8f4f-11e8-b405-fff1a9b3c092/_update?if_seq_no=120&if_primary_term=2&refresh=wait_for` `indices:data/write/update`
**7.3:** `/.kibana/_update/index-pattern%3A98115060-8f4f-11e8-8c86-c74c3ec07dbb?if_seq_no=44&if_primary_term=2&refresh=wait_for` `indices:data/write/update`
I checked docs:
**6.8** https://www.elastic.co/guide/en/elasticsearch/reference/6.8/docs-update.html
**7.3** https://www.elastic.co/guide/en/elasticsearch/reference/7.3/docs-update.html
I can conclude that syntax has been changed & it's not support by ror plugin now.
I patched KibanaAccessRule.scala to fix issue, updated regex in kibanaIndexPattern to:
`"^/@kibana_index/(url|config/.*/_create|index-pattern|doc/index-pattern.*|doc/url.*)/.*|^/_template/.*|^/@kibana_index/doc/telemetry.*|^/@kibana_index/(_update/index-pattern.*|_update/url.*)"`

**Comment by sscarduzio** [comment]
makes sense, thanks @stegan.
