### ISSUE TITLE
Kibana (7.2) Logout Obscures Functions

### ISSUE THREAD

**Issue by Amorik** [sscarduzio/elasticsearch-readonlyrest-plugin#518]
In some cases the location of the logout button for Read-Only-Rest obscures kibana UI functions. As an example below is what it looks like when attempting to import saved objects. If using multi-tenancy you wouldn't even notice the blue box beneath the pink user logout button. 

![image](https://user-images.githubusercontent.com/23191740/67020129-b52a8200-f0cb-11e9-8ec5-9756b548360c.png)

**Comment by sscarduzio** [comment]
You must be using an old version of ROR Enterprise. Now we have a minimize/maximize button on the pink box.

**Comment by Amorik** [comment]
Just got around to updating to 1.18.8 (from 1.18.2) of the RoR plugin and the min/max button is available as described. 

![image](https://user-images.githubusercontent.com/23191740/69368019-4b237080-0c67-11ea-80a2-bb7b684b7811.png)

![image](https://user-images.githubusercontent.com/23191740/69368037-55de0580-0c67-11ea-9b7a-ba1239d3c3eb.png)
