### ISSUE TITLE
Environment variable support in configuration file readonlyrest.yml appears to be broken or removed.

### ISSUE THREAD

**Issue by rodaj** [sscarduzio/elasticsearch-readonlyrest-plugin#519]
At some point between plugin version 1.17.4 and 1.18.5( and up) environment variable support stopped being honored or working.  Have been forced to hardcode values which in my opinion is less secure then having values (such as jks passwords) in environment variables in containerized environment.

Either the code needs to be fixed or the documentation needs to be updated to indicate that environment variable support was dropped/removed.

Recreation is extremely simple, just have password for JKS in environment variable and use environment variable in readonlyrest.yml.  When elasticsearch service is started an error will be returned for JKS stating invalid password (here is example with latest plugin 1.18.7 for ES 6.8.3:

{"type": "server", "timestamp": "2019-10-17T15:53:14,031+0000", "level": "ERROR", "component": "t.b.r.u.SSLCertParser$", "cluster.name": "mytest2", "node.name": "zinc-koala-elasticsearch-data-f4f58d57d-fsqhd",  "message": "ROR SSL: Failed to load SSL certs and keys from JKS Keystore! IOException: keystore password was incorrect" ,
"stacktrace": ["java.io.IOException: keystore password was incorrect",
"at sun.security.pkcs12.PKCS12KeyStore.engineLoad(PKCS12KeyStore.java:2117) ~[?:?]",
"at sun.security.util.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:243) ~[?:?]",
"at java.security.KeyStore.load(KeyStore.java:1472) ~[?:?]",
"at tech.beshu.ror.utils.SSLCertParser$.$anonfun$tryRun$1(SSLCertParser.scala:60) ~[core-1.18.7.jar:?]",
"at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23) ~[scala-library-2.12.8.jar:?]",
"at scala.util.Try$.apply(Try.scala:213) ~[scala-library-2.12.8.jar:?]",
"at tech.beshu.ror.utils.SSLCertParser$.tryRun(SSLCertParser.scala:55) ~[core-1.18.7.jar:?]",
"at tech.beshu.ror.utils.SSLCertParser$.run(SSLCertParser.scala:37) [core-1.18.7.jar:?]",
"at tech.beshu.ror.es.ssl.SSLNetty4HttpServerTransport$SSLHandler.$anonfun$new$1(SSLNetty4HttpServerTransport.scala:64) [readonlyrest-1.18.7_es7.3.2.jar:?]",
"at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23) [scala-library-2.12.8.jar:?]",
"at tech.beshu.ror.es.utils.AccessControllerHelper$$anon$1.run(AccessControllerHelper.scala:25) [readonlyrest-1.18.7_es7.3.2.jar:?]",
"at java.security.AccessController.doPrivileged(AccessController.java:310) [?:?]",
"at tech.beshu.ror.es.utils.AccessControllerHelper$.doPrivileged(AccessControllerHelper.scala:24) [readonlyrest-1.18.7_es7.3.2.jar:?]",
"at tech.beshu.ror.es.ssl.SSLNetty4HttpServerTransport$SSLHandler.<init>(SSLNetty4HttpServerTransport.scala:64) [readonlyrest-1.18.7_es7.3.2.jar:?]",
"at tech.beshu.ror.es.ssl.SSLNetty4HttpServerTransport.configureServerChannelHandler(SSLNetty4HttpServerTransport.scala:56) [readonlyrest-1.18.7_es7.3.2.jar:?]",
"at tech.beshu.ror.es.ssl.SSLNetty4HttpServerTransport.configureServerChannelHandler(SSLNetty4HttpServerTransport.scala:39) [readonlyrest-1.18.7_es7.3.2.jar:?]",
"at org.elasticsearch.http.netty4.Netty4HttpServerTransport.doStart(Netty4HttpServerTransport.java:201) [transport-netty4-client-7.3.2.jar:7.3.2]",
"at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:59) [elasticsearch-7.3.2.jar:7.3.2]",
"at org.elasticsearch.node.Node.start(Node.java:760) [elasticsearch-7.3.2.jar:7.3.2]",
"at org.elasticsearch.bootstrap.Bootstrap.start(Bootstrap.java:273) [elasticsearch-7.3.2.jar:7.3.2]",
"at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:358) [elasticsearch-7.3.2.jar:7.3.2]",
"at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) [elasticsearch-7.3.2.jar:7.3.2]",

**Comment by coutoPL** [comment]
@rodaj variables weren't removed from ROR. Please, show us part of your config with variable usage.

documentation is here: 
https://github.com/beshu-tech/readonlyrest-docs/blob/master/elasticsearch.md#environmental-variables

also you can check out tests:
https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/blob/master/core/src/test/scala/tech/beshu/ror/unit/acl/blocks/variables/StartupResolvableVariablesTests.scala

**Comment by rodaj** [comment]
I'm well aware of the documentation.  Below is a portion of readonlyrest.yml that has been working for 9 months on various versions of plugin up to 1.17.4 as stated in description.  Versions 1.18.5 and 1.18.7 are a HARD failure again as documented in description. 

readonlyrest:
    enable: true
    response_if_req_forbidden: Forbidden by ReadonlyREST ES plugin
    ssl:
      # put the keystore in the same dir with elasticsearch.yml 
      keystore_file: helm-elastic.jks
      keystore_pass: ${ROR_KEYSTORE_PASS}
      key_pass: ${ROR_KEY_PASS}
      key_alias: ${ROR_KEY_ALIAS}
      allowed_protocols: [TLSv1.2]
      allowed_ciphers: [TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256]
    audit_collector: true

**Comment by coutoPL** [comment]
OK, I see now. We've bug with backward compatibility of old ENV var syntax `${ENV_NAM}`. It's fixed but not released yet. But you can use new syntax:

```
keystore_file: helm-elastic.jks
keystore_pass: "@{env:ROR_KEYSTORE_PASS}"
key_pass: "@{env:ROR_KEY_PASS}"
key_alias: "@{env:ROR_KEY_ALIAS}"
```

**Comment by coutoPL** [comment]
https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/pull/514
