### ISSUE TITLE
 Could not load plugin descriptor for plugin directory 

### ISSUE THREAD

**Issue by YLJIOS** [sscarduzio/elasticsearch-readonlyrest-plugin#550]
![image](https://user-images.githubusercontent.com/13409767/72779318-91d91b00-3c56-11ea-898d-3cef8fda019c.png)
elasticsearch 7.5.1

**Comment by coutoPL** [comment]
@YLJIOS 
<img width="1005" alt="Screenshot 2020-01-21 at 20 25 28" src="https://user-images.githubusercontent.com/231553/72836106-45a8cd80-3c8c-11ea-9e34-fab828e8211f.png">

Did you build the plugin yourself or download from our page?
