### ISSUE TITLE
Add availableGroups as dynamic variable

### ISSUE THREAD

**Issue by kiblik** [sscarduzio/elasticsearch-readonlyrest-plugin#565]
Hi,

I know `@{acl:user}`, `@{acl:current_group}`, `@{header:...}` or `@{jwt:...}` but is it possible to implement dynamic variable also for available groups (not only first match - `current_group`). It is useful if somebody is a member of more groups and needs access to all indices like `["@explode{acl:available_groups}-*"]`.

Thank you

**Comment by coutoPL** [comment]
@kiblik thanks for suggestion. We've added it to our backlog.

**Comment by kiblik** [comment]
Hi @coutoPL,

I came up with a solution for the previously mentioned problem. It was my first contact with Scala and also with your plugin so I hope everything is correct.
It would be very helpful if you could check my patch, review it and add to your plugin.

I'm just working with it and it would be very helpful if it will be available in the next release of the plugin.

[0001-Add-availableGroups-as-dynamic-variable.patch.tar.gz](https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/files/4240290/0001-Add-availableGroups-as-dynamic-variable.patch.tar.gz)

Thank you.

**Comment by coutoPL** [comment]
@kiblik it's great that you managed to add it yourself. Could you please create pull request to our repo? When you do this, there will be one important step of the pipeline - signing the contribution agreement. If you will have any problems with it, don't hesitate to ask.

**Comment by coutoPL** [comment]
it's done, so I'll close the issue
