### ISSUE TITLE
Got Error while installing readonly rest plugin for elasticsearch 2.3.1

### ISSUE THREAD

**Issue by stevesui** [sscarduzio/elasticsearch-readonlyrest-plugin#59]
I tried to install readonlyrest plugin for elasticsearch 2.3.1 and encountered the following error. Please help! Thanks a lot. 

sudo /usr/share/elasticsearch/bin/plugin install https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/blob/master/download/elasticsearch-readonlyrest-v1.9.1_es-v2.3.1.zip
-> Installing from https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/blob/master/download/elasticsearch-readonlyrest-v1.9.1_es-v2.3.1.zip...
Trying https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/blob/master/download/elasticsearch-readonlyrest-v1.9.1_es-v2.3.1.zip ...
Downloading ................................DONE
Verifying https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/blob/master/download/elasticsearch-readonlyrest-v1.9.1_es-v2.3.1.zip checksums if available ...
NOTE: Unable to verify checksum for downloaded plugin (unable to find .sha1 or .md5 file to verify)
ERROR: Could not find plugin descriptor 'plugin-descriptor.properties' in plugin zip

**Comment by sscarduzio** [comment]
I have to take a look at this one this weekend, in the meanwhile please download the plugin manually into a local folder and install it from there.
There should do it for now, the integration test in Docker does the same.

**Comment by stevesui** [comment]
Simone:
Thank you very much for the reply and help!
I will give it a try to install locally and let you know. 

By the way, what is the best way to install locally? Do I need to copy the zip file into the plugin directory and run bin/plugin install command? 

Any advice is greatly appreciated.

Steve Sui
 

    On Thursday, April 28, 2016 5:43 AM, Simone Scarduzio <notifications@github.com> wrote:
 

 I have to take a look at this one this weekend, in the meanwhile please download the plugin manually into a local folder and install it from there.
There should do it for now, the integration test in Docker does the same.—

**Comment by stevesui** [comment]
Simone:I tried to install the plugin as a local file, but still got the same error. Please advise. Again thanks a lot.  
Steve Sui
See below the snapshot of the screen:
sudo /usr/share/elasticsearch/bin/plugin install file:///tmp/elasticsearch-readonlyrest-v1.9.1_es-v2.3.1.zip --verbose-> Installing from file:/tmp/elasticsearch-readonlyrest-v1.9.1_es-v2.3.1.zip...Trying file:/tmp/elasticsearch-readonlyrest-v1.9.1_es-v2.3.1.zip ...Downloading .DONEVerifying file:/tmp/elasticsearch-readonlyrest-v1.9.1_es-v2.3.1.zip checksums if available ...NOTE: Unable to verify checksum for downloaded plugin (unable to find .sha1 or .md5 file to verify)ERROR: Could not find plugin descriptor 'plugin-descriptor.properties' in plugin zip 

    On Thursday, April 28, 2016 7:56 AM, steve sui <stevesui@yahoo.com> wrote:
 

 Simone:
Thank you very much for the reply and help!
I will give it a try to install locally and let you know. 

By the way, what is the best way to install locally? Do I need to copy the zip file into the plugin directory and run bin/plugin install command? 

Any advice is greatly appreciated.

Steve Sui
 

    On Thursday, April 28, 2016 5:43 AM, Simone Scarduzio <notifications@github.com> wrote:
 

 I have to take a look at this one this weekend, in the meanwhile please download the plugin manually into a local folder and install it from there.
There should do it for now, the integration test in Docker does the same.—

**Comment by sscarduzio** [comment]
This is the log of my docker integration test script installing the plugin:

```
/elasticsearch/bin/plugin install file:/tmp/elasticsearch-readonlyrest-v1.9.2_es-v2.3.2.zip
 ---> Running in a11141ad2dcb
-> Installing from file:/tmp/elasticsearch-readonlyrest-v1.9.2_es-v2.3.2.zip...
Plugins directory [/elasticsearch/plugins] does not exist. Creating...
Trying file:/tmp/elasticsearch-readonlyrest-v1.9.2_es-v2.3.2.zip ...
Downloading .DONE
Verifying file:/tmp/elasticsearch-readonlyrest-v1.9.2_es-v2.3.2.zip checksums if available ...
NOTE: Unable to verify checksum for downloaded plugin (unable to find .sha1 or .md5 file to verify)
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@     WARNING: plugin requires additional permissions     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
* java.lang.reflect.ReflectPermission suppressAccessChecks
See http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
for descriptions of what these permissions allow and the associated risks.
Installed readonlyrest into /elasticsearch/plugins/readonlyrest
```

I should probably read up and do something about that checksum, make it part of the build process. But as you can see it does not prevent the installation process to complete.

**Comment by sscarduzio** [comment]
OK Found the problem and fixed in the documentation:

```bin/plugin install https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/blob/master/download/elasticsearch-readonlyrest-v1.9.2_es-v2.3.2.zip?raw=true
```
The raw=true was missing

**Comment by stevesui** [comment]
Hi Simone:The parameter raw=true seems to move me further along. The Error of missing properties is no more there. However, the installation did not finish to the end. 
Here is the screen shot:
./bin/plugin install file:/tmp/elasticsearch-readonlyrest-v1.9.2_es-v2.3.2.zip?raw=true-> Installing from file:/tmp/elasticsearch-readonlyrest-v1.9.2_es-v2.3.2.zip?raw=true...Trying file:/tmp/elasticsearch-readonlyrest-v1.9.2_es-v2.3.2.zip?raw=true ...Downloading .DONEVerifying file:/tmp/elasticsearch-readonlyrest-v1.9.2_es-v2.3.2.zip?raw=true checksums if available ...Downloading .DONEERROR: invalid format for checksum file (SHA1), expected 1 line, got: 555
I did not see the logs after this line, as shown in your previous email.
Also I tried to list the plugins and it showed no plugin installed:
./bin/plugin listInstalled plugins in /home/ssui/elasticsearch-2.3.2/plugins:    - No plugin detected
Again appreciate it very much if you could provide further insights.
-Steve
 

    On Thursday, April 28, 2016 1:44 PM, Simone Scarduzio <notifications@github.com> wrote:
 

 OK Found the problem and fixed in the documentation:```bin/plugin install https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/blob/master/download/elasticsearch-readonlyrest-v1.9.2_es-v2.3.2.zip?raw=trueThe raw=true was missing

**Comment by sscarduzio** [comment]
@stevesui the raw=true I suggested applies only for the remote installation, that is: type the command you were doing in the beginning just add that ?raw=true to the HTTP URL.

See this example:

```
$ bin/plugin install https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/blob/master/download/elasticsearch-readonlyrest-v1.9.1_es-v2.3.1.zip?raw=true
-> Installing from https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/blob/master/download/elasticsearch-readonlyrest-v1.9.1_es-v2.3.1.zip?raw=true...
Trying https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/blob/master/download/elasticsearch-readonlyrest-v1.9.1_es-v2.3.1.zip?raw=true ...
Downloading ...DONE
Verifying https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/blob/master/download/elasticsearch-readonlyrest-v1.9.1_es-v2.3.1.zip?raw=true checksums if available ...
Downloading ...DONE
Failed: MalformedInputException[Input length = 1]
NOTE: Unable to verify checksum for downloaded plugin (unable to find .sha1 or .md5 file to verify)
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@     WARNING: plugin requires additional permissions     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
* java.lang.reflect.ReflectPermission suppressAccessChecks
See http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
for descriptions of what these permissions allow and the associated risks.

Continue with installation? [y/N]y
Installed readonlyrest into /me/elasticsearch-readonlyrest-plugin/elasticsearch-2.3.1/plugins/readonlyrest
```

**Comment by stevesui** [comment]
@sscarduzio 
The problem was resolved! Again thanks a lot for the help.

./bin/plugin install https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/blob/master/download/elasticsearch-readonlyrest-v1.9.2_es-v2.3.2.zip?raw=true
-> Installing from https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/blob/master/download/elasticsearch-readonlyrest-v1.9.2_es-v2.3.2.zip?raw=true...
Trying https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/blob/master/download/elasticsearch-readonlyrest-v1.9.2_es-v2.3.2.zip?raw=true ...
Downloading ...DONE
Verifying https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/blob/master/download/elasticsearch-readonlyrest-v1.9.2_es-v2.3.2.zip?raw=true checksums if available ...
Downloading ...DONE
Failed: MalformedInputException[Input length = 1]
NOTE: Unable to verify checksum for downloaded plugin (unable to find .sha1 or .md5 file to verify)
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@     WARNING: plugin requires additional permissions     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
* java.lang.reflect.ReflectPermission suppressAccessChecks
See http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
for descriptions of what these permissions allow and the associated risks.

Continue with installation? [y/N]y
Installed readonlyrest into /home/ssui/elasticsearch-2.3.2/plugins/readonlyrest
.
/bin/plugin list
Installed plugins in /home/ssui/elasticsearch-2.3.2/plugins:
    - readonlyrest

**Comment by sscarduzio** [comment]
My pleasure @stevesui! Thanks for pointing out this bug in the docs!
