### ISSUE TITLE
errors in "USE CASE 2"

### ISSUE THREAD

**Issue by pdelong42** [sscarduzio/elasticsearch-readonlyrest-plugin#60]
The example as stated in "USE CASE 2" causes elasticsearch to fail to start.

I've [attached an excerpt](https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/files/241327/foo.txt) of the output of `journalctl _SYSTEMD_UNIT=elasticsearch.service`.

Version info:

 - CentOS Linux release 7.2.1511 (Core)
 - OpenJDK Runtime Environment (build 1.8.0_77-b03)
 - Elasticsearch 2.3.1
 - readonlyrest 1.9.1

**Comment by pdelong42** [comment]
It seems the config parser isn't forgiving enough about the lack of whitespace between the colon (after the key-name) and the value.  It also doesn't seem to like something about the name "Logstash..." (probably the colon).

**Comment by pdelong42** [comment]
Oops, I forgot to mention: there seems to be a stray hyphen above the first stanza (the "Salesmen" section).  Is it there for a specific reason?  Or is it a no-op?  If it's not a no-op, could it be causing any subtle problems?

**Comment by sscarduzio** [comment]
Hey @pdelong42 thanks for pointing this mess out to me and sorry for the problems it caused. 
I have a new, tested working USE CASE 2 configuration and better instructions. Also, I released a new version of the plugin that finally make it possible to show people only certain indices in Kibana.

**Comment by sscarduzio** [comment]
@pdelong42 can we close this?

**Comment by pdelong42** [comment]
Yes, go ahead.  Looks good.  Thanks!
