### ISSUE TITLE
Basic Authorization failed on ES-7.8.0 with ROR-1.20.0

### ISSUE THREAD

**Issue by dzyubanv** [sscarduzio/elasticsearch-readonlyrest-plugin#612]
I setup new ES-7.8 cluster with 2 hosts, 2 master and 2 data nodes on each host 
I also installed ROR 1.20.0 (readonlyrest-1.20.0_es7.8.0.jar) on one master node 
Environment: RHEL 5.11, JDK 1.8.0_65
My readonlyrest.yaml is as follows
readonlyrest:
    enable: true
    response_if_req_forbidden: Access denied by ROR
    access_control_rules:
    - name: "Allow read/write all indexes for the vadim user only"
      type: allow
      groups: ["team1"]
      actions: ["cluster:monitor/*","indices:data/read*","indices:data/write*","indices:admin/create"]
      indices: ["*"]
    users:
    - username: vadim
      auth_key_sha256: ab...yz
      groups: ["team1"]
For the pair vadim:secpwd I generated the values like abc...xyz for auth_key_sha256 and MN...RS for Base64
Restarted the the master node with ROR successfully.
Checked cluster healt with request to not ROR protected node - showed 4 nodes joined and health=GREEN

Requested ROR protected node on Linux command line
curl -XGET http://host:port/_cat/indices?v -H 'Authorization: Basic MN...RS' 
Output
{"error":{"root cause" ... "reason":"Access denied by ROR" , node..., cluster... "due_to" ["OPERATION_NOT_ALLOWED"]... "status":401}

ES log file:
...
...xyz_node started
...Loading ReadonlyREST settings from index failed: cannot find index
...Loading ReadonlyREST from file: /path_to_file/readonlyrest.yml
...xyz_node ADDING BLOCK: {name: 'Allow read/write all indexes for the vadim user only', policy: ALLOW, rules: [groups,actions,indices]
...xyz_node Readonly REST plugin core was loaded ...
...xyz_node FORBIDDEN by default req={ ID:..., TYP:GetSettingsRequest, CGR:N/A, USR:vadim (attempted), BRS:true, KDX:null, ACT:indices:monitor/settings/get, OA:..., XFF:null, DA:..., IDX:*, MET:GET, PTH: /_cut/indices, CNT:<N/A>, HDR:Accept=*/*, Authorization=<OMOTTED>, Host=some_host/some_port, User-Agent=curl...OpenSSL/..., content-length=0, HIS:[Allow read/write all indexes for the vadim user only-> RULES:[groups->false], RESOLVED:[indices=*]]}

The same readonlyrest.yml configuration worked successfully without issues on the older ES-5.6.3 with ROR 1.16.15 (readonlyrest-1.16.15_es5.6.30.jar) 

Any help on this issue would be appreciated

Thanks

**Comment by coutoPL** [comment]
`PTH: /_cut/indices` <-- this one looks line a typo in path

**Comment by HagK** [comment]
Hi dzyubanv,

Am 2020-07-10 02:58, schrieb dzyubanv:
> I also installed ROR 1.20.0 (readonlyrest-1.20.0_es7.8.0.jar) on one
.....
> access_control_rules:
> - name: "Allow read/write all indexes for the vadim user only"
> type: allow
> groups: ["team1"]
> actions:
> ["cluster:monitor/_","indices:data/read_","indices:data/write*","indices:admin/create"]
> indices: ["*"]
> users:
> - username: vadim
....
> ...xyz_node FPORBIDDEN by default req={ ID:...,
> TYP:GetSettingsRequest, CGR:N/A, USR:vadim (attempted), BRS:true,
> KDX:null, ACT:indices:monitor/settings/get, OA:..., XFF:null, DA:...,

allow the action   ACT:indices:monitor/settings/get   maybe 
indices:monitor/*


> IDX:_, MET:GET, PTH: /_cut/indices, CNT:<N/A>, HDR:Accept=_/_,

really 'cut' is logged on /_cat/ request?

> (readonlyrest-1.16.15_es5.6.30.jar)

between ES 5.6 and 7.8 we have some changes by elastic, also with ACL

regards
Hagen

**Comment by sscarduzio** [comment]
this is being discussed in the forum too
https://forum.readonlyrest.com/t/authorization-failed-on-es-7-8-0-with-ror-1-20-0/1622/2

**Comment by dzyubanv** [comment]
Thank you very much for your feedback Simone and Mateusz

Followed your advise I tried adding to list of allowed actions in my readonlyrest.yaml the "indices:monitor/settings/get" and "indices:monitor/*"
Restared ROR protected node and 
curl -XGET http://host:port/_cat/indices?v -H 'Authorization: Basic MN...RS' 
gave me the same response
{"error":{"root cause" ... "reason":"Access denied by ROR" , node..., cluster... "due_to" ["OPERATION_NOT_ALLOWED"]... "status":401}
The ES log showed the same information as before changes
...xyz_node **FORBIDDEN by default** req={ ID:..., TYP:GetSettingsRequest, CGR:N/A, USR:vadim (attempted), BRS:true, KDX:null, ACT:indices:monitor/settings/get, OA:..., XFF:null, DA:..., IDX:*, MET:GET, **PTH: /_cut/indices**, CNT:<N/A>, HDR:Accept=*/*, **Authorization=OMITTED**, Host=some_host/some_port, User-Agent=curl...OpenSSL/..., content-length=0, HIS:[Allow read/write all indexes for the vadim user only-> RULES:[groups->false], RESOLVED:[indices=*]]}

My concerns are about the "**FORBIDDEN by default**" and **"Authorization=OMITTED"** in the ES log and I have a filling may be some default value(s) need to be overriden somehow/somewhere, may be in the readonlyrest.yml or elasticsearch.yml (?)
Making url REST requests to Not ROR protected node, like list indices, list nodes, cluster health, return good responses.
The same requests to ROR protected node with -H 'Authorization: Basic MN...RS' gaves response "Access denied by ROR" and the ...xyz_node FORBIDDEN by default req={... in the ES log

@Mateusz
In regards to your question "really 'cut' is logged on /_cat/ request?" - yes, in ES log file there is the PTH: /_cut/indices

I did some reserach and not found any specifics/bugs/issues in regards to current ES-7.8 release along with readonlyrest-1.20.0_es7.8.0.jar

Any other ideas, hints, prompts what else might be checked on, changed, tested or whatever will be appreciated  

Thanks in advance

**Comment by coutoPL** [comment]
solved here: https://forum.readonlyrest.com/t/authorization-failed-on-es-7-8-0-with-ror-1-20-0/1622/32
