### ISSUE TITLE
Allow users to see his own Kibana stored objects (dashboards, vizualizations, etc)

### ISSUE THREAD

**Issue by nitram4** [sscarduzio/elasticsearch-readonlyrest-plugin#62]
Hello, now when authentication for Kibana works and can select users to see their indices and define actions, it would be beneficient if we can filter also Kibana Objects.
I read blog about how Kibana stores data in .kibana index:
https://www.elastic.co/blog/kibana-under-the-hood-object-persistence

Inwas wondering if we can filter requests to this index on specific users.
For example user "marketing" will have all the objects saved as "marketing_visualization1" and readonly plugin will allow read only his objects.
Because currently all users see all objects which are stored in Kibana. If user has right to create ones it can make mess.
Advanced solution would be when readonly plugin will rewrite all write and read requests to .kibana index and adding the user ID.
What donyou think?

**Comment by haizaar** [comment]
I'm not an author, but please note that Kibana does not have a notion of "users" - all requests from Kibana will come under a single user defined in Kibana's settings. I believe what you are asking for is a-user level permissions for Kibana itself.

**Comment by nitram4** [comment]
Yes, thats true but since we are doinf lets say "man in the middle" we can do the defferentiation between users based on visualization naming convention.

**Comment by sscarduzio** [comment]
I'm trying to think a way we could think of this in the most kibana-agnostic, generic way. Would it work if we had an on-the-fly requested index renaming? We already have a system to read the list of indices the request refers to. In theory we could replace the name of an index with another string according to what user is logged in.. Not sure if just editing the list of parsed indices will work though.

**Comment by nitram4** [comment]
Ah, you mean on the fly replacing name of index, in this case for example .kibana index which stores all the information about kibana settings? So if user1 ligs in readonly plugin will on the fly rewrite the lets say .kibana.user1 index in EL to .kibana index to present it to Kibana. This should be ever better solution I have proposed, since all users will have their own settings/dashboards.... The only issue is when you would like to share the dashboards (all users to see certain visualization) these would have to be jmported manually.

**Comment by sscarduzio** [comment]
yeah this whole per-user index translation (provided it's feasible) is not a silver bullet. Your proposal about name spacing the dashboard objects depends on document-level security, and although it's in the pipeline, I don't yet have a feature design/strategy in mind. 
Truth is, adding the returned documents (even only scanning the names of the returned docs) to the request context would unlock a lot of features, included the one you described.
Got to bump this up in priority.

**Comment by nitram4** [comment]
I see that most wanted feature here is LDAP conpatibility, but any chance that this will be be taken into consideration ? :-) Will definitely stay simple and powerful compares to Search-Guard....

**Comment by nitram4** [comment]
Cant wait for any of the new features :-) How do you see the timeframe of the additional features?

**Comment by sscarduzio** [comment]
I'll probably have more time in July, work has been crazy lately. In general, I'll definitely I'll have a lot more time in September, because 1st September will be my last day there and afterwards I might also take some ES consultancy gigs related to the plugin (a few companies already asked me in the past, but I had to turn down).

**Comment by sscarduzio** [comment]
@nitram4 I discovered this and it reminded me of this discussion: https://www.elastic.co/blog/restricting-users-kibana-filtered-aliases

Definitely related, if not for implementing the feature, to work around the absence of it.

**Comment by nitram4** [comment]
@sscarduzio In it not related to Kibana 3? Kibana 4 actually "hides" these requests, so it is not so easy to filter on nginx level. And lastly the reason I use readonly plugin is not to use the nginx one :-)

**Comment by nitram4** [comment]
any free time to look at this?
