### ISSUE TITLE
Users and index dynamic map

### ISSUE THREAD

**Issue by itemca** [sscarduzio/elasticsearch-readonlyrest-plugin#63]
Hey,
This plugin works on static config files ? Can we work with API to create new user / index permission ? I would like to implement user management in KIbana that will work with readonly-plugin . We need an API functions for that.

thanks

**Comment by sscarduzio** [comment]
This sounds really interesting, and would expand the scope of this plugin to have a dedicated index for storing the state (a la Shield/Kibana). Not a small change, but definitely can be done. 
Would you be able to give a pull request I can review/expand on?
