### ISSUE TITLE
Debug clarification

### ISSUE THREAD

**Issue by danielmotaleite** [sscarduzio/elasticsearch-readonlyrest-plugin#64]
in https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/wiki/Supported-Rules you say this:

      If in doubt, set ReadOnlyRest debug level to INFO and include an "actions": entrance in every rule. This will show the action received.

I assume that the log level should go to the elasticsearch logging.yml, but what should i use there?
`logger.ReadOnlyRest: INFO` ?

Also, for the _action_ in rules without any action filter (ie: apply to all actions), should i use just `actions:` or something like  `actions:["*"]`

Can you explain this or even better give one example?

**Comment by sscarduzio** [comment]
Hi @danielmotaleite 
Sure, that indeed is another case of crappy documentation. Well spotted. I fixed, rewarded and put it under a "troubleshooting" section
