### ISSUE TITLE
Header auth-key

### ISSUE THREAD

**Issue by Christian1626** [sscarduzio/elasticsearch-readonlyrest-plugin#65]
Hello 
I'm trying to do a redirection to my kibana and I would like to add the auth-key in header, thus I don't need to authenticate. 
Here my role:
`    - name: Kibana Server `
`      auth_key: admin_kibana:admin_kibana`
     ` type: allow
` 

And I added the auth-key (base on 64bits) in the following header:
`Authorization:Basic YWRtaW5fa2liYW5hOmFkbWluX2tpYmFuYQ==`

Unfortunatly it doesn't work, do you have an idea where it is coming from ?

Sincerely,
Chris.

**Comment by sscarduzio** [comment]
Watch your indentation! Make sure the `auth_key` and `type` are  indented at the same level of `name` :)

**Comment by Christian1626** [comment]
yes, they are at the same level. The issue is not in my elasticsearch config but on the header side. I can loggin in my Kibana with this role. But when I'm on my other website and doing a redirection to Kibana with the Authorization header. The authentication popup still appear.

**Comment by Christian1626** [comment]
So any idea how to prevent Basic Authentication form to popup :D  ?

**Comment by sscarduzio** [comment]
Hey @Christian1626! Yeah I didn't really understand your setup, but if it works as expected when you are in the actual Kibana page, integrating with another website sounds like a web-architectural problem. When you get to the bottom of it, please feel free to ask if you need some targeted behaviour modifications on the plugin side.

**Comment by seuf** [comment]
I think the plugin should return a 401 unauthorized instead a 403 forbidden

**Comment by sscarduzio** [comment]
Hi @seuf it kinda of does already.
Here is how it works right now when your request doesn't match any `type: allow` block:
- if you have at least one ACL block that includes the `auth_key` rule: responds 401
- else (that is, if `auth_key` rule is never used in your conf): responds 403

BTW, I should make sure this behaviour works also for the newly introduced hashed version called `auth_key_sha1` which I invite you guys to use!

**Comment by seuf** [comment]
I have multiple rules with auth_key_sha1, but when I'm trying to access to my /_plugin/gui I got a 403 forbidden without password prompt before..

**Comment by sscarduzio** [comment]
Yep it's expected (see above). I committed a fix yesterday to address that, but I didn't release yet.

**Comment by seuf** [comment]
Greats ! I didn't this your commit d9656f7 ..
When do you plan to release the next version (with group acl \o/ ) ?

**Comment by sscarduzio** [comment]
I can do it today if you need it, no problem :)
What versions of ES do you need to be supported?

**Comment by seuf** [comment]
I would appreciate :) We are currently using es 2.3.4

**Comment by sscarduzio** [comment]
https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/releases/tag/v1.11.0_es-v2.3.4

**Comment by seuf** [comment]
Thank's ! I've deployed it to my "dev" environment, and it works !

**Comment by sscarduzio** [comment]
Very glad to hear, mate 🙌
