### ISSUE TITLE
Error when adding _index_template (PUT _index_template/template_1 doesn't work)

### ISSUE THREAD

**Issue by ghost** [sscarduzio/elasticsearch-readonlyrest-plugin#656]
Versions: ES 7.9.0 with ROR 1.22.1_es7.9.0

When trying to add a new index template with the _index_template API, an error is returned:

PUT _index_template/template_1
```
[2020-09-01T19:49:12,761][ERROR][t.b.r.e.r.c.t.ReflectionBasedIndicesEsRequestContext] [node-1] [1612939774-1405143#931225] Cannot update Request request. We’re using reflection to modify the request indices and it fails. Please, report the issue
```

Note that DELETE and GET on the _index_template API work as expected.

This issue has been reported in the forum by kkt2mail here:
https://forum.readonlyrest.com/t/cannot-put-index-template-template-1/1681

I copied it here for easier follow up.

**Comment by coutoPL** [comment]
This is done. Will be released with ROR 1.28.0 (probably this weekend). Link to pre build can be find [here](https://forum.readonlyrest.com/t/cannot-put-index-template-template-1/1681/22)
