### ISSUE TITLE
Does this work on ES 7.10.0?

### ISSUE THREAD

**Issue by jpmckinney** [sscarduzio/elasticsearch-readonlyrest-plugin#663]
This page only goes up to 7.9.3: https://readonlyrest.com/download/

**Comment by coutoPL** [comment]
Hi @jpmckinney 
Are you trying to say, that there is no binaries for ES 7.10.0 yet? 
If so, yes - we are working on it and it will be available soon (it's a matter of days)

**Comment by coutoPL** [comment]
Done. ROR for ES 7.10.0 is ready and available for download (https://readonlyrest.com/download/).

Please notice that at the moment there is sth wrong with sorting.
