### ISSUE TITLE
Support for certificates in PEM format, in addition to keystore format

### ISSUE THREAD

**Issue by jpmckinney** [sscarduzio/elasticsearch-readonlyrest-plugin#675]
For comparison, Elasticsearch supports both (e.g. in the instructions on this page: https://www.elastic.co/guide/en/elasticsearch/reference/7.10/configuring-tls.html).

I use Apache's [mod_md](https://httpd.apache.org/docs/2.4/mod/mod_md.html) to automatically get and renew certificates from Let's Encrypt. Like certbot and other tools, it creates certificates in PEM format.

While I can add a hook to convert to PKCS#12 format and then to keystore format (using commands from this [blog post](https://web.archive.org/web/20190410202118/https://maximilian-boehm.com/en-gb/blog/create-a-java-keystore-jks-from-lets-encrypt-certificates-1884000/), for example), it would be simpler to just point readonlyrest.yml to the certificates in PEM format.

**Comment by coutoPL** [comment]
@jpmckinney please check out this: https://docs.readonlyrest.com/elasticsearch#using-lets-encrypt

**Comment by jpmckinney** [comment]
@coutoPL Yes, I already do those steps. It would be nice to just be able to use the original PEM files instead of converting to PKCS12. It's nice that converting to JKS Keystore is (now) optional.

**Comment by coutoPL** [comment]
hi @jpmckinney [this is supported](https://github.com/beshu-tech/readonlyrest-docs/blob/master/elasticsearch.md#pem-files-instead-of-a-keystore-andor-truststore) starting from ROR 1.44.0
