### ISSUE TITLE
despite force_load_from_file=true, ROR plugin tries to load .readonlyrest index

### ISSUE THREAD

**Issue by fbaligand** [sscarduzio/elasticsearch-readonlyrest-plugin#683]
Hi,

I set this in my readonlyrest.yml file:
``` yaml
readonlyrest:
    force_load_from_file: true
```

But despite this configuration, ROR tries to load .readonlyrest index:
```
[2021-01-21T09:43:14,544][INFO ][t.b.r.c.l.ConfigLoadingInterpreter$] [DESKTOP-8QK15CF] [CLUSTERWIDE SETTINGS] Loading ReadonlyREST settings from index (.readonlyrest) ...
[2021-01-21T09:43:15,570][INFO ][t.b.r.c.l.ConfigLoadingInterpreter$] [DESKTOP-8QK15CF] Loading ReadonlyREST settings from index failed: cannot find index
```

Could you fix it, so that, if this flag is true, ROR does not try to load .readonlyrest index?

Issue reproduced with : 
- ES: 7.8.1
- ROR: 1.26.1

**Comment by coutoPL** [comment]
The `force_load_from_file: true` setting has to be set in `elasticsearch.yml`, not in `readonlyrest.yml`. ROR reads `elasticsearch.yml` first and then decides if it should load settings from index or from file. I figured out that documentation was wrong, but I've already fixed it: https://github.com/beshu-tech/readonlyrest-docs/blob/master/kibana.md#malformed-in-index-settings

**Comment by fbaligand** [comment]
Hi @coutoPL, 

Indeed, I just tried in elasticsearch.yml, and it works great!
Thank you for your quick and useful answer!
