### ISSUE TITLE
Builds for 5.0

### ISSUE THREAD

**Issue by genorex** [sscarduzio/elasticsearch-readonlyrest-plugin#69]
Will there be builds for 5.0? Currently I receive 'elasticsearch' directory is missing in the plugin zip.
My search leads to 'site plugins have been removed. They should be implemented as kibana plugins'

**Comment by sscarduzio** [comment]
Hi @genorex. This is not a site plugin.

As far as I understood (somebody correct me if I'm wrong), 5.0 will be the first (sic!) the version of the Elastic stack (ES+Kibana+LogStash+Beats). Every individual stack component will continue to be separately downloadable and follow the usual release cycle. 

So I intend to release builds for next versions of ES which in parallel will be distributed as part of this "Stack".

Does this answer your question?

**Comment by genorex** [comment]
This sounds good to me. Thank you for the quick feedback. I will close this.
