### ISSUE TITLE
When user access a forbidden resource, the user cannot access to kibana dashboards in 7.5.1

### ISSUE THREAD

**Issue by aryef** [sscarduzio/elasticsearch-readonlyrest-plugin#697]
Elastic, kibana and plugin version: 7.5.1
Chrome version: 78.0.3904.70

Process:

1. User sign in successfully
2. User access a forbidden resource
3. User get a chrome pop-up to insert the credentials again
4. user insert the right credentials 
5. user try to access kibana dashboards and got the exception (**disconnected network, so the error redacted**):

`Error fetching data
.. reason: forbidden, "due_to":OPERATION_NOT_ALLOWED, status: 401
`

In version 6.3 this works.

**Comment by sscarduzio** [comment]
Hi @aryef, 

Are you using the Kibana plugin? What version (7.5.1 is the ES version, not ROR version).
Are you a paying subscriber?

**Comment by david-uash** [comment]
Hey. my name is David and i work with Arie 
we are note a paying subscriber 
and the plugin we use is 1.19.0_es.7.5.1

**Comment by coutoPL** [comment]
@david-uash did you try to upgrade ROR? Currently we have ROR 1.27.0
