### ISSUE TITLE
Set up with elastic.js

### ISSUE THREAD

**Issue by jensfinnas** [sscarduzio/elasticsearch-readonlyrest-plugin#7]
I'm hitting `request matches no rules, forbidden by default` when I try to do queries from a web app using elastic.js, which sends POST requests to the ES server.

I'm developing on 127.0.0.1 and the plugin is set up to allow all traffic from this host.

`- name: full access to internal servers`
`type: allow`
`hosts: [127.0.0.1, localhost]`

CURL works fine though. What do I do wrong?

**Comment by sscarduzio** [comment]
Hi @jensfinnas!
Can you paste your full plugin configuration and the failing call URL? And also the curl command that succeeds, please?

**Comment by sscarduzio** [comment]
I think this can be the same as #8
