### ISSUE TITLE
Courier Fetch Error While launching Kibana

### ISSUE THREAD

**Issue by saurabhcts** [sscarduzio/elasticsearch-readonlyrest-plugin#71]
I am trying to configure readonlyrest plugin for my local ELK setup with following settings in elasticsearch.yml.

readonlyrest:
    enable: true
    response_if_req_forbidden: Forbidden by ReadonlyREST ES plugin
    access_control_rules:

    - name: Kibana Server (we trust this server side component, full access granted via HTTP authentication)
      auth_key: admin:passwd3
      type: allow

    - name: Developer (reads only logstash indices, but can create new charts/dashboards)
      auth_key: dev:dev
      type: allow
      kibana_access: ro+
      indices: ["<no-index>", ".kibana*", "apperror*", "default"]

I have updated kibana.yml with followsing entries:

elasticsearch.username: "admin"
elasticsearch.password: "passwd3"

After restarting the stack successfully I tried to launch kibana dashboard; however I am facing below exception:

 Courier Fetch Error: unhandled courier request error: [security_permission_exception] Insufficient permissions to extract the indices. Abort! Cause: org.elasticsearch.action.get.MultiGetRequest.indices() 

I also tried to enable/disable http.cors.enabled setting; however the issue is still thr. Please advise.

ES Version: 2.2.0
Kibana: 4.4.1

**Comment by sscarduzio** [comment]
What package did you install?

**Comment by saurabhcts** [comment]
thanks sscarduzio; I reinstalled the package 1.7 and it has resolved the issue; however now I am not able to login using dev:dev; whereas I can login with admin:passwd3.

Not sure what I am missing.

**Comment by sscarduzio** [comment]
Sorry but you really need the plugin version 1.9.3 to run the readme example. I can make a build for your ES version.

**Comment by saurabhcts** [comment]
sure thanks. It would be very helpful.

**Comment by sscarduzio** [comment]
Here you go https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/blob/master/download/elasticsearch-readonlyrest-v1.9.3_es-v2.2.0.zip?raw=true

**Comment by saurabhcts** [comment]
Thanks a ton :+1: It helped.

Could you please also help me with the build for ES v2.3.1 as well? I have a staging env running with this version.

**Comment by sscarduzio** [comment]
http://www.filedropper.com/elasticsearch-readonlyrest-v193es-v231 (sorry I made a mess with with my local repo and I'm in a hurry :D )

**Comment by saurabhcts** [comment]
Thanks a Ton Man :)
