### ISSUE TITLE
Multi-homed site

### ISSUE THREAD

**Issue by corneil** [sscarduzio/elasticsearch-readonlyrest-plugin#72]
We want to provide dashboard for our customers. Users from one customer one or more dashboards and indexes and the users of a different customer will have access to their own dashboards and indexes. 
I want to direct them to the ELK installation from an application on a different machine and each customer group will have their own machine.
I was initially thinking of doing a Shibboleth (SAML) plugin in Apache HTTP Server.

Can you outline an approach using this plugin?
- Would I need to update the ACL file when new customers are rolled out?
- Is there a way that I can pass header information that would indicate which index(es) the user may use so that ACL updates are not needed?

**Comment by sscarduzio** [comment]
Hi @corneil, thanks for sharing your real-life scenario, this is always very appreciated!

At the time being, this plugin does not have the notion of neither user groups, or of dynamically loaded settings. All the plugin knows about is being read at start up time from elasticsearch.yml. 

My users have been pushing for an LDAP integration which most likely would cover also your business case. By that I mean: given a mapping between users, groups and resources between ES/Kibana and LDAP world, the authentication and authorization business logic would be entirely delegated to an external, well known specialized system, that is the LDAP server. 

I don't have immediate plans to start developing this right now (my full time job is being quite demanding in this period). Nevertheless, I don't think it's a super complicated feature. This is why I'd encourage the community to contribute this feature (as of #66 tagged as "help wanted"). Would you be interested? I surely can give some pointers along the way :)

**Comment by corneil** [comment]
With SAML the information you would retrieve from LDAP can by part of the SAML interaction. I will dig a bit to see if I can come up with some ideas.

**Comment by sscarduzio** [comment]
Housekeeping here (after 8 months). This is cool and can be done today with static ACL in the conf file. It still would require a restart. To work like described,  this requires LDAP to work.  
Pointing this issue to #66
