### ISSUE TITLE
Help on Backport to 1.7.x

### ISSUE THREAD

**Issue by TimCgn** [sscarduzio/elasticsearch-readonlyrest-plugin#75]
I'm very impress of your work. The plugin very helpfull. Very good work!!!

At the moment a have the problem, that I have a big ES-Cluster on Version 1.7.3 and I'm unable to update this cluster. So is it possible for me to make a backport of the current version to 1.7.3?

Thanks for your work und best regards
Tim

**Comment by dfr0** [comment]
Good job, great plugin!!!

**Comment by TimCgn** [comment]
It' solved.
