### ISSUE TITLE
cors setting in example config results in errors with kibana 4.5.1

### ISSUE THREAD

**Issue by deradam** [sscarduzio/elasticsearch-readonlyrest-plugin#77]
I just installed elastic 2.3.3 and kibana 4.5.1 (via docker) and set up configuration use case 2. However the http.cors.enabled setting seem to break kibana. Some research revealed, that the cors setting should not be used anymore after kibana 3.x (https://github.com/elastic/kibana/issues/6719).

Maybe you can clarify that in the documentation!?

**Comment by sscarduzio** [comment]
Hi @deradam, thanks for pointing this out! Will certainly update the docs, thanks for contributing! 🚀
