### ISSUE TITLE
Potential security issue

### ISSUE THREAD

**Issue by JamieSlome** [sscarduzio/elasticsearch-readonlyrest-plugin#771]
Hey there!

I belong to an open source security research community, and a member (@ready-research) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by sscarduzio** [comment]
Hi @JamieSlome. You are right, we need the security file. I Will take care of adding it later today. In the meantime please contact support at readonlyrest.com. 

Thank you!

**Comment by sscarduzio** [comment]
I added the SECURITY.md as requested
https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/blob/develop/SECURITY.md

**Comment by JamieSlome** [comment]
@sscarduzio - thank you for your timely response here. Just for reference, you can view the report directly here:

https://huntr.dev/bounties/6b10fb54-c2f2-45d0-8459-63a941992114/

It is private and only visible to you (the owner of the repository). Let me know if you have any questions!

**Comment by JamieSlome** [comment]
@sscarduzio - you should have just received an e-mail to the address in your `SECURITY.md` with further details of the report.

**Comment by sscarduzio** [comment]
Hi @JamieSlome, thanks for this report. We fixed the issue already yesterday night. It affected an experimental part of our code (ROR proxy) that was never packaged and released to customers. So the impact is fortunately null.

**Comment by coutoPL** [comment]
this is fixed: https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/pull/773

**Comment by JamieSlome** [comment]
@coutoPL @sscarduzio - thanks for the update and contributions!
