### ISSUE TITLE
Problem installing readonly plugin

### ISSUE THREAD

**Issue by dfaropennetwork** [sscarduzio/elasticsearch-readonlyrest-plugin#80]
I've the elasticsearh version 2.3.3

:/usr/share/elasticsearch$ sudo wget https://download.elastic.co/elasticsearch/release/org/elasticsearch/plugin/logstash-input-beats/2.3.3/logstash-input-beats-2.3.3.zip
--2016-07-05 03:21:01-- https://download.elastic.co/elasticsearch/release/org/elasticsearch/plugin/logstash-input-beats/2.3.3/logstash-input-beats-2.3.3.zip
Resolving download.elastic.co (download.elastic.co)... 50.17.206.20, 23.21.169.22, 50.16.186.13, ...
Connecting to download.elastic.co (download.elastic.co)|50.17.206.20|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-07-05 03:21:01 ERROR 404: Not Found.

/usr/share/elasticsearch$ sudo bin/plugin install readonlyrest
-> Installing readonlyrest...
Trying https://download.elastic.co/elasticsearch/release/org/elasticsearch/plugin/readonlyrest/2.3.3/re+
ERROR: failed to download out of all possible locations..., use --verbose to get detailed information

/usr/share/elasticsearch$ sudo bin/plugin install --verbose logstash-input-beats logstash-output-elasticsearch 
-> Installing logstash-input-beats...
Trying https://download.elastic.co/elasticsearch/release/org/elasticsearch/plugin/logstash-input-beats/2.3.3/logstash-input-beats-2.3.3.zip ...
Failed: FileNotFoundException[https://download.elastic.co/elasticsearch/release/org/elasticsearch/plugin/logstash-input-beats/2.3.3/logstash-input-beats-2.3.3.zip]; nested: FileNotFoundException[https://download.elastic.co/elasticsearch/release/org/elasticsearch/plugin/logstash-input-beats/2.3.3/logstash-input-beats-2.3.3.zip]; 
ERROR: failed to download out of all possible locations..., use --verbose to get detailed information

**Comment by sscarduzio** [comment]
bin/plugin install https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/blob/master/download/elasticsearch-readonlyrest-v1.9.2_es-v2.3.2.zip?raw=true

**Comment by dfaropennetwork** [comment]
Perfect i resolved the issue :dancer:  i think that when i tried the repo was down

now after configured my enviorement i created so many roles and works fine, thanks for the plugin is awesome, more easy that shield and perform the same function.

**Comment by sscarduzio** [comment]
Amazing! Glad it's helpful! :)
