### ISSUE TITLE
Audit logging purpose

### ISSUE THREAD

**Issue by ld57** [sscarduzio/elasticsearch-readonlyrest-plugin#82]
Hi,

First, thanks for your plugin !
If you want me to contribute in Wiki page, just tell me ( regarding debug, or audit, if a way is found)

Following [#52](https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/issues/52), I started this thread regarding idea/suggestion for an access and activity logging for audit purpose.

My suggestion in [#52](https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/issues/52) is good for debugging, but quickly the log file grows so fast.

It may be possible to improve the logging for audit purpose with some minor change : 
Is it possible on your side to : 
1. change this event trigger type as INFO instead of DEBUG : 
   `[2016-07-20 15:57:49,166][DEBUG][plugin.readonlyrest.acl.blocks.rules.impl] Login as: username rc: { action: cluster:monitor/health, OA:127.0.0.1, indices:[], M:GET, P:/_cluster/health, C:, Headers:[]}`
2. change this event trigger type as INFO instead of DEBUG : 
   `[2016-07-20 15:57:49,166][DEBUG][plugin.readonlyrest.acl  ] Block ELKG admin group has matched: ELKG admin group match: true}`
3. lets keep this one as INFO like currently : 
   `[2016-07-20 15:57:04,180][INFO ][plugin.readonlyrest.acl  ] no block has matched, forbidding by default: { action: indices:monitor/stats, OA:127.0.0.1, indices:[], M:GET, P:/_stats/docs,store, C:, Headers:[]}`
4. regarding kibana server, it is a bit more complicated to read log, since it is spamming in log (kibana server tests connection to ES every x seconds).
   maybe it could be useful to treat kibana server connection in debug mode. At this moment, it is needed to standardize the kibana server access definition in elasticsearch.yml , to permit you to catch kibana events from your code and tag them as DEBUG instead of INFO ( I say that because following point 1,2 and 3, kibana server access would go to INFO and would spam log file).

Rgds

Ld

**Comment by ld57** [comment]
Closing - I updated the wiki to simplify the logging , giving 
- user logon name
- matched rules

**Comment by sscarduzio** [comment]
@ld57 really useful, I think it deserves its own wiki page and  a link in the readme!
