### ISSUE TITLE
How can I install this plugin locally?

### ISSUE THREAD

**Issue by shuangshui** [sscarduzio/elasticsearch-readonlyrest-plugin#84]
when I download the zip file of the right version and try to install it locally
"ERROR: Could not find plugin descriptor 'plugin-descriptor.properties' in plugin zip"
How can I solve this problem?

**Comment by sscarduzio** [comment]
that's probably a bug in the build process, what version are you trying to install? And what's your ES version?

**Comment by ld57** [comment]
Maybe you did not downloaded the jar version ( which contains descriptor)
[https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/blob/master/download/elasticsearch-readonlyrest-v1.9.4_es-v2.3.4.zip](https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/blob/master/download/elasticsearch-readonlyrest-v1.9.4_es-v2.3.4.zip)

**Comment by sscarduzio** [comment]
in the docs there's written `?raw=true` this is missing in your URL.

**Comment by sscarduzio** [comment]
is this still a problem @ld57 ?

**Comment by sscarduzio** [comment]
hahah sorry man, I need a holiday :D

**Comment by ld57** [comment]
ah I had in mind you just went back from holidays :)

kidding ahah
