### ISSUE TITLE
Config File Location

### ISSUE THREAD

**Issue by mtopper** [sscarduzio/elasticsearch-readonlyrest-plugin#85]
Sorry, probably an obvious question but I want to make sure I do it correctly:

The install documentation indicates that I should append to conf/elasticsearch.yml

For elastic search, I have /etc/elasticsearch/elasticsearch.yml

Is there a plugin specific configuration directory or file that I should be using or is the configuration intended to be appended to the 'main' config file?

**Comment by ld57** [comment]
Your yml file is the one in /etc/elasticsearch.

there is an example of configuration in the main page of git [https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin](https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin)


se use case 1 and 2.

tomorrow, I will post one of my config to show you how I did on my side.

ah, are you sure the plugin is installed correctly ?

did you check with "plugin list" command of elasticsearch ?

br

ld

**Comment by mtopper** [comment]
Thanks for the explanation.  It's not installed yet - I was just unsure about which config file to edit from reading the documentation, but that answered my question.
