### ISSUE TITLE
Readonlyrest Plugin 1.9.4 Unable to verify checksum

### ISSUE THREAD

**Issue by robinsonkwame** [sscarduzio/elasticsearch-readonlyrest-plugin#89]
<pre>
> curl 'localhost:9200'
{
  "name" : "Athena",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "2.3.5",
    "build_hash" : "90f439ff60a3c0f497f91663701e64ccd01edbb4",
    "build_timestamp" : "2016-07-27T10:36:52Z",
    "build_snapshot" : false,
    "lucene_version" : "5.5.0"
  },
  "tagline" : "You Know, for Search"
}
</pre>

<pre>
>/usr/share/elasticsearch/bin/plugin install https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/blob/master/download/elasticsearch-readonlyrest-v1.9.4_es-v2.3.5.zip?raw=true
</pre>
<pre>
-> Installing from https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/blob/master/download/elasticsearch-readonlyrest-v1.9.4_es-v2.3.5.zip?raw=true...
Trying https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/blob/master/download/elasticsearch-readonlyrest-v1.9.4_es-v2.3.5.zip?raw=true ...
Downloading ..............DONE
Verifying https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/blob/master/download/elasticsearch-readonlyrest-v1.9.4_es-v2.3.5.zip?raw=true checksums if available ...
Downloading ..............DONE
Failed: MalformedInputException[Input length = 1]
NOTE: Unable to verify checksum for downloaded plugin (unable to find .sha1 or .md5 file to verify)
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@     WARNING: plugin requires additional permissions     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
* java.lang.reflect.ReflectPermission suppressAccessChecks
See http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
for descriptions of what these permissions allow and the associated risks.

Continue with installation? [y/N]y
Installed readonlyrest into /usr/share/elasticsearch/plugins/readonlyrest
</pre>

regarding <pre> NOTE: Unable to verify checksum for downloaded plugin (unable to find .sha1 or .md5 file to verify)</pre>
Does the .zip have the right files included?

**Comment by sscarduzio** [comment]
Hi @robinsonkwame, unfortunately I didn't yet implement the checksum as part of the build process, and it sucks :(

But I benevolently accept contributions :)

**Comment by robinsonkwame** [comment]
PRs or cold hard cash?

**Comment by sscarduzio** [comment]
At the moment I cannot accept any compensation for this plugin, as it would go against the contract with my current employer. 

The good news is that my last day of work is September 1st.

Having said that, I value more good PRs than consultancy gigs: it adds more value and it's a sign of active community engagement in the project.

So yes, I would really appreciate if you could add this feature as a PR!

**Comment by Agorian** [comment]
Hi,
I am having a similar problem on Windows:

`./plugin.bat install https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/blob/master/download/elasticsearch-readonlyrest-v1.9.4_es-v2.3.4.zip?raw=true
-> Installing from https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/blob/master/download/elasticsearch-readonlyrest-v1.9.4_es-v2.3.4.zip?raw...
Trying https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/blob/master/download/elasticsearch-readonlyrest-v1.9.4_es-v2.3.4.zip?raw ...
Downloading ...............................DONE
Verifying https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/blob/master/download/elasticsearch-readonlyrest-v1.9.4_es-v2.3.4.zip?raw checksums if available ...
Downloading ...............................DONE
ERROR: invalid format for checksum file (SHA1), expected 1 line, got: 536
`

How can I install the plugin? 

Thanks a lot

**Comment by ld57** [comment]
Hi Agorian,

I also run on windows and had no problem to install it, but I used a different method :+1: 
just download the plugin zip file, and install using the command
`plugin.bat install --url file:///Full_Path_To/elasticsearch-readonlyrest-v1.9.4_es-v2.3.4.zip`

you can find more detail about manual isntallation [here](http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/modules-plugins.html#installing)

Ld

**Comment by sscarduzio** [comment]
I realised that the plugin installation binary was actually looking in the same directory (or URL) where the zip is found for a file with the same name of the zip plus .sha1 or .md5 suffix.
I just added this sha1 file generation as part of the build system. 

Can you try  to install the very latest plugin version for ES 2.4.0 to see if it works for you?

**Comment by sscarduzio** [comment]
fixed with moving to GitHub releases
