### ISSUE TITLE
ACL matching strictness

### ISSUE THREAD

**Issue by robinsonkwame** [sscarduzio/elasticsearch-readonlyrest-plugin#90]
Maybe a potential clarification on index strictness:

https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/wiki/Supported-Rules
says

<pre>
Indices: Match if the request touches indices whose name is "sales", starts with "logstash-" or a combination of both. See also the note on <no-index> below.
</pre>

But the [Block.java](https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/blob/master/src/main/java/org/elasticsearch/plugin/readonlyrest/acl/blocks/Block.java#L107-L122) effectively matches comma seperated indices if any allowed indices are present. This isn't as strict as only matching comma separated indices if and only if allowed indices are present.

e.g.,

<pre>http://***:9200/test_private,test_public/_search?q=data</pre> is allowed with
<pre>
readonlyrest:
    enable: true
    response_if_req_forbidden: Nope, you are forbidden from doing that.
    access_control_rules:
    - name: Read only for public indices
      type: allow
      actions: ["indices:data/read/*"]
      indices: ["test_public"]
</pre>

but not with the more restrictive

<pre>
readonlyrest:
    enable: true
    response_if_req_forbidden: Nope, you are forbidden from doing that.
    access_control_rules:
    - name: Explicitly block access to any combination to private indices
      type: forbid
      actions: ["indices:data/read/*"]
      indices: ["*private*"]

    - name: Read only for public indices
      type: allow
      actions: ["indices:data/read/*"]
      indices: ["test_public"]
</pre>

The search request fails since it includes indices not specifically whitelisted. So you may want to note this in the documentation with something like

<pre>
Indices: Match if the request touches indices whose name is "sales", starts with "logstash-" or any combination of both, including unspecified indices. Block forbidden indices with a prior rule. See also the note on <no-index> below.
</pre>

**Comment by sscarduzio** [comment]
Yep this is a great insight that is worth clarification and some examples too. Would you mind editing the wiki? And please include the example!

**Comment by robinsonkwame** [comment]
Done.

https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/wiki/Supported-Rules
https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/wiki/Supported-Rules#a-note-on-white-listing-strictness

**Comment by sscarduzio** [comment]
@robinsonkwame check out the latest version with strict `indices` rule. I'd love to hear your opinion on this :)

**Comment by sscarduzio** [comment]
@robinsonkwame this should behave as expected in v1.12.1

**Comment by sscarduzio** [comment]
The "note on whitelisting strictness" does not apply anymore. Nowadays this is working as @robinsonkwame expected  in the beginning.
