### ISSUE TITLE
How to permit dashboards for the users with rol (ro)  

### ISSUE THREAD

**Issue by dfaropennetwork** [sscarduzio/elasticsearch-readonlyrest-plugin#91]
I need to know hwo to permit the access for this type of users.

**Comment by sscarduzio** [comment]
we don't have that level of granularity (document level permission) yet. This is been requested in the past, didn't get around to settle for the best way to design this feature (not trivial).

**Comment by dfaropennetwork** [comment]
Ouu! thanks you, I was turn crazy :)

**Comment by danielmotaleite** [comment]
check my post in http://forum.readonlyrest.com/t/allow-kibana-readonly-access-to-create-short-urls/14/2
