### ISSUE TITLE
Single Server Setup - Kibana Read Only

### ISSUE THREAD

**Issue by rhysxevans** [sscarduzio/elasticsearch-readonlyrest-plugin#92]
Hi

I have a single server ELK setup with the elasticsearch-readonlyrest and the basics seem to be working.

The test setup, has the following in the elasticsearch.yaml file. (I have update the logstash output and kibana config files)

`readonlyrest:
    enable: true
    response_if_req_forbidden: Forbidden by ReadonlyREST ES plugin
    access_control_rules:

```
- name: Accept all requests from localhost
  type: allow
  hosts: [127.0.0.1]

- name: "Logstash can write and create its own indices"
  auth_key: logstash:logstash
  type: allow
  actions: ["indices:data/read/*","indices:data/write/*","indices:admin/template/*","indices:admin/create"]
  indices: ["logstash-*", "winlogbeat-*", "filebeat-*", "elastalert_status", "<no-index>"]

- name: Kibana Server (we trust this server side component, full access granted via HTTP authentication)
  auth_key: admin:passwd3
  type: allow   

- name: Developer (reads only logstash indices, but can create new charts/dashboards)
  auth_key: dev:dev
  type: allow
  kibana_access: ro+
  indices: ["<no-index>", ".kibana*", "logstash*", "winlogbeat*", "default"]
```

   `

My question is how can I give users only read access to the Kibana interface ?

I have played around with the rule order etc. At present I am able to see all my indices (I have deliberately left on out for the dev user)

Any ideas ?

Thanks

**Comment by sscarduzio** [comment]
Have you tried to add another user with `kibana_access: ro`  instead of `ro+`?

**Comment by rhysxevans** [comment]
Hi

Thanks, yes I have same result.

As a side when accessing kibana via the url I am not prompted for user credentials. I get full access straight away

Thanks

**Comment by sscarduzio** [comment]
this works completely differently now, should not have these issues anymore
