### ISSUE TITLE
Allowing updated ACLs on the fly

### ISSUE THREAD

**Issue by crain9412** [sscarduzio/elasticsearch-readonlyrest-plugin#93]
Are there any plans to allow updating our ACLs while ElasticSearch is running? https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-update-settings.html

**Comment by sscarduzio** [comment]
elasticsearch 5 supports re-reading the configuration file without restart, we could leverage that once we manage to get this thing ported. But for now there's some obstacles #108

**Comment by Globegitter** [comment]
Is this now something that is possible to implement, as ES 5.x is supported?

**Comment by sscarduzio** [comment]
@Globegitter not really, we're actually in the process of moving out of the ES settings framework all together for security reasons.

A similar effect of changing settings with no-restart can be achieved even today using the [Kibana plugin](https://readonlyrest.com/pro.html).
