### ISSUE TITLE
Can't able to authenticate with LDAP 

### ISSUE THREAD

**Issue by maheshwarangit** [sscarduzio/elasticsearch-readonlyrest-plugin#934]
I got error after restarting the elasticsearch service

{"error":{"root_cause":[{"type":"forbidden_response","reason":"forbidden","due_to":"READONLYREST_FAILED_TO_START"}],"type":"forbidden_response","reason":"forbidden","due_to":"READONLYREST_FAILED_TO_START"},"status":403}

These are my ldap configuration in readonlyrest.yml:

readonlyrest:
  access_control_rules:

  - name: "Require HTTP Basic Auth"
    type: allow
    auth_key: elastic:elastic

  ldaps:

  - name: "ldap1"
    host: "global.example.com"
    port: 389
    ssl_enabled: false
    ssl_trust_all_certs: true
    bind_dn: "cn=git,dc=global,dc=example,dc=com"
    bind_password: "password"
    ignore_ldap_connectivity_problems: true
    search_user_base_DN: "dc=global,dc=example,dc=com"
    user_id_attribute: "samaccountname"
    search_groups_base_DN: "cn=Rundeck,dc=global,dc=example,dc=com"

Please help me to resolve these issue

**Comment by sscarduzio** [comment]
Is the ldap server unreachable?

**Comment by maheshwarangit** [comment]
Nope,  it reachable 
i already integrated this ldap with some other services
like rundeck, zabbix, bookstack

**Comment by coutoPL** [comment]
@maheshwarangit please take a look in ES logs. You should find the reason why ROR refused to start. You can share the logs here if you are not able to figure out what's going on.

**Comment by ld57** [comment]
Hello,
Ldaps on 389? Ils ont intended?
Kind regards,
Fred
 
Envoyé depuis l'application Mail Orange
----------------De : Maheshwaran-git ***@***.***>Envoyé : jeudi 24 août 2023 19:27À : sscarduzio/elasticsearch-readonlyrest-plugin ***@***.***>Cc : Subscribed ***@***.***>Objet : Re: [sscarduzio/elasticsearch-readonlyrest-plugin] Can't able to authenticate with LDAP (Issue #934)
Nope,  it reachable
i already integrated this ldap with some other services
like rundeck, zabbix, bookstack

**Comment by maheshwarangit** [comment]
[2023-08-25T12:51:30,784][ERROR][t.b.r.e.IndexLevelActionFilter] [elasticsearch] [1521458576-780187206#2377] Cannot handle the /.fleet-actions/_fleet/global_checkpoints request because ReadonlyREST failed to start

it was the error i got

**Comment by maheshwarangit** [comment]
yes its 389 port

**Comment by coutoPL** [comment]
@maheshwarangit it would be great if you could share your solution with the community :)

You should definitely check the [LDAP authorization rule docs](https://docs.readonlyrest.com/elasticsearch#ldap_authorization). This is what you need

**Comment by coutoPL** [comment]
@maheshwarangit was it helpful?

**Comment by maheshwarangit** [comment]
![image](https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/assets/112377636/8674487f-113c-4f89-915c-929aa0d87785)

Any one please help to how to resolve this by readonlyrest

**Comment by sscarduzio** [comment]
we are working on making agents GUI work in Kibana in the next 2 weeks, it's a task in progress.

**Comment by coutoPL** [comment]
First of all, you need to tell us what did you do and show us your configuration
