### ISSUE TITLE
Getting KIBANA ACCESS DENIED not sure why or how to fix it

### ISSUE THREAD

**Issue by teebu** [sscarduzio/elasticsearch-readonlyrest-plugin#94]
Query path: index/_suggest from within sense. 

config:
```
    - name: can see stats, see all indices, cant do anything else
      auth_key: user:password
      type: allow
      kibana_access: rw
      methods: ["GET","OPTIONS","POST"]
      actions: ["indices:data/read/suggest", "indices:data/read/*", "indices:admin/get", "cluster:monitor/*", "indices:monitor/*"]
      indices: ["<no-index>", ".kibana*", "logstash*", "*"]
```

```
[2016-08-21 00:12:36,431][DEBUG][plugin.readonlyrest.acl.blocks.rules.impl] Login as: user rc: { action: indices:data/read/suggest, OA:xx.xxx.xxx.xxx, indices:[], M:POST, P:/_suggest, C:{
[2016-08-21 00:12:36,431][DEBUG][plugin.readonlyrest.acl.blocks.rules.impl] Login as: user rc: { action: indices:data/read/suggest, OA:xx.xxx.xxx.xxx, indices:[], M:POST, P:/_suggest, C:{
[2016-08-21 00:12:36,431][DEBUG][plugin.readonlyrest.acl.blocks.rules.impl] KIBANA ACCESS DENIED { action: indices:data/read/suggest, OA:xx.xxx.xxx.xxx, indices:[], M:POST, P:/_suggest, C:{
```

The 'admin' with no limitations works, this one with some restrictions cant.

I thought maybe the indices:data needed write for kibana by adding `"indices:data/write/*"`, so I tried that too, didn't fix it.

Also, if you omit 'inidices' does that mean 'all' ?

The only thing that allowed me to continue executing my queries is removing `kibana_access: rw`

**Comment by sscarduzio** [comment]
So: all the rules need to match in order for the whole block to match. 

The `kibana_access` rule won't match for any request that refers to any indices out of `.kibana-devnull`, `<no-index>` and `.kibana`. This behaviour can be only slightly changed specifying a custom index name to replace `.kibana` with another index.

If you want this user to use kibana AND allow (or forbid) some additional things, don't hesitate to create another block with the same credentials (auth_key) and allow/forbid extra indices or actions using additional rules.

**Comment by teebu** [comment]
thanks, I created another block with just Kibana stuff for the same user. I expected it to just encompass every rule I throw it. I don't think this was in the documentation.

I'm noticing `"indices:admin/get/*"` doesn't encompass
``` { action: indices:admin/get, OA:127.0.0.1, indices:[_all], M:GET, P:/_aliases, C:, Headers:[]}```

would `"indices:admin/get*"` get both?

**Comment by sscarduzio** [comment]
yeah get/* is different than get*.

**Comment by teebu** [comment]
I see, `indices:admin/mappings/get` on your list, but that wont pickup `{ action: indices:admin/get, OA:127.0.0.1, indices:[_all], M:GET, P:/_aliases, C:, Headers:[]}`

**Comment by sscarduzio** [comment]
Of course it won't, it's a different string.  When you say "my list" you mean KibanaAccessRule.java ?

BTW I added some more detailed docs about rules/blocks evaluation:
https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/wiki/Supported-Rules

**Comment by teebu** [comment]
Is there a rule for P: (paths?) For example, to block _aliases, `admin/get` has a lot of paths, including _mapping, etc. 

```{ action: indices:admin/get, OA:127.0.0.1, indices:[_all], M:GET, P:/_aliases, C:, Headers:[]}```

**Comment by sscarduzio** [comment]
No there's no rule for paths. And in general, I'd discourage any HTTP related rule because we now have the ability to make decisions on ES-level parameters like actions and indices. Otherwise this becomes as insecure as proxying ES REST calls through nginx .

I have a question: I understood you want to allow the action `indices:admin/get`. Is this something that Kibana is requesting? Or is it another tool/your app?

**Comment by teebu** [comment]
I am using Kibana & Kibana/sense so I assume yes that is where it's coming from.

**Comment by sscarduzio** [comment]
Ok you have a lot of things going on, how about you add a new allow block with the same `auth_key` and `actions: ["indices:admin/get"]` ? That would fix it.

**Comment by teebu** [comment]
Does each block request a new login?

**Comment by sscarduzio** [comment]
you'd need to repeat the same identical auth_key in the new block (user and pass) so that you won't allow the "indices:admin/get" action to the whole world.

**Comment by teebu** [comment]
do I need a new block for "indices:admin/get" it seems to be working

**Comment by sscarduzio** [comment]
yeah you need a separate block because blocks are in logical OR, and rules are in logical AND.
See the first part of this page: https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/wiki/Supported-Rules

**Comment by teebu** [comment]
That is a strange way of doing it, why are they not ORs? 

I would imagine, 

```
actions: ["indices:data/read/*", "indices:admin/mappings/*", "indices:admin/get", "indices:admin/get/*", "indices:admin/aliases/*", "cluster:monitor/*", "indices:monitor/*"]
``

Reads like: actions : read OR mappings OR admin/get/aliases ... allow

**Comment by sscarduzio** [comment]
Good point, a rule that accepts a list of arguments has all the arguments in OR!

Then - as described in the docs - all the rules in a block are in AND,  and all the blocks are in OR between each other.

**Comment by teebu** [comment]
So I don't need another block for "indices:admin/get", it just fits into the actions

**Comment by sscarduzio** [comment]
you need another block because kibana_access will make all the block not match (your custom action is not in the list of allowed kibana actions)

**Comment by teebu** [comment]
But the log doesn't show .kibana:

```
[2016-08-21 19:40:49,047][INFO ][plugin.readonlyrest.acl  ] no block has matched, forbidding by default: { action: indices:admin/get, OA:127.0.0.1, indices:[_all], M:GET, P:/_aliases, C:, Headers:[]}
```

**Comment by sscarduzio** [comment]
```
[2016-08-21 19:40:49,047][INFO ][plugin.readonlyrest.acl  ] no block has matched, forbidding by default: { action: indices:admin/get, OA:127.0.0.1, indices:[_all], M:GET, P:/_aliases, C:, Headers:[]}
```
Despite this request has an allowed action, this is not something the `kibana_access` rule is gonna match because it affects an index called `_all` which is neither of `.kibana` or `.kibana-devnull` or `<no-index>`. 

Again, you can use a separate block of rules with the same `auth_key` rule in order to match anything extra from what we expect coming from the plain vanilla Kibana.

**Comment by teebu** [comment]
How do you block specific actions of the `indices:admin/get` that are in the Path?

**Comment by sscarduzio** [comment]
Sorry I don't get the question, do you have a log line example?

**Comment by teebu** [comment]
`[2016-08-21 19:40:49,047][INFO ][plugin.readonlyrest.acl  ] no block has matched, forbidding by default: { action: indices:admin/get, OA:127.0.0.1, indices:[_all], M:GET, P:/_mapping, C:, Headers:[]}`

**Comment by sscarduzio** [comment]
if you need  to go this specific, you can always use the `uri_re` rule

**Comment by teebu** [comment]
I asked this yesterday. You said `No there's no rule for paths.`


But I am curious why it's not getting picked up by `indices:admin/mappings/*`

**Comment by sscarduzio** [comment]
yep sorry didn't come to mind soon enough, reason being it's been deprecated in favour of indices rule which is more secure if what you want is apply rules to indices.

**Comment by teebu** [comment]
I assumed they all go to the same underlying ES function, which I assumed is what your addon was picking up. IE: `mapping` in this case, which I assumed would fall under admin/mappings, but it is doing the same thing, but at a different end point. I hope I explained it properly. 

`indices:admin/mappings/` gets mapping for specific index.
`indices:admin/get path: _mapping` gets mapping for specific index.

**Comment by sscarduzio** [comment]
yeah nope, the `actions` rule is just string matching on the action field. It is very unfortunate that there's two equivalent HTTP request parsed by ES into different "action". I was not aware. And that also explain you had to work around this issue using the `uri_re` rule, which - plot twist - is not so deprecable after all.

**Comment by sscarduzio** [comment]
So basically the resolution of this was to use `kibana_access` plus a twin rule with the same `auth_key` of the one above, but with more specific`indices` and `uri_re` rules. Right?
