### ISSUE TITLE
Able to read any index, as long as at least one is readable

### ISSUE THREAD

**Issue by teebu** [sscarduzio/elasticsearch-readonlyrest-plugin#95]
Setting:
```
    - name: (public) Public read these indices
      type: allow
      actions: ["indices:data/read/*"]
      methods: ["GET","OPTIONS"]
      indices: ["test"]
```

Browser: 
`http://localhost:9200/test,*/_search`
`http://localhost:9200/test,.kibana/_search`

Result:
Every index in your ES is now readable 

Further testing:

```
    - name: Forbid test indices
      type: forbid
      actions: ["indices:data/read/*"]
      methods: ["GET","OPTIONS"]
      uri_re: ^/test.*
```

Url:
http://54.81.104.78/test,anotherindex/_search  => asks for auth
http://54.81.104.78/anotherindex,test/_search  => succeeds loading

Log for first, that asks for auth:
```
[2016-08-24 21:42:56,632][DEBUG][plugin.readonlyrest.acl  ] matched readonlyrest Rules Block :: { name: 'Forbid test indices', policy: FORBID}
[2016-08-24 21:42:56,632][DEBUG][plugin.readonlyrest.acl  ] Block Forbid test indices has matched: Forbid test indices match: true}
```
Log of success
```
[2016-08-24 21:38:54,981][DEBUG][plugin.readonlyrest.acl  ] [Forbid test indices] the request matches no rules in this block: { action: indices:data/read/search, OA:x.1.141.x, indices:[anotherindex test], M:GET, P:/anotherindex,test/_search, C:, Headers:[]}
```

OK that one wasnt fair, it uses reg exp. 

Here's another one:

```
    - name: Forbid test indices
      type: forbid
      actions: ["indices:data/read/*"]
      methods: ["GET","OPTIONS"]
      indices: ["test"]
```
http://54.81.104.78/test*/_search => asks for auth (working as expected, only because there is no allow for test* not because if forbids it) 
`[2016-08-24 21:48:32,306][INFO ][plugin.readonlyrest.acl  ] no block has matched, forbidding by default: { action: indices:data/read/search, OA:x.1.141.x, indices:[test*], M:GET, P:/test*/_search, C:, Headers:[]}`

http://54.81.104.78/test*,anotherindex/_search => loads data (not working as expected)

One possible solution: dont allow `*` or `,` in path using reg exp, However its bypassed by url encoded version.

`http://localhost:9200/test%2c%2A/_search` => `http://localhost:9200/test,*/_search`

So, that too can be part of the regex.

**Comment by sscarduzio** [comment]
This was spotted already by another user, who published a workaround in the wiki. 

https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/wiki/Supported-Rules#a-note-on-white-listing-strictness

However, I really believe this is an undesired behaviour and should be addressed as a bug.

Thanks for reporting it, @teebu.

**Comment by teebu** [comment]
I just wanted to let you know your "workaround" in the wikipedia is not very good, because you can just do `http://blah.com/index,*priv*/_search` to bypass the `*private*` or even `http://bla.com/index,*`

And that is a very big security hole. 

I looked at your code, it should be https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/blob/master/src/main/java/org/elasticsearch/plugin/readonlyrest/acl/blocks/rules/impl/IndicesRule.java#L34 and instead of returning on first match, you have to check against every index passed to validate the match.

**Comment by sscarduzio** [comment]
Yeah man, this is shit. Got to fix it, do you have time to make a pull request? The fix seems easy, and I'm travelling all week!

**Comment by teebu** [comment]
Sorry, not a java developer.

**Comment by robison** [comment]
Something along the lines of:
```
for(String i : rc.getIndices()) {
    if(m.match(i)){
        return MATCH;
    }
}
```

?

**Comment by robison** [comment]
Something along the lines of

```
for(String i : rc.getIndices()) {
    if(!m.match(i)){
        return NO_MATCH;
    }
}
```

?

**Comment by sscarduzio** [comment]
Yeah, please! make a pull request!

**Comment by robison** [comment]
Apologies on not putting together a quick PR, was wrapped up all weekend myself.
