### ISSUE TITLE
Source code for 2.2.0

### ISSUE THREAD

**Issue by vynguyenchantal** [sscarduzio/elasticsearch-readonlyrest-plugin#98]
Hi,
Please ignore the below message since I've already found the source:
"We are currently using Elasticsearch 2.2.0. Can you please provide me the link to source code supporting Elasticsearch 2.2.0?"

Thank you.
v/r
Chantal

**Comment by sscarduzio** [comment]
If you are already compiling it yourself, just download the source, change the elasticsearch version in `pom.xml` and run the `build.sh` to produce the plugin zip file which you'll find under `/target`.
