### ISSUE TITLE
Elasticsearch 2.4 support

### ISSUE THREAD

**Issue by rhysxevans** [sscarduzio/elasticsearch-readonlyrest-plugin#99]
Hi

Do you have an eta on support for ES 2.4 ?

Thanks

**Comment by sscarduzio** [comment]
I just released it :)

**Comment by rhysxevans** [comment]
Thanks, will give it a go this evening

**Comment by sscarduzio** [comment]
amazing, don't forget to close the issue if everything is all right. 👍

**Comment by rhysxevans** [comment]
from my very basic/limited testing seems to be working fine. Thanks
